prompt PATH TRANSLATE /vhr/rep/hpr/payroll_book
begin
uis.lang_ru('#a:/vhr/rep/hpr/payroll_book$select_job','Выбрать должность');
uis.lang_ru('#a:/vhr/rep/hpr/payroll_book$select_staffs','Выбрать сотрудника');
uis.lang_ru('#f:/vhr/rep/hpr/payroll_book','Книга начисления заработной платы');
uis.lang_ru('ui-vhr217:accrued, $1{currency}','Начислено, $1');
uis.lang_ru('ui-vhr217:advance payment','Аванс');
uis.lang_ru('ui-vhr217:begin date','Начало отчетного периода');
uis.lang_ru('ui-vhr217:credit','Заем');
uis.lang_ru('ui-vhr217:date','Дата');
uis.lang_ru('ui-vhr217:days','дней');
uis.lang_ru('ui-vhr217:deducted, $1{currency}','Удержано, $1');
uis.lang_ru('ui-vhr217:divisions','Подразделения');
uis.lang_ru('ui-vhr217:divisions: $1{division_names}','Подразделение, $1');
uis.lang_ru('ui-vhr217:end date','Конец отчетного периода');
uis.lang_ru('ui-vhr217:fact days','Отработано дней');
uis.lang_ru('ui-vhr217:fact hours','Отработано часов');
uis.lang_ru('ui-vhr217:filial name','Организация');
uis.lang_ru('ui-vhr217:final balance','Сальдо на конец');
uis.lang_ru('ui-vhr217:given year income','Доход с начала года');
uis.lang_ru('ui-vhr217:given year income tax','Налог на доходы с начала года');
uis.lang_ru('ui-vhr217:given year social payment','Социальный налог с начала года');
uis.lang_ru('ui-vhr217:hours','часов');
uis.lang_ru('ui-vhr217:iapa','ИНПС');
uis.lang_ru('ui-vhr217:income tax','Налог на доходы');
uis.lang_ru('ui-vhr217:initial balance','Сальдо на начало');
uis.lang_ru('ui-vhr217:job name','Должность');
uis.lang_ru('ui-vhr217:name','Ф.И.О.');
uis.lang_ru('ui-vhr217:npin','ПИНФЛ');
uis.lang_ru('ui-vhr217:order no','Порядковый номер');
uis.lang_ru('ui-vhr217:other accrual','Прочие начисления');
uis.lang_ru('ui-vhr217:other deduction','Прочие удержания');
uis.lang_ru('ui-vhr217:other payments','Прочие');
uis.lang_ru('ui-vhr217:payment','Оплаты');
uis.lang_ru('ui-vhr217:payment, $1{currency}','Оплата, $1');
uis.lang_ru('ui-vhr217:payroll book','Книга начисления заработной платы');
uis.lang_ru('ui-vhr217:payroll book for $1{month_year}','Книга начисления заработной платы за $1');
uis.lang_ru('ui-vhr217:penalty for absence','Штраф за отсутствие');
uis.lang_ru('ui-vhr217:penalty for day skip','Штраф за пропуск дня');
uis.lang_ru('ui-vhr217:penalty for early output','Штрафное время за ранний уход');
uis.lang_ru('ui-vhr217:penalty for late','Штрафное время за опоздание');
uis.lang_ru('ui-vhr217:pension payment','В том числе ИНПС');
uis.lang_ru('ui-vhr217:planned wage, $1{currency}','Плановый оклад');
uis.lang_ru('ui-vhr217:rank name','Разряд');
uis.lang_ru('ui-vhr217:social payment','Социальный налог');
uis.lang_ru('ui-vhr217:staff name','Сотрудник');
uis.lang_ru('ui-vhr217:staff number','Табельный номер');
uis.lang_ru('ui-vhr217:staffs','Сотрудники');
uis.lang_ru('ui-vhr217:tin','ИНН');
uis.lang_ru('ui-vhr217:total accrual','Всего');
uis.lang_ru('ui-vhr217:total deduction','Всего');
uis.lang_ru('ui-vhr217:total payment','Всего выплачено');
uis.lang_ru('ui-vhr217:total:','Итого:');
uis.lang_ru('ui-vhr217:turnout','Отработано');
uis.lang_ru('ui-vhr217:wage','Оклад');
uis.lang_ru('ui-vhr217:wage accrual','По окладу');
uis.lang_ru('ui-vhr217:wage, $1{currency}','Оклад, $1');
commit;
end;
/
