prompt PATH TRANSLATE /vhr/htt/schedule_registry
begin
uis.lang_ru('#a:/vhr/htt/schedule_registry+robot_add$add_calendar','Создать производственный календарь');
uis.lang_ru('#a:/vhr/htt/schedule_registry+robot_add$select_calendar','Выбрать производственный календарь');
uis.lang_ru('#a:/vhr/htt/schedule_registry+robot_add$select_robot','Выбрать позицию');
uis.lang_ru('#a:/vhr/htt/schedule_registry+robot_edit$add_calendar','Создать производственный календарь');
uis.lang_ru('#a:/vhr/htt/schedule_registry+robot_edit$select_calendar','Выбрать производственный календарь');
uis.lang_ru('#a:/vhr/htt/schedule_registry+robot_edit$select_staff','Выбрать сотрудника');
uis.lang_ru('#a:/vhr/htt/schedule_registry+staff_add$add_calendar','Создать производственный календарь');
uis.lang_ru('#a:/vhr/htt/schedule_registry+staff_add$select_calendar','Выбрать производственный календарь');
uis.lang_ru('#a:/vhr/htt/schedule_registry+staff_add$select_staff','Выбрать сотрудника');
uis.lang_ru('#a:/vhr/htt/schedule_registry+staff_edit$add_calendar','Создать производственный календарь');
uis.lang_ru('#a:/vhr/htt/schedule_registry+staff_edit$select_calendar','Выбрать производственный календарь');
uis.lang_ru('#a:/vhr/htt/schedule_registry+staff_edit$select_staff','Выбрать сотрудника');
uis.lang_ru('#f:/vhr/htt/schedule_registry+robot_add','Индивидуальный график (создание)');
uis.lang_ru('#f:/vhr/htt/schedule_registry+robot_edit','Индивидуальный график (изменение)');
uis.lang_ru('#f:/vhr/htt/schedule_registry+staff_add','Индивидуальный график (создание)');
uis.lang_ru('#f:/vhr/htt/schedule_registry+staff_edit','Индивидуальный график (изменение)');
uis.lang_ru('ui-vhr446:$1{error message} with robot $2{robot_id}','$1 связанная с позициям: $2');
uis.lang_ru('ui-vhr446:$1{error message} with staff $2{staff_id}','$1 связанная с сотрудникам: $2');
uis.lang_ru('ui-vhr446:1-all data types must be text','1. Все типы данных должны быть текстовыми');
uis.lang_ru('ui-vhr446:2-code must be unique','2. Коды должны быть уникальными');
uis.lang_ru('ui-vhr446:3-if there is no break, the beginning and the end of the break do not need to be written','3. Если Перерыв нет начало и конец перерыв не нужно писать');
uis.lang_ru('ui-vhr446:begin break time','Начало перерыва');
uis.lang_ru('ui-vhr446:begin time','Начало дня');
uis.lang_ru('ui-vhr446:break enabled(y or n (y-yes, n-no))','Перерыв(Y или N (Y - да, N – нет))');
uis.lang_ru('ui-vhr446:code','Код');
uis.lang_ru('ui-vhr446:code not found in metadata, please check code to correctly, date: $1{date}, row: $2{row}, code: $3{code}','Код не найден. Пожалуйста, проверьте код. Дата: $1, строка: $2, код: $3');
uis.lang_ru('ui-vhr446:division_name','Подразделение');
uis.lang_ru('ui-vhr446:employee_name','Сотрудник');
uis.lang_ru('ui-vhr446:end break time','Конец перерыва');
uis.lang_ru('ui-vhr446:end time','Конец дня');
uis.lang_ru('ui-vhr446:example','Смена 1');
uis.lang_ru('ui-vhr446:id','ИД');
uis.lang_ru('ui-vhr446:job_name','Должность');
uis.lang_ru('ui-vhr446:plan time','Явка');
uis.lang_ru('ui-vhr446:robot_name','Штат');
commit;
end;
/
