prompt PATH TRANSLATE /vhr/rep/hpd/transfer_multiple
begin
uis.lang_en('#f:/vhr/rep/hpd/transfer_multiple','Massive HR Transfer Order');
uis.lang_en('ui-vhr111:concluding term','Concluding Term');
uis.lang_en('ui-vhr111:contract date','Contract Date');
uis.lang_en('ui-vhr111:contract number','Contract Number');
uis.lang_en('ui-vhr111:contract term','Work Type');
uis.lang_en('ui-vhr111:director job name','Manager Job');
uis.lang_en('ui-vhr111:director name','Manager Full Name');
uis.lang_en('ui-vhr111:division name','Department');
uis.lang_en('ui-vhr111:employee name','Employee');
uis.lang_en('ui-vhr111:employment type name','Employment Type');
uis.lang_en('ui-vhr111:expiry date','Contract Expiry Date');
uis.lang_en('ui-vhr111:filial name','Organization');
uis.lang_en('ui-vhr111:fixed term','Fixed-term Labour Contract');
uis.lang_en('ui-vhr111:fixed term base name','Fixed-term Contract Reason');
uis.lang_en('ui-vhr111:hiring conditions','Hiring Requirements');
uis.lang_en('ui-vhr111:job name','Job');
uis.lang_en('ui-vhr111:journal date','Document Date');
uis.lang_en('ui-vhr111:journal name','Document Name');
uis.lang_en('ui-vhr111:journal number','Document Number');
uis.lang_en('ui-vhr111:labor function name','Labour Function');
uis.lang_en('ui-vhr111:old division name','Previous Department');
uis.lang_en('ui-vhr111:old job name','Previous Job');
uis.lang_en('ui-vhr111:old rank name','Previous Rank');
uis.lang_en('ui-vhr111:old schedule name','Previous Work Schedule');
uis.lang_en('ui-vhr111:old staff number','Previous PersNo');
uis.lang_en('ui-vhr111:old wage amount','Previous Salary');
uis.lang_en('ui-vhr111:old working day','Previous Working Day Duration');
uis.lang_en('ui-vhr111:old working week','Previous Working Week Duration');
uis.lang_en('ui-vhr111:old_robot name','Previous Position');
uis.lang_en('ui-vhr111:other conditions','Other Requirements');
uis.lang_en('ui-vhr111:quantity','Pay Rate');
uis.lang_en('ui-vhr111:rank name','Rank');
uis.lang_en('ui-vhr111:representative basis','Representative Reason');
uis.lang_en('ui-vhr111:robot name','Position');
uis.lang_en('ui-vhr111:schedule name','Work Schedule');
uis.lang_en('ui-vhr111:staff number','PersNo');
uis.lang_en('ui-vhr111:transfer base','Transfer Proof');
uis.lang_en('ui-vhr111:transfer begin','Transfer Start Date');
uis.lang_en('ui-vhr111:transfer end','Transfer End Date');
uis.lang_en('ui-vhr111:transfer kind name','Transfer Type');
uis.lang_en('ui-vhr111:transfer reason','Transfer Reason');
uis.lang_en('ui-vhr111:transfers','Employee List');
uis.lang_en('ui-vhr111:wage amount','Salary');
uis.lang_en('ui-vhr111:working day','Working Day Duration');
uis.lang_en('ui-vhr111:working week','Working Week Duration');
uis.lang_en('ui-vhr111:workplace equipment','Workspace Equipment');
commit;
end;
/
