prompt PATH TRANSLATE /vhr/rep/hpd/transfer
begin
uis.lang_en('#f:/vhr/rep/hpd/transfer','HR Transfer Order');
uis.lang_en('ui-vhr107:concluding term','Concluding Term');
uis.lang_en('ui-vhr107:contract date','Contract Date');
uis.lang_en('ui-vhr107:contract number','Contract Number');
uis.lang_en('ui-vhr107:contract term','Work Type');
uis.lang_en('ui-vhr107:director job name','Manager Job');
uis.lang_en('ui-vhr107:director name','Manager Full Name');
uis.lang_en('ui-vhr107:division name','Department');
uis.lang_en('ui-vhr107:employee name','Employee');
uis.lang_en('ui-vhr107:employment type name','Employment Type');
uis.lang_en('ui-vhr107:expiry date','Contract Expiry Date');
uis.lang_en('ui-vhr107:filial name','Organization');
uis.lang_en('ui-vhr107:fixed term','Fixed-term Labour Contract');
uis.lang_en('ui-vhr107:fixed term base name','Fixed-term Contract Reason');
uis.lang_en('ui-vhr107:hiring conditions','Hiring Requirements');
uis.lang_en('ui-vhr107:job name','Job');
uis.lang_en('ui-vhr107:journal date','Document Date');
uis.lang_en('ui-vhr107:journal name','Document Name');
uis.lang_en('ui-vhr107:journal number','Document Number');
uis.lang_en('ui-vhr107:labor function name','Labour Function');
uis.lang_en('ui-vhr107:old division name','Previous Department');
uis.lang_en('ui-vhr107:old job name','Previous Job');
uis.lang_en('ui-vhr107:old rank name','Previous Rank');
uis.lang_en('ui-vhr107:old schedule name','Previous Work Schedule');
uis.lang_en('ui-vhr107:old staff number','Previous PersNo');
uis.lang_en('ui-vhr107:old wage amount','Previous Salary');
uis.lang_en('ui-vhr107:old working day','Previous Working Day Duration');
uis.lang_en('ui-vhr107:old working week','Previous Working Week Duration');
uis.lang_en('ui-vhr107:old_robot name','Previous Position');
uis.lang_en('ui-vhr107:other conditions','Other Requirements');
uis.lang_en('ui-vhr107:quantity','Pay Rate');
uis.lang_en('ui-vhr107:rank name','Rank');
uis.lang_en('ui-vhr107:representative basis','Representative Reason');
uis.lang_en('ui-vhr107:robot name','Position');
uis.lang_en('ui-vhr107:schedule name','Work Schedule');
uis.lang_en('ui-vhr107:staff number','PersNo');
uis.lang_en('ui-vhr107:transfer base','Transfer Proof');
uis.lang_en('ui-vhr107:transfer begin','Transfer Start Date');
uis.lang_en('ui-vhr107:transfer end','Transfer End Date');
uis.lang_en('ui-vhr107:transfer kind name','Transfer Type');
uis.lang_en('ui-vhr107:transfer reason','Transfer Reason');
uis.lang_en('ui-vhr107:wage amount','Salary');
uis.lang_en('ui-vhr107:working day','Working Day Duration');
uis.lang_en('ui-vhr107:working week','Working Week Duration');
uis.lang_en('ui-vhr107:workplace equipment','Workspace Equipment');
commit;
end;
/
