prompt MOBILE TRANSLATE
begin
uis.lang_ru('#mob:vhr:attendance_chart:free_day','Выходной');
uis.lang_ru('#mob:vhr:attendance_chart:intime','Вовремя');
uis.lang_ru('#mob:vhr:attendance_chart:late','Опоздали');
uis.lang_ru('#mob:vhr:attendance_chart:no_schedule','Нет графика');
uis.lang_ru('#mob:vhr:attendance_chart:not_begin','Не рабочее время');
uis.lang_ru('#mob:vhr:attendance_chart:not_come','Не пришли');
uis.lang_ru('#mob:vhr:attendance_chart:take_leave','Запросили отсутствие');
uis.lang_ru('#mob:vhr:camera:back','Назад');
uis.lang_ru('#mob:vhr:camera:face_recognition','Идентифицировать');
uis.lang_ru('#mob:vhr:camera:ok','OK');
uis.lang_ru('#mob:vhr:camera:please_wait','Пожалуйста, подождите');
uis.lang_ru('#mob:vhr:camera:repeat','Повторить');
uis.lang_ru('#mob:vhr:camera:send_note','Отправка отметки');
uis.lang_ru('#mob:vhr:camera:skip','Пропустить');
uis.lang_ru('#mob:vhr:camera:warning','Внимание!');
uis.lang_ru('#mob:vhr:change:add','Добавить');
uis.lang_ru('#mob:vhr:change:cancel','Отмена');
uis.lang_ru('#mob:vhr:change:comment','Комментарий');
uis.lang_ru('#mob:vhr:change:comment_text','Текст комментария');
uis.lang_ru('#mob:vhr:change:send','Отправить');
uis.lang_ru('#mob:vhr:change:toolbar_title','Смена графика');
uis.lang_ru('#mob:vhr:change_item:date','дата');
uis.lang_ru('#mob:vhr:change_item:free_schedule','Свободный график');
uis.lang_ru('#mob:vhr:change_item:lunch','Обед');
uis.lang_ru('#mob:vhr:change_item:lunch_end','конец обеда');
uis.lang_ru('#mob:vhr:change_item:lunch_start','начало обеда');
uis.lang_ru('#mob:vhr:change_item:not_specified','Не указано');
uis.lang_ru('#mob:vhr:change_item:remove','Удалить');
uis.lang_ru('#mob:vhr:change_item:schedule','График');
uis.lang_ru('#mob:vhr:change_item:specify','Указать');
uis.lang_ru('#mob:vhr:change_item:time_end','время конца');
uis.lang_ru('#mob:vhr:change_item:time_start','время начала');
uis.lang_ru('#mob:vhr:change_item:working_hours_number','Количество рабочих часов');
uis.lang_ru('#mob:vhr:dashboard_mark:card_title','Отметиться');
uis.lang_ru('#mob:vhr:dashboard_mark:check-in','Отметка');
uis.lang_ru('#mob:vhr:dashboard_mark:input','Приход');
uis.lang_ru('#mob:vhr:dashboard_mark:output','Уход');
uis.lang_ru('#mob:vhr:face_registered_screen:face_registered','Лицо зарегистрировано');
uis.lang_ru('#mob:vhr:face_registered_screen:finish','Завершить');
uis.lang_ru('#mob:vhr:head:my_day','Мой день');
uis.lang_ru('#mob:vhr:head:settings','Ещё');
uis.lang_ru('#mob:vhr:head:subordinate','Подчиненные');
uis.lang_ru('#mob:vhr:head:toolbar_title','Главная');
uis.lang_ru('#mob:vhr:kpi_category:calculation_type','Вид расчета: ');
uis.lang_ru('#mob:vhr:kpi_category:plan_type_e','Дополнительные показатели');
uis.lang_ru('#mob:vhr:kpi_category:plan_type_m','Основные показатели');
uis.lang_ru('#mob:vhr:kpi_category:status','Статус');
uis.lang_ru('#mob:vhr:kpi_category:weight','Вес: ');
uis.lang_ru('#mob:vhr:kpi_part_add_edit:accept','Принять');
uis.lang_ru('#mob:vhr:kpi_part_add_edit:add','Добавление оценки');
uis.lang_ru('#mob:vhr:kpi_part_add_edit:comment','Примечание');
uis.lang_ru('#mob:vhr:kpi_part_add_edit:error_empty_field','Обязательное поле');
uis.lang_ru('#mob:vhr:kpi_part_add_edit:fact','Факт');
uis.lang_ru('#mob:vhr:kpi_plan_detailed:add','Добавить');
uis.lang_ru('#mob:vhr:kpi_plan_detailed:added','Добавил(а)');
uis.lang_ru('#mob:vhr:kpi_plan_detailed:are_you_sure_delete','Вы действительно хотите удалить оценку?');
uis.lang_ru('#mob:vhr:kpi_plan_detailed:at_time','в');
uis.lang_ru('#mob:vhr:kpi_plan_detailed:calculation_type','Вид расчета: ');
uis.lang_ru('#mob:vhr:kpi_plan_detailed:close','Закрыть');
uis.lang_ru('#mob:vhr:kpi_plan_detailed:delete','Удалить');
uis.lang_ru('#mob:vhr:kpi_plan_detailed:edit','Изменить');
uis.lang_ru('#mob:vhr:kpi_plan_detailed:no','Нет');
uis.lang_ru('#mob:vhr:kpi_plan_detailed:weight','Вес: ');
uis.lang_ru('#mob:vhr:kpi_plan_detailed:yes','Да');
uis.lang_ru('#mob:vhr:kpi_plan_detailed:you','Вы');
uis.lang_ru('#mob:vhr:mark_barcode:close','Закрыть');
uis.lang_ru('#mob:vhr:mark_barcode:qr_message','Для того, чтобы отметиться поднесите QR-код к планшету с Timepad.');
uis.lang_ru('#mob:vhr:mark_barcode:title','Отметка по QR');
uis.lang_ru('#mob:vhr:mark_face_bean:check_emotion_close_left_eye','Закройте левый глаз');
uis.lang_ru('#mob:vhr:mark_face_bean:check_emotion_close_right_eye','Закройте правый глаз');
uis.lang_ru('#mob:vhr:mark_face_bean:check_emotion_smile','Улыбнитесь');
uis.lang_ru('#mob:vhr:mark_face_bean:face_not_recognized','Лицо не идентифицировано');
uis.lang_ru('#mob:vhr:mark_face_bean:face_recognized','Лицо идентифицировано');
uis.lang_ru('#mob:vhr:mark_face_bean:unable_generate_emotion','Невозможно сгенерировать эмоцию');
uis.lang_ru('#mob:vhr:mark_location:location_found','Координаты найдены,
погрешность %1s м');
uis.lang_ru('#mob:vhr:mark_location:location_not_match','Локация не совпадает');
uis.lang_ru('#mob:vhr:mark_location:please_wait','Пожалуйста, подождите');
uis.lang_ru('#mob:vhr:mark_location:skip','Пропустить');
uis.lang_ru('#mob:vhr:mark_location:touch_id_description','Используйте Touch-ID для идентификации пользователя в текущий аккаунт
Приложите палец к датчику');
uis.lang_ru('#mob:vhr:mark_note:cancel','Отмена');
uis.lang_ru('#mob:vhr:mark_note:face','Фото');
uis.lang_ru('#mob:vhr:mark_note:face_found','Лицо идентифицировано');
uis.lang_ru('#mob:vhr:mark_note:field_required','Комментария об отметке обязательное для заполнения');
uis.lang_ru('#mob:vhr:mark_note:location','Местоположение');
uis.lang_ru('#mob:vhr:mark_note:location_accuracy','Погрешность: %1s м');
uis.lang_ru('#mob:vhr:mark_note:location_not_found','Локация не совпадает');
uis.lang_ru('#mob:vhr:mark_note:not_valid','Лицо не идентифицировано');
uis.lang_ru('#mob:vhr:mark_note:note_hint_message','Комментарий об отметке...');
uis.lang_ru('#mob:vhr:mark_note:send','Отправить');
uis.lang_ru('#mob:vhr:mark_note:toolbar_title','Об отметке');
uis.lang_ru('#mob:vhr:mark_note:track_note','Примечание');
uis.lang_ru('#mob:vhr:my_day:no_schedule','Нет графика');
uis.lang_ru('#mob:vhr:my_day:relax','Займись собой и отдохни');
uis.lang_ru('#mob:vhr:my_day:timesheet','Календарь');
uis.lang_ru('#mob:vhr:my_day:toolbar_title','Главная');
uis.lang_ru('#mob:vhr:my_day:weekend','Выходной');
uis.lang_ru('#mob:vhr:my_day:work_day','Рабочий день%1s: %2s');
uis.lang_ru('#mob:vhr:my_kpi:calculation_type','Вид расчета');
uis.lang_ru('#mob:vhr:my_kpi:calendar','Календарь');
uis.lang_ru('#mob:vhr:my_kpi:toolbar_title','Мой KPI');
uis.lang_ru('#mob:vhr:my_kpi:weight','Вес');
uis.lang_ru('#mob:vhr:my_requests:back','Назад');
uis.lang_ru('#mob:vhr:my_requests:my_requests','Запросы на отсутствие');
uis.lang_ru('#mob:vhr:notify_mark_setting:after','После');
uis.lang_ru('#mob:vhr:notify_mark_setting:before','За');
uis.lang_ru('#mob:vhr:notify_mark_setting:begin_time_notification','Начало рабочего дня');
uis.lang_ru('#mob:vhr:notify_mark_setting:enable_text','Уведомления о необходимости отметки Начало рабочего дня Конец рабочего дня');
uis.lang_ru('#mob:vhr:notify_mark_setting:end_time_notification','Конец рабочего дня');
uis.lang_ru('#mob:vhr:notify_mark_setting:minute','%1s мин');
uis.lang_ru('#mob:vhr:notify_mark_setting:toolbar_title','Уведомления о необходимости отметки');
uis.lang_ru('#mob:vhr:profile:account_title','Аккаунт');
uis.lang_ru('#mob:vhr:profile:change_account','Сменить профиль');
uis.lang_ru('#mob:vhr:profile:change_filial','Сменить филиал');
uis.lang_ru('#mob:vhr:profile:change_password','Изменить PIN-код');
uis.lang_ru('#mob:vhr:profile:current_filial','Текущий филиал');
uis.lang_ru('#mob:vhr:profile:enter_with_touch_id','Вход с Touch-ID');
uis.lang_ru('#mob:vhr:profile:my_kpi','Мой KPI');
uis.lang_ru('#mob:vhr:profile:notify_mark','Уведомления о начале и конце рабочего дня');
uis.lang_ru('#mob:vhr:profile:remove_password','Удалить PIN-код');
uis.lang_ru('#mob:vhr:profile:security_title','Безопасность');
uis.lang_ru('#mob:vhr:profile:set_password','Установить PIN-код');
uis.lang_ru('#mob:vhr:profile:settings','Настройки');
uis.lang_ru('#mob:vhr:profile:show_direct_subordinates','Показывать только прямых подчиненных');
uis.lang_ru('#mob:vhr:profile:subordinates_kpi','KPI подчиненных');
uis.lang_ru('#mob:vhr:profile:toolbar_title','Ещё');
uis.lang_ru('#mob:vhr:profile_screen:accounts','Аккаунты');
uis.lang_ru('#mob:vhr:profile_screen:accounts_and_ids','Счета и идентификаторы');
uis.lang_ru('#mob:vhr:profile_screen:back','Назад');
uis.lang_ru('#mob:vhr:profile_screen:camera','Камера');
uis.lang_ru('#mob:vhr:profile_screen:city','город');
uis.lang_ru('#mob:vhr:profile_screen:contacts','Контакты');
uis.lang_ru('#mob:vhr:profile_screen:copied','Скопировано в буфер обмена');
uis.lang_ru('#mob:vhr:profile_screen:date_of_birth','дата рождения');
uis.lang_ru('#mob:vhr:profile_screen:email','e-mail');
uis.lang_ru('#mob:vhr:profile_screen:exit_account_message','Вы действительно хотите выйти из аккаунта?');
uis.lang_ru('#mob:vhr:profile_screen:exit_account_no','Нет');
uis.lang_ru('#mob:vhr:profile_screen:exit_account_yes','Да');
uis.lang_ru('#mob:vhr:profile_screen:face','лицо');
uis.lang_ru('#mob:vhr:profile_screen:face_not_registered','Незарегистрировано');
uis.lang_ru('#mob:vhr:profile_screen:face_registered','Зарегистрировано');
uis.lang_ru('#mob:vhr:profile_screen:female','Женский');
uis.lang_ru('#mob:vhr:profile_screen:gallery','Галерея');
uis.lang_ru('#mob:vhr:profile_screen:gender','пол');
uis.lang_ru('#mob:vhr:profile_screen:image_source_question','Откуда возьмем фото?');
uis.lang_ru('#mob:vhr:profile_screen:inn','ИНН');
uis.lang_ru('#mob:vhr:profile_screen:inps','ИНПС');
uis.lang_ru('#mob:vhr:profile_screen:leave','Выйти');
uis.lang_ru('#mob:vhr:profile_screen:male','Мужской');
uis.lang_ru('#mob:vhr:profile_screen:manager','руководитель');
uis.lang_ru('#mob:vhr:profile_screen:no_image_selected','Фотография не была выбрана');
uis.lang_ru('#mob:vhr:profile_screen:no_info','Не указано');
uis.lang_ru('#mob:vhr:profile_screen:personnel_number','табельный номер');
uis.lang_ru('#mob:vhr:profile_screen:phone_number','номер телефона');
uis.lang_ru('#mob:vhr:profile_screen:pinfl','ПИНФЛ');
uis.lang_ru('#mob:vhr:profile_screen:profile','Профиль');
uis.lang_ru('#mob:vhr:profile_screen:region','Регион');
uis.lang_ru('#mob:vhr:profile_screen:registration_address','адрес прописки');
uis.lang_ru('#mob:vhr:profile_screen:residence_address','адрес проживания');
uis.lang_ru('#mob:vhr:profile_screen:warning','Предупреждение');
uis.lang_ru('#mob:vhr:request_component:change_schedule','Изм. график');
uis.lang_ru('#mob:vhr:request_component:for_today','На сегодня');
uis.lang_ru('#mob:vhr:request_component:leave','Отсутствие');
uis.lang_ru('#mob:vhr:request_component:requests','Запросы на отсутствие');
uis.lang_ru('#mob:vhr:request_component:show_all','Все');
uis.lang_ru('#mob:vhr:request_component:swap','Обмен дней');
uis.lang_ru('#mob:vhr:request_component:this_month','В этом месяце');
uis.lang_ru('#mob:vhr:request_details:approve','Принять');
uis.lang_ru('#mob:vhr:request_details:approved','Подтвержден');
uis.lang_ru('#mob:vhr:request_details:back','Назад');
uis.lang_ru('#mob:vhr:request_details:change','Смена графика');
uis.lang_ru('#mob:vhr:request_details:comment','Комментарий');
uis.lang_ru('#mob:vhr:request_details:comment_text','Текст комментария');
uis.lang_ru('#mob:vhr:request_details:date','дата');
uis.lang_ru('#mob:vhr:request_details:dates','даты');
uis.lang_ru('#mob:vhr:request_details:delete','Удалить');
uis.lang_ru('#mob:vhr:request_details:denied','Отклонен');
uis.lang_ru('#mob:vhr:request_details:deny','Отклонить');
uis.lang_ru('#mob:vhr:request_details:edit','Изменить');
uis.lang_ru('#mob:vhr:request_details:leave','Запрос на отсутствие');
uis.lang_ru('#mob:vhr:request_details:leave_reason','причина отсутствия');
uis.lang_ru('#mob:vhr:request_details:leave_type','тип отсутствия');
uis.lang_ru('#mob:vhr:request_details:manager_approval','одобрение руководителя');
uis.lang_ru('#mob:vhr:request_details:manager_note','Комментария руководителя');
uis.lang_ru('#mob:vhr:request_details:note','Примечание');
uis.lang_ru('#mob:vhr:request_details:replaced_day','Заменяемый день');
uis.lang_ru('#mob:vhr:request_details:replacing_day','Обмен дней');
uis.lang_ru('#mob:vhr:request_details:request_state','состояние запроса');
uis.lang_ru('#mob:vhr:request_details:reset','Сброс');
uis.lang_ru('#mob:vhr:request_details:schedule_change','перенос графика');
uis.lang_ru('#mob:vhr:request_details:subordinate_name','Сотрудник');
uis.lang_ru('#mob:vhr:request_details:swap','обмен дней');
uis.lang_ru('#mob:vhr:request_details:time','время');
uis.lang_ru('#mob:vhr:request_details:waiting','Ожидание');
uis.lang_ru('#mob:vhr:request_list:april','Апрель');
uis.lang_ru('#mob:vhr:request_list:august','Август');
uis.lang_ru('#mob:vhr:request_list:december','Декабрь');
uis.lang_ru('#mob:vhr:request_list:february','Февраль');
uis.lang_ru('#mob:vhr:request_list:january','Январь');
uis.lang_ru('#mob:vhr:request_list:july','Июль');
uis.lang_ru('#mob:vhr:request_list:june','Июнь');
uis.lang_ru('#mob:vhr:request_list:march','Март');
uis.lang_ru('#mob:vhr:request_list:may','Май');
uis.lang_ru('#mob:vhr:request_list:no_requests','Запросов нет.');
uis.lang_ru('#mob:vhr:request_list:november','Ноябрь');
uis.lang_ru('#mob:vhr:request_list:october','Октябрь');
uis.lang_ru('#mob:vhr:request_list:september','Сентябрь');
uis.lang_ru('#mob:vhr:requests:approved','Подтвержден');
uis.lang_ru('#mob:vhr:requests:back','Назад');
uis.lang_ru('#mob:vhr:requests:cancel','Отмена');
uis.lang_ru('#mob:vhr:requests:change','Смена графика');
uis.lang_ru('#mob:vhr:requests:comment','Комментарий');
uis.lang_ru('#mob:vhr:requests:comment_text','Текст комментария');
uis.lang_ru('#mob:vhr:requests:date','дата');
uis.lang_ru('#mob:vhr:requests:dates','даты');
uis.lang_ru('#mob:vhr:requests:day_end','конец дня');
uis.lang_ru('#mob:vhr:requests:day_start','начало дня');
uis.lang_ru('#mob:vhr:requests:delete','Удалить');
uis.lang_ru('#mob:vhr:requests:denied','Отклонен');
uis.lang_ru('#mob:vhr:requests:edit','Изменить');
uis.lang_ru('#mob:vhr:requests:free_schedule','Свободный график');
uis.lang_ru('#mob:vhr:requests:leave','Запрос на отсутствие');
uis.lang_ru('#mob:vhr:requests:leave_reason','Причина отсутствия');
uis.lang_ru('#mob:vhr:requests:leave_type','Тип отсутствия');
uis.lang_ru('#mob:vhr:requests:leave_type_day','День');
uis.lang_ru('#mob:vhr:requests:leave_type_days','Несколько дней');
uis.lang_ru('#mob:vhr:requests:leave_type_hourly','Почасовой');
uis.lang_ru('#mob:vhr:requests:lunch','Обед');
uis.lang_ru('#mob:vhr:requests:lunch_end','конец обеда');
uis.lang_ru('#mob:vhr:requests:lunch_start','начало обеда');
uis.lang_ru('#mob:vhr:requests:manager_approval','одобрение руководителя');
uis.lang_ru('#mob:vhr:requests:no_choice','Не выбрано/Not chosen');
uis.lang_ru('#mob:vhr:requests:not_specified','Не указано');
uis.lang_ru('#mob:vhr:requests:replaced_day','Заменяемый день');
uis.lang_ru('#mob:vhr:requests:replacing_day','Заменяющий день');
uis.lang_ru('#mob:vhr:requests:request_state','состояние запроса');
uis.lang_ru('#mob:vhr:requests:schedule_change','перенос графика');
uis.lang_ru('#mob:vhr:requests:send','Отправить');
uis.lang_ru('#mob:vhr:requests:specify','Указать');
uis.lang_ru('#mob:vhr:requests:swap','Обмен дней');
uis.lang_ru('#mob:vhr:requests:time','время');
uis.lang_ru('#mob:vhr:requests:time_end','время конца');
uis.lang_ru('#mob:vhr:requests:time_start','время начала');
uis.lang_ru('#mob:vhr:requests:waiting','Ожидание');
uis.lang_ru('#mob:vhr:requests:working_hours_number','Количество рабочих часов');
uis.lang_ru('#mob:vhr:setting:account_btn','Аккаунты');
uis.lang_ru('#mob:vhr:setting:back','Назад');
uis.lang_ru('#mob:vhr:setting:background','Фон приложения');
uis.lang_ru('#mob:vhr:setting:components','Компоненты');
uis.lang_ru('#mob:vhr:setting:dark','Темная');
uis.lang_ru('#mob:vhr:setting:default_system','Как в системе');
uis.lang_ru('#mob:vhr:setting:for_developer','Для разработчиков');
uis.lang_ru('#mob:vhr:setting:interface','Интерфейс');
uis.lang_ru('#mob:vhr:setting:lang','язык интерфейса');
uis.lang_ru('#mob:vhr:setting:light','Светлая');
uis.lang_ru('#mob:vhr:setting:load_vector','Загрузка лиц %1s/%2s');
uis.lang_ru('#mob:vhr:setting:load_vector_error','Загрузка лиц %1s/%2s, %3s');
uis.lang_ru('#mob:vhr:setting:main_page','Стартовый экран');
uis.lang_ru('#mob:vhr:setting:please_wait','Пожалуйста, подождите');
uis.lang_ru('#mob:vhr:setting:reload_btn','Повторить');
uis.lang_ru('#mob:vhr:setting:setting_downloads','Скачиваются настройки');
uis.lang_ru('#mob:vhr:setting:theme','тема');
uis.lang_ru('#mob:vhr:setting:toolbar_title','Настройки');
uis.lang_ru('#mob:vhr:setting_options:back','Назад');
uis.lang_ru('#mob:vhr:setting_options:dark','Темная');
uis.lang_ru('#mob:vhr:setting_options:default_system','Как в системе');
uis.lang_ru('#mob:vhr:setting_options:light','Светлая');
uis.lang_ru('#mob:vhr:setting_options:theme','Тема');
uis.lang_ru('#mob:vhr:setting_options:toolbar_title','Опции');
uis.lang_ru('#mob:vhr:subordinate:show_all','Все');
uis.lang_ru('#mob:vhr:subordinate:sub_show_all','Все');
uis.lang_ru('#mob:vhr:subordinate:subordinate_requests','Запросы на отсутствие');
uis.lang_ru('#mob:vhr:subordinate:subordinates','Подчиненные');
uis.lang_ru('#mob:vhr:subordinate:toolbar_title','Подчиненные');
uis.lang_ru('#mob:vhr:subordinate_dialog:btn_close','Закрыть');
uis.lang_ru('#mob:vhr:subordinate_dialog:list_is_empty','Список сотрудников пуст');
uis.lang_ru('#mob:vhr:subordinate_dialog:search_hint','Поиск');
uis.lang_ru('#mob:vhr:subordinate_dialog:toolbar_title','Сотрудники');
uis.lang_ru('#mob:vhr:subordinate_kpi:calendar','Календарь');
uis.lang_ru('#mob:vhr:subordinate_kpi:search','Поиск');
uis.lang_ru('#mob:vhr:subordinate_kpi:toolbar_title','KPI подчиненных');
uis.lang_ru('#mob:vhr:subordinate_kpi_detailed:calculation_type','Вид расчета');
uis.lang_ru('#mob:vhr:subordinate_kpi_detailed:calendar','Календарь');
uis.lang_ru('#mob:vhr:subordinate_kpi_detailed:toolbar_title','KPI');
uis.lang_ru('#mob:vhr:subordinate_kpi_detailed:weight','Вес');
uis.lang_ru('#mob:vhr:swap:add','Добавить');
uis.lang_ru('#mob:vhr:swap:cancel','Отмена');
uis.lang_ru('#mob:vhr:swap:comment','Комментарий');
uis.lang_ru('#mob:vhr:swap:comment_text','Текст комментария');
uis.lang_ru('#mob:vhr:swap:send','Отправить');
uis.lang_ru('#mob:vhr:swap:toolbar_title','Обмен дней');
uis.lang_ru('#mob:vhr:swap_item:not_specified','Не указано');
uis.lang_ru('#mob:vhr:swap_item:remove','Удалить');
uis.lang_ru('#mob:vhr:swap_item:replaced_day','Заменяемый день');
uis.lang_ru('#mob:vhr:swap_item:replacing_day','Заменяющий день');
uis.lang_ru('#mob:vhr:swap_item:specify','Указать');
uis.lang_ru('#mob:vhr:timesheet:april','Апрель');
uis.lang_ru('#mob:vhr:timesheet:at_work','На работе');
uis.lang_ru('#mob:vhr:timesheet:august','Август');
uis.lang_ru('#mob:vhr:timesheet:back_pressed','Назад');
uis.lang_ru('#mob:vhr:timesheet:december','Декабрь');
uis.lang_ru('#mob:vhr:timesheet:employee_change','Изменение раб.дня');
uis.lang_ru('#mob:vhr:timesheet:february','Февраль');
uis.lang_ru('#mob:vhr:timesheet:has_leave_full_day','Отсутствие на весь день.');
uis.lang_ru('#mob:vhr:timesheet:january','Январь');
uis.lang_ru('#mob:vhr:timesheet:july','Июль');
uis.lang_ru('#mob:vhr:timesheet:june','Июнь');
uis.lang_ru('#mob:vhr:timesheet:march','Март');
uis.lang_ru('#mob:vhr:timesheet:may','Май');
uis.lang_ru('#mob:vhr:timesheet:november','Ноябрь');
uis.lang_ru('#mob:vhr:timesheet:october','Октябрь');
uis.lang_ru('#mob:vhr:timesheet:schedule','График');
uis.lang_ru('#mob:vhr:timesheet:september','Сентябрь');
uis.lang_ru('#mob:vhr:timesheet:toolbar_title','Календарь');
uis.lang_ru('#mob:vhr:timesheet:track_title','Трекинг');
uis.lang_ru('#mob:vhr:timesheet:weekend','Выходной');
uis.lang_ru('#mob:vhr:timesheet:work_pass','Пропуск');
uis.lang_ru('#mob:vhr:timesheet_employee_info:back','Назад');
uis.lang_ru('#mob:vhr:timesheet_employee_info:calendar','Календарь');
uis.lang_ru('#mob:vhr:timesheet_employee_info:employee_statistic','Профиль сотрудника');
uis.lang_ru('#mob:vhr:timesheet_employee_info:schedule_requests','Запросы');
uis.lang_ru('#mob:vhr:timesheet_employee_info:show_all','Все');
uis.lang_ru('#mob:vhr:timesheet_employee_info:track_title','Трекинг');
uis.lang_ru('#mob:vhr:timesheet_inout:input','Приход');
uis.lang_ru('#mob:vhr:timesheet_inout:output','Уход');
uis.lang_ru('#mob:vhr:timesheet_schedule:change_change','Изменение графика');
uis.lang_ru('#mob:vhr:timesheet_schedule:change_swap','Поменять дни');
uis.lang_ru('#mob:vhr:timesheet_schedule:dinner','Перерыв');
uis.lang_ru('#mob:vhr:timesheet_schedule:leave','Отсутствие');
uis.lang_ru('#mob:vhr:timesheet_schedule:leave_full_day','Отсутствие на весь день.');
uis.lang_ru('#mob:vhr:timesheet_schedule:schedule','График');
uis.lang_ru('#mob:vhr:timesheet_schedule:work_day','Рабочий день');
uis.lang_ru('#mob:vhr:timesheet_statistic:day_result_title','Статистика дня');
uis.lang_ru('#mob:vhr:timesheet_statistic:freetime','Свободное');
uis.lang_ru('#mob:vhr:timesheet_statistic:intime','Вовремя');
uis.lang_ru('#mob:vhr:timesheet_statistic:not_worked','Неотработанное');
uis.lang_ru('#mob:vhr:timesheet_statistic:overtime','Сверхурочное');
uis.lang_ru('#mob:vhr:timesheet_statistic:plan_time','По плану');
uis.lang_ru('#mob:vhr:timesheet_statistic:toolbar_title','Итоги дня');
uis.lang_ru('#mob:vhr:timesheet_tracking:more_tracks','Все');
uis.lang_ru('#mob:vhr:today_attendance:back','Назад');
uis.lang_ru('#mob:vhr:today_attendance:calendar','Календарь');
uis.lang_ru('#mob:vhr:today_attendance:close','Закрыть');
uis.lang_ru('#mob:vhr:today_attendance:filter','Фильтр');
uis.lang_ru('#mob:vhr:today_attendance:more_info','Подробно');
uis.lang_ru('#mob:vhr:today_attendance:sort','Сорт.');
uis.lang_ru('#mob:vhr:today_attendance:sort_full','Сорт.');
uis.lang_ru('#mob:vhr:today_attendance:visits','Посещаемость');
uis.lang_ru('#mob:vhr:today_attendance_filter_dialog:all','Все');
uis.lang_ru('#mob:vhr:today_attendance_filter_dialog:close','Закрыть');
uis.lang_ru('#mob:vhr:today_attendance_filter_dialog:filter','Фильтр');
uis.lang_ru('#mob:vhr:today_attendance_filter_dialog:free_day','Выходной');
uis.lang_ru('#mob:vhr:today_attendance_filter_dialog:intime','Вовремя');
uis.lang_ru('#mob:vhr:today_attendance_filter_dialog:late','Опоздали');
uis.lang_ru('#mob:vhr:today_attendance_filter_dialog:no_schedule','Нет графика');
uis.lang_ru('#mob:vhr:today_attendance_filter_dialog:not_begin','Не рабочее время');
uis.lang_ru('#mob:vhr:today_attendance_filter_dialog:not_come','Не пришли');
uis.lang_ru('#mob:vhr:today_attendance_filter_dialog:select','Принять');
uis.lang_ru('#mob:vhr:today_attendance_filter_dialog:take_leave','Запросили отсутствие');
uis.lang_ru('#mob:vhr:today_timesheet:breaks','Перерыв');
uis.lang_ru('#mob:vhr:today_timesheet:input','Приход');
uis.lang_ru('#mob:vhr:today_timesheet:output','Уход');
uis.lang_ru('#mob:vhr:today_timesheet:weekend','Выходной');
uis.lang_ru('#mob:vhr:today_timesheet:work_day','Раб. день');
uis.lang_ru('#mob:vhr:track_filter:cancel','Отмена');
uis.lang_ru('#mob:vhr:track_filter:current_month','Этот месяц');
uis.lang_ru('#mob:vhr:track_filter:filter','Отфильтровать');
uis.lang_ru('#mob:vhr:track_filter:filter_tracks_title','Отфильтровать отметки');
uis.lang_ru('#mob:vhr:track_filter:last30day','Последние 30 дней');
uis.lang_ru('#mob:vhr:track_filter:last7day','Последние 7 дней');
uis.lang_ru('#mob:vhr:track_filter:last_month','Последний месяц');
uis.lang_ru('#mob:vhr:track_filter:today','Сегодня');
uis.lang_ru('#mob:vhr:track_filter:yesterday','Вчера');
uis.lang_ru('#mob:vhr:track_info:back','Назад');
uis.lang_ru('#mob:vhr:track_info:location','Координаты');
uis.lang_ru('#mob:vhr:track_info:location_accuracy','Погрешность: %1s м');
uis.lang_ru('#mob:vhr:track_info:not_valid','Недействительный');
uis.lang_ru('#mob:vhr:track_info:toolbar_title','Отметка (%1s)');
uis.lang_ru('#mob:vhr:track_info:track_location','Локация');
uis.lang_ru('#mob:vhr:track_info:track_note','Примечание');
uis.lang_ru('#mob:vhr:track_info:track_photo','Фото');
uis.lang_ru('#mob:vhr:track_info:track_time','Время');
uis.lang_ru('#mob:vhr:track_info:tracking_type','Тип трекинга');
uis.lang_ru('#mob:vhr:track_widget:not_valid','Недействительный');
uis.lang_ru('#mob:vhr:tracking:all_tracks_title','Все отметки');
uis.lang_ru('#mob:vhr:tracking:check-in','Отметка');
uis.lang_ru('#mob:vhr:tracking:employee_close_btn','Закрыть');
uis.lang_ru('#mob:vhr:tracking:employee_list_is_empty','Список сотрудников пуст');
uis.lang_ru('#mob:vhr:tracking:employee_list_title','Список подчиненных');
uis.lang_ru('#mob:vhr:tracking:employee_select_btn','Выбрать');
uis.lang_ru('#mob:vhr:tracking:employee_title','Сотрудники');
uis.lang_ru('#mob:vhr:tracking:employee_tracks_title','Отметки сотрудника');
uis.lang_ru('#mob:vhr:tracking:filter_title','Фильтр');
uis.lang_ru('#mob:vhr:tracking:input','Приход');
uis.lang_ru('#mob:vhr:tracking:more_tracks','Все');
uis.lang_ru('#mob:vhr:tracking:output','Уход');
uis.lang_ru('#mob:vhr:tracking:search_hint','Поиск');
uis.lang_ru('#mob:vhr:tracking:track_at_date','%1s в %2s');
uis.lang_ru('#mob:vhr:tracking:track_input','Приход');
uis.lang_ru('#mob:vhr:tracking:track_is_empty','Список трекингов пуст');
uis.lang_ru('#mob:vhr:tracking:track_list_is_empty','Список трекингов пуст');
uis.lang_ru('#mob:vhr:tracking:track_location','Локация');
uis.lang_ru('#mob:vhr:tracking:track_mark','Отметка');
uis.lang_ru('#mob:vhr:tracking:track_not_valid','Недействительный');
uis.lang_ru('#mob:vhr:tracking:track_note','Примечание');
uis.lang_ru('#mob:vhr:tracking:track_output','Уход');
uis.lang_ru('#mob:vhr:tracking:track_time','Время');
uis.lang_ru('#mob:vhr:tracking:track_title','Трекинг');
uis.lang_ru('#mob:vhr:tracking:track_today','Сегодня в %1s');
uis.lang_ru('#mob:vhr:tracking:tracking_type','Тип трекинга');
uis.lang_ru('#mob:vhr:tracking_list:all_tracks_title','Все отметки');
uis.lang_ru('#mob:vhr:tracking_list:back','Назад');
uis.lang_ru('#mob:vhr:tracking_list:employee','Подчинённые');
uis.lang_ru('#mob:vhr:tracking_list:employee_tracks_title','Отметки сотрудника');
uis.lang_ru('#mob:vhr:tracking_list:filter','Фильтр');
uis.lang_ru('#mob:vhr:tracking_list:track_list_is_empty','Список трекингов пуст');
commit;
end;
/
