set define off
prompt TABLE RECORD TRANSLATE
begin
uis.table_record_translate('HPD_JOURNAL_TYPES','VHR:HPD:1','NAME','ru','Прием на работу');
uis.table_record_translate('HPD_JOURNAL_TYPES','VHR:HPD:10','NAME','ru','Командировка');
uis.table_record_translate('HPD_JOURNAL_TYPES','VHR:HPD:11','NAME','ru','Отпуск');
uis.table_record_translate('HPD_JOURNAL_TYPES','VHR:HPD:12','NAME','ru','Изменение разряда');
uis.table_record_translate('HPD_JOURNAL_TYPES','VHR:HPD:13','NAME','ru','Изменение количества отпускных дней');
uis.table_record_translate('HPD_JOURNAL_TYPES','VHR:HPD:14','NAME','ru','Сверхурочная работа');
uis.table_record_translate('HPD_JOURNAL_TYPES','VHR:HPD:15','NAME','ru','Изменение оплаты труда списком');
uis.table_record_translate('HPD_JOURNAL_TYPES','VHR:HPD:2','NAME','ru','Прием на работу списком');
uis.table_record_translate('HPD_JOURNAL_TYPES','VHR:HPD:3','NAME','ru','Кадровый перевод');
uis.table_record_translate('HPD_JOURNAL_TYPES','VHR:HPD:4','NAME','ru','Кадровый перевод списком');
uis.table_record_translate('HPD_JOURNAL_TYPES','VHR:HPD:5','NAME','ru','Увольнение');
uis.table_record_translate('HPD_JOURNAL_TYPES','VHR:HPD:6','NAME','ru','Увольнение списком');
uis.table_record_translate('HPD_JOURNAL_TYPES','VHR:HPD:7','NAME','ru','Изменение оплаты труда');
uis.table_record_translate('HPD_JOURNAL_TYPES','VHR:HPD:8','NAME','ru','Изменение графика работы списком');
uis.table_record_translate('HPD_JOURNAL_TYPES','VHR:HPD:9','NAME','ru','Больничный лист');
uis.table_record_translate('HPR_BOOK_TYPES','VHR:1','NAME','ru','Начисление зарплаты и взносов');
uis.table_record_translate('HPR_BOOK_TYPES','VHR:2','NAME','ru','Начисление больничных');
uis.table_record_translate('HPR_BOOK_TYPES','VHR:3','NAME','ru','Начисление командировочных');
uis.table_record_translate('HPR_BOOK_TYPES','VHR:4','NAME','ru','Начисление отпускных');
uis.table_record_translate('HPR_BOOK_TYPES','VHR:5','NAME','ru','Начисление всех видов');
uis.table_record_translate('HPR_OPER_GROUPS','VHR:1','NAME','ru','Повременная оплата труда и надбавки');
uis.table_record_translate('HPR_OPER_GROUPS','VHR:2','NAME','ru','Бонус за эффективность');
uis.table_record_translate('HPR_OPER_GROUPS','VHR:3','NAME','ru','Больничные');
uis.table_record_translate('HPR_OPER_GROUPS','VHR:4','NAME','ru','Командировочные');
uis.table_record_translate('HPR_OPER_GROUPS','VHR:5','NAME','ru','Отпускные');
uis.table_record_translate('HPR_OPER_GROUPS','VHR:6','NAME','ru','Сверхурочная оплата труда');
uis.table_record_translate('HPR_OPER_GROUPS','VHR:7','NAME','ru','Штрафы за нарушение дисциплины');
uis.table_record_translate('HREF_DOCUMENT_TYPES','VHR:1','NAME','ru','Паспорт (по умолчанию)');
uis.table_record_translate('HREF_FTES','VHR:1','NAME','ru','Полная ставка');
uis.table_record_translate('HREF_FTES','VHR:2','NAME','ru','Полставки');
uis.table_record_translate('HREF_FTES','VHR:3','NAME','ru','Четверть ставки');
uis.table_record_translate('HREF_INDICATORS','VHR:1','IDENTIFIER','ru','Оклад');
uis.table_record_translate('HREF_INDICATORS','VHR:1','NAME','ru','Оклад');
uis.table_record_translate('HREF_INDICATORS','VHR:1','SHORT_NAME','ru','Оклад');
uis.table_record_translate('HREF_INDICATORS','VHR:10','IDENTIFIER','ru','РабочееВремя');
uis.table_record_translate('HREF_INDICATORS','VHR:10','NAME','ru','Рабочее время в часах');
uis.table_record_translate('HREF_INDICATORS','VHR:10','SHORT_NAME','ru','Рабочее время');
uis.table_record_translate('HREF_INDICATORS','VHR:11','IDENTIFIER','ru','КоэффициентБольничныхЛистов');
uis.table_record_translate('HREF_INDICATORS','VHR:11','NAME','ru','Коэффициент больничных листов');
uis.table_record_translate('HREF_INDICATORS','VHR:11','SHORT_NAME','ru','Коэффициент (Больничный лист)');
uis.table_record_translate('HREF_INDICATORS','VHR:12','IDENTIFIER','ru','КоличествоКомандировочныхДней');
uis.table_record_translate('HREF_INDICATORS','VHR:12','NAME','ru','Количество командировочных дней');
uis.table_record_translate('HREF_INDICATORS','VHR:12','SHORT_NAME','ru','Кол-во ком. дней');
uis.table_record_translate('HREF_INDICATORS','VHR:13','IDENTIFIER','ru','КоличествоОтпускныхДней');
uis.table_record_translate('HREF_INDICATORS','VHR:13','NAME','ru','Количество отпускных дней');
uis.table_record_translate('HREF_INDICATORS','VHR:13','SHORT_NAME','ru','Кол-во от. дней');
uis.table_record_translate('HREF_INDICATORS','VHR:14','IDENTIFIER','ru','СреднемесячноеКоличествоРабочихДней');
uis.table_record_translate('HREF_INDICATORS','VHR:14','NAME','ru','Среднемесячное количество рабочих дней');
uis.table_record_translate('HREF_INDICATORS','VHR:14','SHORT_NAME','ru','Среднемес. кол-во раб. дней');
uis.table_record_translate('HREF_INDICATORS','VHR:15','IDENTIFIER','ru','КоличествоБольничныхДней');
uis.table_record_translate('HREF_INDICATORS','VHR:15','NAME','ru','Количество больничных дней');
uis.table_record_translate('HREF_INDICATORS','VHR:15','SHORT_NAME','ru','Кол-во больн. дней');
uis.table_record_translate('HREF_INDICATORS','VHR:16','IDENTIFIER','ru','СреднеЧасовойОклад');
uis.table_record_translate('HREF_INDICATORS','VHR:16','NAME','ru','Средний часовой оклад');
uis.table_record_translate('HREF_INDICATORS','VHR:16','SHORT_NAME','ru','Сред. час. оклад');
uis.table_record_translate('HREF_INDICATORS','VHR:17','IDENTIFIER','ru','СверхурочныеЧасы');
uis.table_record_translate('HREF_INDICATORS','VHR:17','NAME','ru','Cверхурочные часы');
uis.table_record_translate('HREF_INDICATORS','VHR:17','SHORT_NAME','ru','Сверх. часы');
uis.table_record_translate('HREF_INDICATORS','VHR:18','IDENTIFIER','ru','КоэффициентСверхурочногоВремени');
uis.table_record_translate('HREF_INDICATORS','VHR:18','NAME','ru','Коэффициент сверхурочного времени');
uis.table_record_translate('HREF_INDICATORS','VHR:18','SHORT_NAME','ru','Коэф. сверх. времени');
uis.table_record_translate('HREF_INDICATORS','VHR:19','IDENTIFIER','ru','ШтрафЗаОпоздание');
uis.table_record_translate('HREF_INDICATORS','VHR:19','NAME','ru','Штраф за опоздание');
uis.table_record_translate('HREF_INDICATORS','VHR:19','SHORT_NAME','ru','Штраф за опоздание');
uis.table_record_translate('HREF_INDICATORS','VHR:2','IDENTIFIER','ru','ДоляНеполногоРабочегоВремени');
uis.table_record_translate('HREF_INDICATORS','VHR:2','NAME','ru','Доля неполного рабочего времени');
uis.table_record_translate('HREF_INDICATORS','VHR:2','SHORT_NAME','ru','Доля неполн. времени');
uis.table_record_translate('HREF_INDICATORS','VHR:20','IDENTIFIER','ru','ШтрафЗаРаннийУход');
uis.table_record_translate('HREF_INDICATORS','VHR:20','NAME','ru','Штраф за ранний уход');
uis.table_record_translate('HREF_INDICATORS','VHR:20','SHORT_NAME','ru','Штраф за ранний уход');
uis.table_record_translate('HREF_INDICATORS','VHR:21','IDENTIFIER','ru','ШтрафЗаОтсутствие');
uis.table_record_translate('HREF_INDICATORS','VHR:21','NAME','ru','Штраф за отсутствие');
uis.table_record_translate('HREF_INDICATORS','VHR:21','SHORT_NAME','ru','Штраф за отсутствие');
uis.table_record_translate('HREF_INDICATORS','VHR:22','IDENTIFIER','ru','ШтрафЗаПропускДня');
uis.table_record_translate('HREF_INDICATORS','VHR:22','NAME','ru','Штраф за пропуск дня');
uis.table_record_translate('HREF_INDICATORS','VHR:22','SHORT_NAME','ru','Штраф за пропуск дня');
uis.table_record_translate('HREF_INDICATORS','VHR:3','IDENTIFIER','ru','НормаДней');
uis.table_record_translate('HREF_INDICATORS','VHR:3','NAME','ru','Норма дней');
uis.table_record_translate('HREF_INDICATORS','VHR:3','SHORT_NAME','ru','Норма (дн.)');
uis.table_record_translate('HREF_INDICATORS','VHR:4','IDENTIFIER','ru','ВремяВДнях');
uis.table_record_translate('HREF_INDICATORS','VHR:4','NAME','ru','Время в днях');
uis.table_record_translate('HREF_INDICATORS','VHR:4','SHORT_NAME','ru','Время в днях');
uis.table_record_translate('HREF_INDICATORS','VHR:5','IDENTIFIER','ru','НормаЧасов');
uis.table_record_translate('HREF_INDICATORS','VHR:5','NAME','ru','Норма часов');
uis.table_record_translate('HREF_INDICATORS','VHR:5','SHORT_NAME','ru','Норма (часов)');
uis.table_record_translate('HREF_INDICATORS','VHR:6','IDENTIFIER','ru','ВремяВЧасах');
uis.table_record_translate('HREF_INDICATORS','VHR:6','NAME','ru','Время в часах');
uis.table_record_translate('HREF_INDICATORS','VHR:6','SHORT_NAME','ru','Время в часах');
uis.table_record_translate('HREF_INDICATORS','VHR:7','IDENTIFIER','ru','БонусЗаЭффективность');
uis.table_record_translate('HREF_INDICATORS','VHR:7','NAME','ru','Бонус за эффективность');
uis.table_record_translate('HREF_INDICATORS','VHR:7','SHORT_NAME','ru','Бонус за эффект.');
uis.table_record_translate('HREF_INDICATORS','VHR:8','IDENTIFIER','ru','ДополнительныйБонусЗаЭффективность');
uis.table_record_translate('HREF_INDICATORS','VHR:8','NAME','ru','Дополнительный бонус за эффективность');
uis.table_record_translate('HREF_INDICATORS','VHR:8','SHORT_NAME','ru','Доп. бонус за эффект.');
uis.table_record_translate('HREF_INDICATORS','VHR:9','IDENTIFIER','ru','РабочиеДни');
uis.table_record_translate('HREF_INDICATORS','VHR:9','NAME','ru','Рабочее время в днях');
uis.table_record_translate('HREF_INDICATORS','VHR:9','SHORT_NAME','ru','Рабочие дни');
uis.table_record_translate('HTT_CALENDARS','VHR:1','NAME','ru','Производственный календарь');
uis.table_record_translate('HTT_REQUEST_KINDS','VHR:1','NAME','ru','Больничный');
uis.table_record_translate('HTT_REQUEST_KINDS','VHR:2','NAME','ru','Отпуск');
uis.table_record_translate('HTT_REQUEST_KINDS','VHR:3','NAME','ru','Командировка');
uis.table_record_translate('HTT_REQUEST_KINDS','VHR:4','NAME','ru','Отгул');
uis.table_record_translate('HTT_REQUEST_KINDS','VHR:5','NAME','ru','Рабочая Встреча');
uis.table_record_translate('HTT_SCHEDULES','VHR:1','NAME','ru','Индивидуальный график');
uis.table_record_translate('HTT_SCHEDULES','VHR:2','NAME','ru','Индивидуальный график для позиции');
uis.table_record_translate('HTT_TIME_KINDS','VHR:1','LETTER_CODE','ru','Я');
uis.table_record_translate('HTT_TIME_KINDS','VHR:1','NAME','ru','Явка');
uis.table_record_translate('HTT_TIME_KINDS','VHR:10','LETTER_CODE','ru','К');
uis.table_record_translate('HTT_TIME_KINDS','VHR:10','NAME','ru','Командировка');
uis.table_record_translate('HTT_TIME_KINDS','VHR:11','LETTER_CODE','ru','ОТ');
uis.table_record_translate('HTT_TIME_KINDS','VHR:11','NAME','ru','Отпуск');
uis.table_record_translate('HTT_TIME_KINDS','VHR:12','LETTER_CODE','ru','СУ');
uis.table_record_translate('HTT_TIME_KINDS','VHR:12','NAME','ru','Сверхурочныe');
uis.table_record_translate('HTT_TIME_KINDS','VHR:13','LETTER_CODE','ru','РВ');
uis.table_record_translate('HTT_TIME_KINDS','VHR:13','NAME','ru','Рабочая Встреча');
uis.table_record_translate('HTT_TIME_KINDS','VHR:14','LETTER_CODE','ru','П');
uis.table_record_translate('HTT_TIME_KINDS','VHR:14','NAME','ru','Праздник');
uis.table_record_translate('HTT_TIME_KINDS','VHR:15','LETTER_CODE','ru','НД');
uis.table_record_translate('HTT_TIME_KINDS','VHR:15','NAME','ru','Нерабочий день');
uis.table_record_translate('HTT_TIME_KINDS','VHR:16','LETTER_CODE','ru','ДВ');
uis.table_record_translate('HTT_TIME_KINDS','VHR:16','NAME','ru','Дорабочее время');
uis.table_record_translate('HTT_TIME_KINDS','VHR:17','LETTER_CODE','ru','ПВ');
uis.table_record_translate('HTT_TIME_KINDS','VHR:17','NAME','ru','Послерабочее время');
uis.table_record_translate('HTT_TIME_KINDS','VHR:18','LETTER_CODE','ru','ОВ');
uis.table_record_translate('HTT_TIME_KINDS','VHR:18','NAME','ru','Обеденное время');
uis.table_record_translate('HTT_TIME_KINDS','VHR:19','LETTER_CODE','ru','СВП');
uis.table_record_translate('HTT_TIME_KINDS','VHR:19','NAME','ru','Cвободное время внутри плана');
uis.table_record_translate('HTT_TIME_KINDS','VHR:2','LETTER_CODE','ru','ОП');
uis.table_record_translate('HTT_TIME_KINDS','VHR:2','NAME','ru','Опоздание');
uis.table_record_translate('HTT_TIME_KINDS','VHR:20','LETTER_CODE','ru','ЯК');
uis.table_record_translate('HTT_TIME_KINDS','VHR:20','NAME','ru','Явка из корректировки');
uis.table_record_translate('HTT_TIME_KINDS','VHR:21','LETTER_CODE','ru','СК');
uis.table_record_translate('HTT_TIME_KINDS','VHR:21','NAME','ru','Сверхурочныe из корректировки');
uis.table_record_translate('HTT_TIME_KINDS','VHR:3','LETTER_CODE','ru','РУ');
uis.table_record_translate('HTT_TIME_KINDS','VHR:3','NAME','ru','Ранний Уход');
uis.table_record_translate('HTT_TIME_KINDS','VHR:4','LETTER_CODE','ru','ПО');
uis.table_record_translate('HTT_TIME_KINDS','VHR:4','NAME','ru','Почасовой Отгул');
uis.table_record_translate('HTT_TIME_KINDS','VHR:5','LETTER_CODE','ru','В');
uis.table_record_translate('HTT_TIME_KINDS','VHR:5','NAME','ru','Выходной');
uis.table_record_translate('HTT_TIME_KINDS','VHR:6','LETTER_CODE','ru','ОТС');
uis.table_record_translate('HTT_TIME_KINDS','VHR:6','NAME','ru','Отсутствие');
uis.table_record_translate('HTT_TIME_KINDS','VHR:7','LETTER_CODE','ru','СВ');
uis.table_record_translate('HTT_TIME_KINDS','VHR:7','NAME','ru','Свободное Время');
uis.table_record_translate('HTT_TIME_KINDS','VHR:8','LETTER_CODE','ru','Б');
uis.table_record_translate('HTT_TIME_KINDS','VHR:8','NAME','ru','Больничный');
uis.table_record_translate('HTT_TIME_KINDS','VHR:9','LETTER_CODE','ru','О');
uis.table_record_translate('HTT_TIME_KINDS','VHR:9','NAME','ru','Отгул');
uis.table_record_translate('MPR_OPER_TYPES','VHR:1','NAME','ru','Больничные');
uis.table_record_translate('MPR_OPER_TYPES','VHR:1','SHORT_NAME','ru','Больничные');
uis.table_record_translate('MPR_OPER_TYPES','VHR:2','NAME','ru','Командировочные');
uis.table_record_translate('MPR_OPER_TYPES','VHR:2','SHORT_NAME','ru','Командировочные');
uis.table_record_translate('MPR_OPER_TYPES','VHR:3','NAME','ru','Отпускные');
uis.table_record_translate('MPR_OPER_TYPES','VHR:3','SHORT_NAME','ru','Отпускные');
uis.table_record_translate('MPR_OPER_TYPES','VHR:4','NAME','ru','Почасовая оплата труда');
uis.table_record_translate('MPR_OPER_TYPES','VHR:4','SHORT_NAME','ru','Почасовая');
uis.table_record_translate('MPR_OPER_TYPES','VHR:5','NAME','ru','Поденная оплата труда');
uis.table_record_translate('MPR_OPER_TYPES','VHR:5','SHORT_NAME','ru','Поденная');
uis.table_record_translate('MPR_OPER_TYPES','VHR:6','NAME','ru','Помесячная оплата труда');
uis.table_record_translate('MPR_OPER_TYPES','VHR:6','SHORT_NAME','ru','Помесячная');
uis.table_record_translate('MPR_OPER_TYPES','VHR:7','NAME','ru','Сверхурочная оплата труда');
uis.table_record_translate('MPR_OPER_TYPES','VHR:7','SHORT_NAME','ru','Сверхурочные');
uis.table_record_translate('MPR_OPER_TYPES','VHR:8','NAME','ru','Помесячная оплата труда (за отработанные часы)');
uis.table_record_translate('MPR_OPER_TYPES','VHR:8','SHORT_NAME','ru','Помесячная (за отработанные часы)');
uis.table_record_translate('MPR_OPER_TYPES','VHR:9','NAME','ru','Штрафы за нарушение дисциплины');
uis.table_record_translate('MPR_OPER_TYPES','VHR:9','SHORT_NAME','ru','Штрафы за нарушение дисциплины');
uis.table_record_translate('MS_TASK_GROUPS','VHR:1','NAME','ru','План');
commit;
end;
/
