prompt PATH TRANSLATE /vhr/rep/hpd/transfer_multiple
begin
uis.lang_ru('#f:/vhr/rep/hpd/transfer_multiple','Приказ о кадровом переводе списком');
uis.lang_ru('ui-vhr111:concluding term','Срок заключения договора');
uis.lang_ru('ui-vhr111:contract date','Дата договора');
uis.lang_ru('ui-vhr111:contract number','Номер договора');
uis.lang_ru('ui-vhr111:contract term','Характер работы');
uis.lang_ru('ui-vhr111:director job name','Должность руководителя');
uis.lang_ru('ui-vhr111:director name','ФИО руководителя');
uis.lang_ru('ui-vhr111:division name','Новое подразделение');
uis.lang_ru('ui-vhr111:employee name','Сотрудник');
uis.lang_ru('ui-vhr111:employment type name','Вид работы');
uis.lang_ru('ui-vhr111:expiry date','Срок действия договора');
uis.lang_ru('ui-vhr111:filial name','Название организации');
uis.lang_ru('ui-vhr111:fixed term','Срочный трудовой договор');
uis.lang_ru('ui-vhr111:fixed term base name','Основание срочного договора');
uis.lang_ru('ui-vhr111:hiring conditions','Условия приема');
uis.lang_ru('ui-vhr111:job name','Новая должность');
uis.lang_ru('ui-vhr111:journal date','Дата документа');
uis.lang_ru('ui-vhr111:journal name','Название документа');
uis.lang_ru('ui-vhr111:journal number','Номер документа');
uis.lang_ru('ui-vhr111:labor function name','Трудовая функция');
uis.lang_ru('ui-vhr111:old division name','Прежнее подразделение');
uis.lang_ru('ui-vhr111:old job name','Прежняя должность');
uis.lang_ru('ui-vhr111:old rank name','Прежний разряд');
uis.lang_ru('ui-vhr111:old schedule name','Прежний график работы');
uis.lang_ru('ui-vhr111:old staff number','Прежний табельный номер');
uis.lang_ru('ui-vhr111:old wage amount','Прежний оклад');
uis.lang_ru('ui-vhr111:old working day','Прежняя продолжительность рабочего дня');
uis.lang_ru('ui-vhr111:old working week','Прежняя продолжительность рабочей недели');
uis.lang_ru('ui-vhr111:old_robot name','Предыдущая позиция');
uis.lang_ru('ui-vhr111:other conditions','Иные условия');
uis.lang_ru('ui-vhr111:quantity','Ставка');
uis.lang_ru('ui-vhr111:rank name','Новый разряд');
uis.lang_ru('ui-vhr111:representative basis','Основание представителя');
uis.lang_ru('ui-vhr111:robot name','Позиция');
uis.lang_ru('ui-vhr111:schedule name','Новый график работы');
uis.lang_ru('ui-vhr111:staff number','Табельный номер');
uis.lang_ru('ui-vhr111:transfer base','Основание перевода');
uis.lang_ru('ui-vhr111:transfer begin','Начало перевода');
uis.lang_ru('ui-vhr111:transfer end','Окончание перевода');
uis.lang_ru('ui-vhr111:transfer kind name','Вид перевода');
uis.lang_ru('ui-vhr111:transfer reason','Причина перевода');
uis.lang_ru('ui-vhr111:transfers','Список сотрудников');
uis.lang_ru('ui-vhr111:wage amount','Новый оклад');
uis.lang_ru('ui-vhr111:working day','Продолжительность рабочего дня');
uis.lang_ru('ui-vhr111:working week','Продолжительность рабочей недели');
uis.lang_ru('ui-vhr111:workplace equipment','Оборудование рабочего места');
commit;
end;
/
