prompt PATH TRANSLATE /vhr/hpd/audit/journal_audit_details
begin
uis.lang_ru('#f:/vhr/hpd/audit/journal_audit_details','Детали истории изменений');
uis.lang_ru('ui-vhr183:based on doc','Основание увольнения');
uis.lang_ru('ui-vhr183:begin date','Начало');
uis.lang_ru('ui-vhr183:change data','Изменить данные');
uis.lang_ru('ui-vhr183:change date','Дата изменения');
uis.lang_ru('ui-vhr183:coefficient','Коэффициент');
uis.lang_ru('ui-vhr183:concluding term','Срок заключения договора');
uis.lang_ru('ui-vhr183:contract date','Дата договора');
uis.lang_ru('ui-vhr183:contract number','Номер договора');
uis.lang_ru('ui-vhr183:currency name','Валюта');
uis.lang_ru('ui-vhr183:days limit','Кол-во отпускных дней');
uis.lang_ru('ui-vhr183:dismissal date','Дата увольнения');
uis.lang_ru('ui-vhr183:dismissal reason name','Причина увольнения');
uis.lang_ru('ui-vhr183:division name','Подразделение');
uis.lang_ru('ui-vhr183:employment source name','Источник занятости');
uis.lang_ru('ui-vhr183:employment type name','Вид занятости');
uis.lang_ru('ui-vhr183:end date','Конец');
uis.lang_ru('ui-vhr183:file name','Файл');
uis.lang_ru('ui-vhr183:fixed term','Срочный трудовой договор');
uis.lang_ru('ui-vhr183:fixed term base name','Основание срочного договора');
uis.lang_ru('ui-vhr183:free time','Вне графика');
uis.lang_ru('ui-vhr183:fte','Ставка');
uis.lang_ru('ui-vhr183:hiring conditions','Условия приема');
uis.lang_ru('ui-vhr183:hiring date','Дата приема');
uis.lang_ru('ui-vhr183:indicator name','Показатель расчета зарплаты');
uis.lang_ru('ui-vhr183:indicator names','Показатели');
uis.lang_ru('ui-vhr183:indicator value','Значение показателя расчета зарплаты');
uis.lang_ru('ui-vhr183:job name','Должность');
uis.lang_ru('ui-vhr183:journal date','Дата документа');
uis.lang_ru('ui-vhr183:journal number','Номер документа');
uis.lang_ru('ui-vhr183:journal type name','Тип документа');
uis.lang_ru('ui-vhr183:note','Примечание');
uis.lang_ru('ui-vhr183:oper type name','Начисление');
uis.lang_ru('ui-vhr183:order no','№');
uis.lang_ru('ui-vhr183:other conditions','Иные условия');
uis.lang_ru('ui-vhr183:overtime','Сверхурочно');
uis.lang_ru('ui-vhr183:overtime date','Дата');
uis.lang_ru('ui-vhr183:overtime total','Сверхурочно');
uis.lang_ru('ui-vhr183:person name','Физическое лицо');
uis.lang_ru('ui-vhr183:posted','Проведено');
uis.lang_ru('ui-vhr183:rank name','Разряд');
uis.lang_ru('ui-vhr183:reason name','Причина');
uis.lang_ru('ui-vhr183:region name','Регион');
uis.lang_ru('ui-vhr183:representative basis','Основание представителя');
uis.lang_ru('ui-vhr183:robot name','Позиция');
uis.lang_ru('ui-vhr183:schedule name','График работы');
uis.lang_ru('ui-vhr183:sick leave number','Номер больничного листа');
uis.lang_ru('ui-vhr183:staff name','Сотрудник');
uis.lang_ru('ui-vhr183:transfer base','Основание перевода');
uis.lang_ru('ui-vhr183:transfer begin','Начало перевода');
uis.lang_ru('ui-vhr183:transfer end','Окончание перевода');
uis.lang_ru('ui-vhr183:transfer reason','Причина перевода');
uis.lang_ru('ui-vhr183:trial period','Испыт. срок (дней)');
uis.lang_ru('ui-vhr183:turnout time','Явка');
uis.lang_ru('ui-vhr183:workplace equipment','Оборудование рабочего места');
commit;
end;
/
