prompt PATH TRANSLATE /vhr/hpr/start/wage_sheet_list
begin
uis.lang_ru('#a:/vhr/hpr/start/wage_sheet_list$add','Создать');
uis.lang_ru('#a:/vhr/hpr/start/wage_sheet_list$delete','Удалить');
uis.lang_ru('#a:/vhr/hpr/start/wage_sheet_list$edit','Изменить');
uis.lang_ru('#a:/vhr/hpr/start/wage_sheet_list$post','Провести');
uis.lang_ru('#a:/vhr/hpr/start/wage_sheet_list$run','Отчет');
uis.lang_ru('#a:/vhr/hpr/start/wage_sheet_list$unpost','Отменить');
uis.lang_ru('#a:/vhr/hpr/start/wage_sheet_list+onetime$add','Создать');
uis.lang_ru('#a:/vhr/hpr/start/wage_sheet_list+onetime$delete','Удалить');
uis.lang_ru('#a:/vhr/hpr/start/wage_sheet_list+onetime$edit','Изменить');
uis.lang_ru('#a:/vhr/hpr/start/wage_sheet_list+onetime$post','Провести');
uis.lang_ru('#a:/vhr/hpr/start/wage_sheet_list+onetime$unpost','Отменить');
uis.lang_ru('#f:/vhr/hpr/start/wage_sheet_list','Расчет оклада');
uis.lang_ru('#f:/vhr/hpr/start/wage_sheet_list+onetime','Разовые начисления');
uis.lang_ru('ui-vhr315:accrual','Начислено');
uis.lang_ru('ui-vhr315:accrual amount','Итого');
uis.lang_ru('ui-vhr315:accrued','Начислено');
uis.lang_ru('ui-vhr315:amount','Сумма');
uis.lang_ru('ui-vhr315:break time','Перерыв');
uis.lang_ru('ui-vhr315:date','Дата');
uis.lang_ru('ui-vhr315:day','День');
uis.lang_ru('ui-vhr315:day_skip_amount','Пропуск дня');
uis.lang_ru('ui-vhr315:days','Дней');
uis.lang_ru('ui-vhr315:deduction','Удержано');
uis.lang_ru('ui-vhr315:division','Подразделение');
uis.lang_ru('ui-vhr315:division: $1','Подразделение: $1');
uis.lang_ru('ui-vhr315:division: $1{division_name}','Подразделение: $1');
uis.lang_ru('ui-vhr315:early','Ранний уход');
uis.lang_ru('ui-vhr315:early amount','Ранний уход');
uis.lang_ru('ui-vhr315:early fact','Ранний уход (время)');
uis.lang_ru('ui-vhr315:fact','Отработано');
uis.lang_ru('ui-vhr315:fact time','Отработано');
uis.lang_ru('ui-vhr315:fte: $1{fte_name}','Тип занятости: $1');
uis.lang_ru('ui-vhr315:input','Приход');
uis.lang_ru('ui-vhr315:job','Должность');
uis.lang_ru('ui-vhr315:job: $1{job_name}','Должность: $1');
uis.lang_ru('ui-vhr315:lack','Отсутствие');
uis.lang_ru('ui-vhr315:lack amount','Отсутствие');
uis.lang_ru('ui-vhr315:lack fact','Отсутствие (время)');
uis.lang_ru('ui-vhr315:late','Опоздания');
uis.lang_ru('ui-vhr315:late amount','Опоздание');
uis.lang_ru('ui-vhr315:late fact','Опоздание (время)');
uis.lang_ru('ui-vhr315:manager: $1{manager_name}','Руководитель: $1');
uis.lang_ru('ui-vhr315:mark_skip_amount','Пропуск отметки');
uis.lang_ru('ui-vhr315:month: $1','Месяц: $1');
uis.lang_ru('ui-vhr315:monthly amount','Оклад');
uis.lang_ru('ui-vhr315:monthly days','Дней');
uis.lang_ru('ui-vhr315:monthly plan','По плану (месяц)');
uis.lang_ru('ui-vhr315:monthly time','Часов');
uis.lang_ru('ui-vhr315:nighttime','Доплата');
uis.lang_ru('ui-vhr315:nighttime amount','Сумма доплаты');
uis.lang_ru('ui-vhr315:onetime accrual','Премия');
uis.lang_ru('ui-vhr315:onetime penalty','Штраф');
uis.lang_ru('ui-vhr315:others ..','Другие');
uis.lang_ru('ui-vhr315:output','Уход');
uis.lang_ru('ui-vhr315:overtime','Сверхурочно');
uis.lang_ru('ui-vhr315:overtime amount','Сверхурочно');
uis.lang_ru('ui-vhr315:overtime fact','Сверхурочно (время)');
uis.lang_ru('ui-vhr315:part begin','Дата начала');
uis.lang_ru('ui-vhr315:penalty','Удержания');
uis.lang_ru('ui-vhr315:penalty amount','Итого');
uis.lang_ru('ui-vhr315:period kind: $1{period_kind} ($2{period_begin} - $3{period_end})','Тип периода: <b>$1</b> ($2 - $3)');
uis.lang_ru('ui-vhr315:period plan','По плану (период)');
uis.lang_ru('ui-vhr315:period: from $1{begin_date} to $2{end_date}','Период: $1 - $2');
uis.lang_ru('ui-vhr315:plan','План');
uis.lang_ru('ui-vhr315:plan amount','Оклад');
uis.lang_ru('ui-vhr315:plan days','Дней');
uis.lang_ru('ui-vhr315:plan time','Часов');
uis.lang_ru('ui-vhr315:rest day','Выходной день');
uis.lang_ru('ui-vhr315:rownum','№');
uis.lang_ru('ui-vhr315:schedule','График работы');
uis.lang_ru('ui-vhr315:schedule: $1{schedule_name}','График работы: $1');
uis.lang_ru('ui-vhr315:sheet is not posted, sheet_id=$1','Расчет оклада не проведен, ИД=$1');
uis.lang_ru('ui-vhr315:sheet_number: $1','Номер: $1');
uis.lang_ru('ui-vhr315:skip day','Пропуск дня');
uis.lang_ru('ui-vhr315:skip mark','Пропуск отметки');
uis.lang_ru('ui-vhr315:staff name','Сотрудник');
uis.lang_ru('ui-vhr315:staff number','Табельный номер');
uis.lang_ru('ui-vhr315:staff: $1{staff_name}','Сотрудник: $1');
uis.lang_ru('ui-vhr315:time','Время');
uis.lang_ru('ui-vhr315:total','Итого');
uis.lang_ru('ui-vhr315:total amount','Общая сумма');
uis.lang_ru('ui-vhr315:total:','Итого:');
uis.lang_ru('ui-vhr315:type','Тип занятости');
uis.lang_ru('ui-vhr315:wage','Зарплата');
uis.lang_ru('ui-vhr315:wage amount','Оклад');
uis.lang_ru('ui-vhr315:wage days','Дней');
uis.lang_ru('ui-vhr315:wage time','Часов');
uis.lang_ru('ui-vhr315:you can not see rows that contain jobs that you do not have access to','⚠️ Вы не можете видеть информацию по тем сотрудникам, доступ к заработной плате которых для Вас ограничен');
commit;
end;
/
