prompt PATH TRANSLATE /vhr/rep/href/employee_by_gender
begin
uis.lang_ru('#a:/vhr/rep/href/employee_by_gender$select_edu_stage','Выбрать вид образования');
uis.lang_ru('#a:/vhr/rep/href/employee_by_gender$select_rank','Выбрать квалификационный разряд');
uis.lang_ru('#f:/vhr/rep/href/employee_by_gender','Отчет по гендерному разделению сотрудников');
uis.lang_ru('ui-vhr291:... others','и другие');
uis.lang_ru('ui-vhr291:age','Возраст');
uis.lang_ru('ui-vhr291:age range title','Отчет по гендерному разделению сотрудников (возраст)');
uis.lang_ru('ui-vhr291:age ranges','Возраст');
uis.lang_ru('ui-vhr291:birthday','Дата рождения');
uis.lang_ru('ui-vhr291:count','Кол-во');
uis.lang_ru('ui-vhr291:count %','Кол-во (%)');
uis.lang_ru('ui-vhr291:count female','Женщины');
uis.lang_ru('ui-vhr291:count male','Мужчины');
uis.lang_ru('ui-vhr291:date $1','Дата: $1');
uis.lang_ru('ui-vhr291:division','Подразделение');
uis.lang_ru('ui-vhr291:divisions: $1','Подразделение: $1');
uis.lang_ru('ui-vhr291:edu stages','Вид образования');
uis.lang_ru('ui-vhr291:educ title','Отчет по гендерному разделению сотрудников (вид образования)');
uis.lang_ru('ui-vhr291:eduction stage : $1','Виды образования: $1');
uis.lang_ru('ui-vhr291:experience range title','Отчет по гендерному разделению сотрудников (опыт)');
uis.lang_ru('ui-vhr291:female','Женский');
uis.lang_ru('ui-vhr291:from $1 ages','от $1 лет');
uis.lang_ru('ui-vhr291:from $1 experiences','от $1 лет');
uis.lang_ru('ui-vhr291:from $1 to $2 ages','от $1 до $2 лет');
uis.lang_ru('ui-vhr291:from $1 to $2 experiences','от $1 до $2 лет');
uis.lang_ru('ui-vhr291:gender','Пол');
uis.lang_ru('ui-vhr291:hiring_date','Дата приема');
uis.lang_ru('ui-vhr291:job','Должность');
uis.lang_ru('ui-vhr291:male','Мужской');
uis.lang_ru('ui-vhr291:month','Месяц');
uis.lang_ru('ui-vhr291:name','Сотрудник');
uis.lang_ru('ui-vhr291:rank : $1','Квалификационные разряды: $1');
uis.lang_ru('ui-vhr291:rank title','Отчет по гендерному разделению сотрудников (квалификационный разряд)');
uis.lang_ru('ui-vhr291:ranks','Разряд');
uis.lang_ru('ui-vhr291:run_header: range not found, type=$1','Должен быть задан как минимум один диапазон!');
uis.lang_ru('ui-vhr291:some days ago','неск. дней назад');
uis.lang_ru('ui-vhr291:to $1 ages','до $1 лет');
uis.lang_ru('ui-vhr291:to $1 experiences','до $1 лет');
uis.lang_ru('ui-vhr291:total','Всего');
uis.lang_ru('ui-vhr291:wage','Оклад');
uis.lang_ru('ui-vhr291:wage %','Оклад (%)');
uis.lang_ru('ui-vhr291:wage female','Оклад');
uis.lang_ru('ui-vhr291:wage male','Оклад');
uis.lang_ru('ui-vhr291:work ranges','Опыт');
uis.lang_ru('ui-vhr291:work_month','Опыт');
uis.lang_ru('ui-vhr291:year','лет');
commit;
end;
/
