prompt PATH TRANSLATE /vhr/href/start/employee_import
begin
uis.lang_uz('#a:/vhr/href/start/employee_import$save_setting','Sozlamalarni saqlash');
uis.lang_uz('#f:/vhr/href/start/employee_import','Xodimlar (import)');
uis.lang_uz('ui-vhr309:$1{error message} with address $2{address}','Xatolik: $1, Xatolik sababi Manzil: $2');
uis.lang_uz('ui-vhr309:$1{error message} with birthday $2{birthday}','Xatolik: $1, Xatolik sababi Tug''ilgan kun: $2');
uis.lang_uz('ui-vhr309:$1{error message} with division $2{division}','Xatolik: $1, Xatolik sababi Bo''lim: $2');
uis.lang_uz('ui-vhr309:$1{error message} with email $2{email}','Xatolik: $1, Xatolik sababi E-mail: $2');
uis.lang_uz('ui-vhr309:$1{error message} with fte $2{fte}','Xatolik: $1, Xatolik sababi Ish vaqti turi: $2');
uis.lang_uz('ui-vhr309:$1{error message} with gender $2{gender}','Xatolik: $1, Xatolik sababi Jins: $2');
uis.lang_uz('ui-vhr309:$1{error message} with hiring_date $2{hiring_date}','Xatolik: $1, Xatolik sababi Ishga qabul qilingan sanasi: $2');
uis.lang_uz('ui-vhr309:$1{error message} with iapa $2{iapa}','Xatolik: $1, Xatolik sababi ShJBPH: $2');
uis.lang_uz('ui-vhr309:$1{error message} with job $2{job}','Xatolik: $1, Xatolik sababi Lavozim: $2');
uis.lang_uz('ui-vhr309:$1{error message} with legal address $2{legal_address}','Xatolik: $1, Xatolik sababi Ro''yxatga olingan manzil: $2');
uis.lang_uz('ui-vhr309:$1{error message} with location $2{location}','Xatolik: $1, Xatolik sababi Joylashuv: $2');
uis.lang_uz('ui-vhr309:$1{error message} with login $2{login}','Xatolik: $1, Xatolik sababi Login: $2');
uis.lang_uz('ui-vhr309:$1{error message} with main phone $2{main phone}','Xatolik: $1, Xatolik sababi Telefon raqam: $2');
uis.lang_uz('ui-vhr309:$1{error message} with nationality $2{nationality}','Xatolik: $1, Xatolik sababi Millat: $2');
uis.lang_uz('ui-vhr309:$1{error message} with natural person first name $2{natural person}','Xatolik: $1, Xatolik sababi Ism: $2');
uis.lang_uz('ui-vhr309:$1{error message} with natural person last name $2{natural person}','Xatolik: $1, Xatolik sababi Familiya: $2');
uis.lang_uz('ui-vhr309:$1{error message} with natural person middle name $2{natural person}','Xatolik: $1, Xatolik sababi Otasining ismi: $2');
uis.lang_uz('ui-vhr309:$1{error message} with npin $2{npin}','Xatolik: $1, Xatolik sababi JShShIR: $2');
uis.lang_uz('ui-vhr309:$1{error message} with region $2{region}','Xatolik: $1, Xatolik sababi Hudud: $2');
uis.lang_uz('ui-vhr309:$1{error message} with salary_amount $2{salary_amount}','Xatolik: $1, Xatolik sababi Ish haqi: $2');
uis.lang_uz('ui-vhr309:$1{error message} with salary_type $2{salary_type}','Xatolik: $1, Xatolik sababi Ish haqi turi: $2');
uis.lang_uz('ui-vhr309:$1{error message} with schedule $2{schedule}','Xatolik: $1, Xatolik sababi Ish jadvali: $2');
uis.lang_uz('ui-vhr309:$1{error message} with staff_number $2{employee number}','Xatolik: $1, Xatolik sababi Xodim raqami: $2');
uis.lang_uz('ui-vhr309:address','Manzil');
uis.lang_uz('ui-vhr309:birthday','Tug''ilgan kun');
uis.lang_uz('ui-vhr309:chosen job is not belongs to chosen division, job_id=$1, division_id=$2','Tanlangan lavozim tanlangan bo‘limga tegishli emas, Lavozim ID=$1, Bo‘lim ID=$2');
uis.lang_uz('ui-vhr309:division','Bo''lim');
uis.lang_uz('ui-vhr309:email','E-mail');
uis.lang_uz('ui-vhr309:employees','Xodimlar');
uis.lang_uz('ui-vhr309:first_name','Ism');
uis.lang_uz('ui-vhr309:fte_name','Ish vaqti turi');
uis.lang_uz('ui-vhr309:gender','Jins');
uis.lang_uz('ui-vhr309:hiring_date','Ishga qabul qilingan sana');
uis.lang_uz('ui-vhr309:iapa','ShJBPH');
uis.lang_uz('ui-vhr309:identifier:code','Kod');
uis.lang_uz('ui-vhr309:identifier:name','Nom');
uis.lang_uz('ui-vhr309:job','Lavozim');
uis.lang_uz('ui-vhr309:last_name','Familiya');
uis.lang_uz('ui-vhr309:legal_address','Ro''yxatga olingan manzil');
uis.lang_uz('ui-vhr309:location','Joylashuv');
uis.lang_uz('ui-vhr309:login','Login');
uis.lang_uz('ui-vhr309:login is used, $1=login','Login boshqa foydalanuvchiga biriktirilgan, Login=$1');
uis.lang_uz('ui-vhr309:main_phone','Telefon raqam');
uis.lang_uz('ui-vhr309:middle_name','Otasining ismi');
uis.lang_uz('ui-vhr309:nationality_name','Millat');
uis.lang_uz('ui-vhr309:npin','JShShIR');
uis.lang_uz('ui-vhr309:region','Hudud');
uis.lang_uz('ui-vhr309:salary_amount','Ish haqi');
uis.lang_uz('ui-vhr309:salary_type','Ish haqi turi');
uis.lang_uz('ui-vhr309:schedule','Ish jadvali');
uis.lang_uz('ui-vhr309:staff_number','Xodim raqami');
commit;
end;
/
