prompt PATH TRANSLATE /vhr/href/employee/employee_import
begin
uis.lang_en('#a:/vhr/href/employee/employee_import$save_setting','Save settings');
uis.lang_en('#f:/vhr/href/employee/employee_import','Employees / Import');
uis.lang_en('ui-vhr265:$1{error message} with address $2{address}','Error $1 in Address: $2');
uis.lang_en('ui-vhr265:$1{error message} with birthday $2{birthday}','Error $1 in Birth Date: $2');
uis.lang_en('ui-vhr265:$1{error message} with corporate email $2{corporate_email}','Error $1 in Corporate E-mail: $2');
uis.lang_en('ui-vhr265:$1{error message} with division $2{division}','Error $1 in Department: $2');
uis.lang_en('ui-vhr265:$1{error message} with email $2{email}','Error $1 in Email: $2');
uis.lang_en('ui-vhr265:$1{error message} with employee id $2{employee id}','Error $1 in Employee ID: $2');
uis.lang_en('ui-vhr265:$1{error message} with employee number $2{employee number}','Error $1 in PersNo: $2');
uis.lang_en('ui-vhr265:$1{error message} with extra phone number $2{extra phone number}','Error $1 in Additional Phone Number: $2');
uis.lang_en('ui-vhr265:$1{error message} with fte $2{fte}','Error $1 in Full-time equivalent $2');
uis.lang_en('ui-vhr265:$1{error message} with gender $2{gender}','Error $1 in Gender: $2');
uis.lang_en('ui-vhr265:$1{error message} with hiring date $2{hiring_date}','Error $1 in Hiring Date: $2');
uis.lang_en('ui-vhr265:$1{error message} with iapa $2{iapa}','Error $1 in IPSA: $2');
uis.lang_en('ui-vhr265:$1{error message} with job $2{job}','Error $1 in Job: $2');
uis.lang_en('ui-vhr265:$1{error message} with legal address $2{legal_address}','Error $1 in Legal Address: $2');
uis.lang_en('ui-vhr265:$1{error message} with location $2{location}','Error $1 in Location: $2');
uis.lang_en('ui-vhr265:$1{error message} with main phone $2{main phone}','Error $1 in Phone: $2');
uis.lang_en('ui-vhr265:$1{error message} with nationality $2{nationality}','Error $1 in Nationality: $2');
uis.lang_en('ui-vhr265:$1{error message} with natural person first name $2{natural person}','Error $1 in First Name: $2');
uis.lang_en('ui-vhr265:$1{error message} with natural person last name $2{natural person}','Error $1 in Last Name: $2');
uis.lang_en('ui-vhr265:$1{error message} with natural person middle name $2{natural person}','Error $1 in Patronymic: $2');
uis.lang_en('ui-vhr265:$1{error message} with npin $2{npin}','Error $1 in IPIN: $2');
uis.lang_en('ui-vhr265:$1{error message} with oper type $2{oper_type}','Error $1 in Accrual: $2');
uis.lang_en('ui-vhr265:$1{error message} with org unit $2{org unit}','Error $1 in Org. Unit: $2');
uis.lang_en('ui-vhr265:$1{error message} with passport_begin_date $2{passport_begin_date}','Error $1 in Valid From: $2');
uis.lang_en('ui-vhr265:$1{error message} with passport_expiry_date $2{passport_expiry_date}','Error $1 in Valid Until: $2');
uis.lang_en('ui-vhr265:$1{error message} with passport_issued_by $2{passport_issued_by}','Error $1 in Issued by: $2');
uis.lang_en('ui-vhr265:$1{error message} with passport_issued_date $2{passport_issued_date}','Error $1 in Issued: $2');
uis.lang_en('ui-vhr265:$1{error message} with passport_number $2{passport_number}','Error $1 in Passport Number: $2');
uis.lang_en('ui-vhr265:$1{error message} with passport_series $2{passport_series}','Error $1 in Passport Series: $2');
uis.lang_en('ui-vhr265:$1{error message} with pin $2{pin}','Error $1 in PIN: $2');
uis.lang_en('ui-vhr265:$1{error message} with pin_code $2{pin_code}','Error $1 in Password: $2');
uis.lang_en('ui-vhr265:$1{error message} with rank $2{rank}','Error $1 in Rank: $2');
uis.lang_en('ui-vhr265:$1{error message} with region $2{region}','Error $1 in Region: $2');
uis.lang_en('ui-vhr265:$1{error message} with rfid_code $2{rfid_code}','Error $1 in RFID Code: $2');
uis.lang_en('ui-vhr265:$1{error message} with robot $2{robot}','Error $1 in Position $2');
uis.lang_en('ui-vhr265:$1{error message} with schedule $2{schedule}','Error $1 in Work Schedule: $2');
uis.lang_en('ui-vhr265:$1{error message} with tin $2{tin}','Error $1 in TIN: $2');
uis.lang_en('ui-vhr265:$1{error message} with wage $2{wage}','Error $1 in Salary: $2');
uis.lang_en('ui-vhr265:$1{error message} with wage scale $2{wage scale}','Error $1 in Tariff Group: $2');
uis.lang_en('ui-vhr265:address','Address');
uis.lang_en('ui-vhr265:birthday','Birth Date');
uis.lang_en('ui-vhr265:chosen job is not belongs to chosen division, job_id=$1, division_id=$2','The selected job does not belong to the selected department, job ID=$1, department ID=$2');
uis.lang_en('ui-vhr265:corporate_email','Corporate E-mail');
uis.lang_en('ui-vhr265:division','Department');
uis.lang_en('ui-vhr265:division (code)','Department Code');
uis.lang_en('ui-vhr265:email','Email');
uis.lang_en('ui-vhr265:employee_id','Employee ID');
uis.lang_en('ui-vhr265:employee_number','PersNo');
uis.lang_en('ui-vhr265:employees','Employees');
uis.lang_en('ui-vhr265:error with first name=$1{first name}, last name=$2{last_name}, login=$3{login} already used by another user','Error, First name: $1, Last name: $2, Login: $3 are already used by another user');
uis.lang_en('ui-vhr265:extra_phone_number','Additional Phone Number');
uis.lang_en('ui-vhr265:first name','First Name');
uis.lang_en('ui-vhr265:first_name','First Name');
uis.lang_en('ui-vhr265:fte','Full-time equivalent');
uis.lang_en('ui-vhr265:gender','Gender (M / F)');
uis.lang_en('ui-vhr265:hiring_date','Hiring Date');
uis.lang_en('ui-vhr265:iapa','IPSA');
uis.lang_en('ui-vhr265:identifier: code','Code');
uis.lang_en('ui-vhr265:identifier: name','Name');
uis.lang_en('ui-vhr265:job','Job');
uis.lang_en('ui-vhr265:job (code)','Position Code');
uis.lang_en('ui-vhr265:last name','Last Name');
uis.lang_en('ui-vhr265:last_name','Last Name');
uis.lang_en('ui-vhr265:legal_address','Legal Address');
uis.lang_en('ui-vhr265:location','Location');
uis.lang_en('ui-vhr265:location (code)','Location Code');
uis.lang_en('ui-vhr265:login','Login');
uis.lang_en('ui-vhr265:login_template: first_name.last_name','First Name Last Name');
uis.lang_en('ui-vhr265:login_template: first_name_last_name','First Name_Last Name');
uis.lang_en('ui-vhr265:login_template: last_name.first_name','Last Name First Name');
uis.lang_en('ui-vhr265:login_template: last_name_first_name','Last Name_First Name');
uis.lang_en('ui-vhr265:main phone','Phone');
uis.lang_en('ui-vhr265:main_phone','Phone');
uis.lang_en('ui-vhr265:middle name','Patronymic');
uis.lang_en('ui-vhr265:middle_name','Patronymic');
uis.lang_en('ui-vhr265:nationality','Nationality');
uis.lang_en('ui-vhr265:note','Note');
uis.lang_en('ui-vhr265:npin','IPIN');
uis.lang_en('ui-vhr265:oper_type','Accrual');
uis.lang_en('ui-vhr265:org unit','Org. Unit');
uis.lang_en('ui-vhr265:org unit (code)','Org. Unit (code)');
uis.lang_en('ui-vhr265:passport_begin_date','Valid From (passport)');
uis.lang_en('ui-vhr265:passport_expiry_date','Valid Until (passport)');
uis.lang_en('ui-vhr265:passport_issued_by','Issued by (passport)');
uis.lang_en('ui-vhr265:passport_issued_date','Issued (passport)');
uis.lang_en('ui-vhr265:passport_number','Passport Number');
uis.lang_en('ui-vhr265:passport_series','Passport Series');
uis.lang_en('ui-vhr265:pin','PIN');
uis.lang_en('ui-vhr265:pin_code','Password');
uis.lang_en('ui-vhr265:rank','Rank');
uis.lang_en('ui-vhr265:region','Region');
uis.lang_en('ui-vhr265:rfid_code','RFID Code');
uis.lang_en('ui-vhr265:robot','Position');
uis.lang_en('ui-vhr265:schedule','Work Schedule');
uis.lang_en('ui-vhr265:schedule (code)','Work Schedule (code)');
uis.lang_en('ui-vhr265:tin','TIN');
uis.lang_en('ui-vhr265:wage','Salary');
uis.lang_en('ui-vhr265:wage scale','Tariff Group');
uis.lang_en('ui-vhr265:wage_scale','Tariff Group');
commit;
end;
/
