prompt MOBILE TRANSLATE
begin
uis.lang_en('#mob:vhr:attendance_chart:free_day','Rest day');
uis.lang_en('#mob:vhr:attendance_chart:intime','On time');
uis.lang_en('#mob:vhr:attendance_chart:late','Late');
uis.lang_en('#mob:vhr:attendance_chart:no_schedule','No schedule');
uis.lang_en('#mob:vhr:attendance_chart:not_begin','Not working time');
uis.lang_en('#mob:vhr:attendance_chart:not_come','Absent');
uis.lang_en('#mob:vhr:attendance_chart:take_leave','Requested for absence');
uis.lang_en('#mob:vhr:camera:back','Back');
uis.lang_en('#mob:vhr:camera:face_recognition','Identify');
uis.lang_en('#mob:vhr:camera:ok','Ok');
uis.lang_en('#mob:vhr:camera:please_wait','Please, wait');
uis.lang_en('#mob:vhr:camera:repeat','Try again');
uis.lang_en('#mob:vhr:camera:send_note','Track sending');
uis.lang_en('#mob:vhr:camera:skip','Skip');
uis.lang_en('#mob:vhr:camera:warning','Warning!');
uis.lang_en('#mob:vhr:change:add','Add');
uis.lang_en('#mob:vhr:change:cancel','Cancel');
uis.lang_en('#mob:vhr:change:comment','Comment');
uis.lang_en('#mob:vhr:change:comment_text','Text');
uis.lang_en('#mob:vhr:change:send','Send');
uis.lang_en('#mob:vhr:change:toolbar_title','Schedule change');
uis.lang_en('#mob:vhr:change_item:date','date');
uis.lang_en('#mob:vhr:change_item:free_schedule','Flextime');
uis.lang_en('#mob:vhr:change_item:lunch','Lunch break');
uis.lang_en('#mob:vhr:change_item:lunch_end','Lunch end');
uis.lang_en('#mob:vhr:change_item:lunch_start','Lunch start');
uis.lang_en('#mob:vhr:change_item:not_specified','Not specified');
uis.lang_en('#mob:vhr:change_item:remove','Delete');
uis.lang_en('#mob:vhr:change_item:schedule','Work schedule');
uis.lang_en('#mob:vhr:change_item:specify','Specify');
uis.lang_en('#mob:vhr:change_item:time_end','Time end');
uis.lang_en('#mob:vhr:change_item:time_start','Time start');
uis.lang_en('#mob:vhr:change_item:working_hours_number','Working hours');
uis.lang_en('#mob:vhr:dashboard_mark:card_title','Track');
uis.lang_en('#mob:vhr:dashboard_mark:check-in','Track');
uis.lang_en('#mob:vhr:dashboard_mark:input','Check in');
uis.lang_en('#mob:vhr:dashboard_mark:output','Check out');
uis.lang_en('#mob:vhr:face_registered_screen:face_registered','Face registered');
uis.lang_en('#mob:vhr:face_registered_screen:finish','Complete');
uis.lang_en('#mob:vhr:head:my_day','My day');
uis.lang_en('#mob:vhr:head:settings','More');
uis.lang_en('#mob:vhr:head:subordinate','Subordinates');
uis.lang_en('#mob:vhr:head:toolbar_title','Main');
uis.lang_en('#mob:vhr:kpi_category:calculation_type','Calculation type');
uis.lang_en('#mob:vhr:kpi_category:plan_type_e','Additional measures');
uis.lang_en('#mob:vhr:kpi_category:plan_type_m','Main measures');
uis.lang_en('#mob:vhr:kpi_category:status','Status');
uis.lang_en('#mob:vhr:kpi_category:weight','Weight');
uis.lang_en('#mob:vhr:kpi_part_add_edit:accept','Accept');
uis.lang_en('#mob:vhr:kpi_part_add_edit:add','New grade');
uis.lang_en('#mob:vhr:kpi_part_add_edit:comment','Note');
uis.lang_en('#mob:vhr:kpi_part_add_edit:error_empty_field','Required field');
uis.lang_en('#mob:vhr:kpi_part_add_edit:fact','Fact');
uis.lang_en('#mob:vhr:kpi_plan_detailed:add','Add');
uis.lang_en('#mob:vhr:kpi_plan_detailed:added','Added by');
uis.lang_en('#mob:vhr:kpi_plan_detailed:are_you_sure_delete','Do you really want to delete grade?');
uis.lang_en('#mob:vhr:kpi_plan_detailed:at_time','at');
uis.lang_en('#mob:vhr:kpi_plan_detailed:calculation_type','Calculation type:');
uis.lang_en('#mob:vhr:kpi_plan_detailed:close','Close');
uis.lang_en('#mob:vhr:kpi_plan_detailed:delete','Delete');
uis.lang_en('#mob:vhr:kpi_plan_detailed:edit','Edit');
uis.lang_en('#mob:vhr:kpi_plan_detailed:no','No');
uis.lang_en('#mob:vhr:kpi_plan_detailed:weight','Weight:');
uis.lang_en('#mob:vhr:kpi_plan_detailed:yes','Yes');
uis.lang_en('#mob:vhr:kpi_plan_detailed:you','You');
uis.lang_en('#mob:vhr:mark_barcode:close','Close');
uis.lang_en('#mob:vhr:mark_barcode:qr_message','In order to track, take QR-code to the tablet with the Timepad.');
uis.lang_en('#mob:vhr:mark_barcode:title','Track by QR');
uis.lang_en('#mob:vhr:mark_face_bean:check_emotion_close_left_eye','Close left eye');
uis.lang_en('#mob:vhr:mark_face_bean:check_emotion_close_right_eye','Close right eye');
uis.lang_en('#mob:vhr:mark_face_bean:check_emotion_smile','Smile');
uis.lang_en('#mob:vhr:mark_face_bean:face_not_recognized','Face not detected');
uis.lang_en('#mob:vhr:mark_face_bean:face_recognized','Face detected');
uis.lang_en('#mob:vhr:mark_face_bean:unable_generate_emotion','Cannot generate emotion');
uis.lang_en('#mob:vhr:mark_location:location_found','Coordinates found, accuracy %1s m');
uis.lang_en('#mob:vhr:mark_location:location_not_match','Location does not match');
uis.lang_en('#mob:vhr:mark_location:please_wait','Please, wait');
uis.lang_en('#mob:vhr:mark_location:skip','Skip');
uis.lang_en('#mob:vhr:mark_location:touch_id_description','Use Touch-ID to identify the user to the current account. Put your finger on the sensor');
uis.lang_en('#mob:vhr:mark_note:cancel','Cancel');
uis.lang_en('#mob:vhr:mark_note:face','Photo');
uis.lang_en('#mob:vhr:mark_note:face_found','Face detected');
uis.lang_en('#mob:vhr:mark_note:field_required','Track comments are required for filling');
uis.lang_en('#mob:vhr:mark_note:location','Location');
uis.lang_en('#mob:vhr:mark_note:location_accuracy','Accuracy: %1s m');
uis.lang_en('#mob:vhr:mark_note:location_not_found','Location does not match');
uis.lang_en('#mob:vhr:mark_note:not_valid','Face not detected');
uis.lang_en('#mob:vhr:mark_note:note_hint_message','Track comment...');
uis.lang_en('#mob:vhr:mark_note:send','Send');
uis.lang_en('#mob:vhr:mark_note:toolbar_title','About track');
uis.lang_en('#mob:vhr:mark_note:track_note','Note');
uis.lang_en('#mob:vhr:my_day:no_schedule','No schedule');
uis.lang_en('#mob:vhr:my_day:relax','Relax and enjoy your day');
uis.lang_en('#mob:vhr:my_day:timesheet','Calendar');
uis.lang_en('#mob:vhr:my_day:toolbar_title','Main');
uis.lang_en('#mob:vhr:my_day:weekend','Rest day');
uis.lang_en('#mob:vhr:my_day:work_day','Working day %1s: %2s');
uis.lang_en('#mob:vhr:my_kpi:calculation_type','Calculation type');
uis.lang_en('#mob:vhr:my_kpi:calendar','Calendar');
uis.lang_en('#mob:vhr:my_kpi:toolbar_title','My KPI');
uis.lang_en('#mob:vhr:my_kpi:weight','Weight');
uis.lang_en('#mob:vhr:my_requests:back','Back');
uis.lang_en('#mob:vhr:my_requests:my_requests','Request for absence');
uis.lang_en('#mob:vhr:notify_mark_setting:after','After');
uis.lang_en('#mob:vhr:notify_mark_setting:before','Before');
uis.lang_en('#mob:vhr:notify_mark_setting:begin_time_notification','Work start time');
uis.lang_en('#mob:vhr:notify_mark_setting:enable_text','Notifications about tracking of Start of the working day, End of the working day');
uis.lang_en('#mob:vhr:notify_mark_setting:end_time_notification','Work end time');
uis.lang_en('#mob:vhr:notify_mark_setting:minute','%1s min');
uis.lang_en('#mob:vhr:notify_mark_setting:toolbar_title','Notifications about tracking');
uis.lang_en('#mob:vhr:profile:account_title','Account');
uis.lang_en('#mob:vhr:profile:change_account','Change account');
uis.lang_en('#mob:vhr:profile:change_filial','Change organization');
uis.lang_en('#mob:vhr:profile:change_password','Change PIN');
uis.lang_en('#mob:vhr:profile:current_filial','Current organization');
uis.lang_en('#mob:vhr:profile:enter_with_touch_id','Log in with Touch-ID');
uis.lang_en('#mob:vhr:profile:my_kpi','My KPI');
uis.lang_en('#mob:vhr:profile:notify_mark','Start and end work time notifications');
uis.lang_en('#mob:vhr:profile:remove_password','Delete PIN');
uis.lang_en('#mob:vhr:profile:security_title','Security');
uis.lang_en('#mob:vhr:profile:set_password','Set PIN');
uis.lang_en('#mob:vhr:profile:settings','Settings');
uis.lang_en('#mob:vhr:profile:show_direct_subordinates','Display only direct subordinates');
uis.lang_en('#mob:vhr:profile:subordinates_kpi','Subordinates KPI');
uis.lang_en('#mob:vhr:profile:toolbar_title','More');
uis.lang_en('#mob:vhr:profile_screen:accounts','Accounts');
uis.lang_en('#mob:vhr:profile_screen:accounts_and_ids','Accounts and IDs');
uis.lang_en('#mob:vhr:profile_screen:back','Back');
uis.lang_en('#mob:vhr:profile_screen:camera','Camera');
uis.lang_en('#mob:vhr:profile_screen:city','city');
uis.lang_en('#mob:vhr:profile_screen:contacts','Contacts');
uis.lang_en('#mob:vhr:profile_screen:copied','Copied to clipboard');
uis.lang_en('#mob:vhr:profile_screen:date_of_birth','Birth date');
uis.lang_en('#mob:vhr:profile_screen:email','email');
uis.lang_en('#mob:vhr:profile_screen:exit_account_message','Do you really want to exit from account?');
uis.lang_en('#mob:vhr:profile_screen:exit_account_no','No');
uis.lang_en('#mob:vhr:profile_screen:exit_account_yes','Yes');
uis.lang_en('#mob:vhr:profile_screen:face','face');
uis.lang_en('#mob:vhr:profile_screen:face_not_registered','Not registered');
uis.lang_en('#mob:vhr:profile_screen:face_registered','Registered');
uis.lang_en('#mob:vhr:profile_screen:female','Female');
uis.lang_en('#mob:vhr:profile_screen:gallery','Gallery');
uis.lang_en('#mob:vhr:profile_screen:gender','gender');
uis.lang_en('#mob:vhr:profile_screen:image_source_question','Photo from?');
uis.lang_en('#mob:vhr:profile_screen:inn','TIN');
uis.lang_en('#mob:vhr:profile_screen:inps','IPSA');
uis.lang_en('#mob:vhr:profile_screen:leave','Exit');
uis.lang_en('#mob:vhr:profile_screen:male','Male');
uis.lang_en('#mob:vhr:profile_screen:manager','manager');
uis.lang_en('#mob:vhr:profile_screen:no_image_selected','Photo not selected');
uis.lang_en('#mob:vhr:profile_screen:no_info','Not specified');
uis.lang_en('#mob:vhr:profile_screen:personnel_number','persNo');
uis.lang_en('#mob:vhr:profile_screen:phone_number','phone');
uis.lang_en('#mob:vhr:profile_screen:pinfl','IPIN');
uis.lang_en('#mob:vhr:profile_screen:profile','Profile');
uis.lang_en('#mob:vhr:profile_screen:region','Region');
uis.lang_en('#mob:vhr:profile_screen:registration_address','registration address');
uis.lang_en('#mob:vhr:profile_screen:residence_address','residence address');
uis.lang_en('#mob:vhr:profile_screen:warning','Warning');
uis.lang_en('#mob:vhr:request_component:change_schedule','Change schedule');
uis.lang_en('#mob:vhr:request_component:for_today','For today');
uis.lang_en('#mob:vhr:request_component:leave','Absence');
uis.lang_en('#mob:vhr:request_component:requests','Requests for absence');
uis.lang_en('#mob:vhr:request_component:show_all','All');
uis.lang_en('#mob:vhr:request_component:swap','Day swap');
uis.lang_en('#mob:vhr:request_component:this_month','This month');
uis.lang_en('#mob:vhr:request_details:approve','Accept');
uis.lang_en('#mob:vhr:request_details:approved','Approved');
uis.lang_en('#mob:vhr:request_details:back','Back');
uis.lang_en('#mob:vhr:request_details:change','Change schedule');
uis.lang_en('#mob:vhr:request_details:comment','Comment');
uis.lang_en('#mob:vhr:request_details:comment_text','Text');
uis.lang_en('#mob:vhr:request_details:date','data');
uis.lang_en('#mob:vhr:request_details:dates','dates');
uis.lang_en('#mob:vhr:request_details:delete','Delete');
uis.lang_en('#mob:vhr:request_details:denied','Disapproved');
uis.lang_en('#mob:vhr:request_details:deny','Disapprove');
uis.lang_en('#mob:vhr:request_details:edit','Edit');
uis.lang_en('#mob:vhr:request_details:leave','Request for absence');
uis.lang_en('#mob:vhr:request_details:leave_reason','absence reason');
uis.lang_en('#mob:vhr:request_details:leave_type','absence type');
uis.lang_en('#mob:vhr:request_details:manager_approval','Manager approval');
uis.lang_en('#mob:vhr:request_details:manager_note','Manager note');
uis.lang_en('#mob:vhr:request_details:note','Note');
uis.lang_en('#mob:vhr:request_details:replaced_day','Replacement day');
uis.lang_en('#mob:vhr:request_details:replacing_day','Replacing day');
uis.lang_en('#mob:vhr:request_details:request_state','request status');
uis.lang_en('#mob:vhr:request_details:reset','Reset');
uis.lang_en('#mob:vhr:request_details:schedule_change','Change schedule');
uis.lang_en('#mob:vhr:request_details:subordinate_name','Employee');
uis.lang_en('#mob:vhr:request_details:swap','day swap');
uis.lang_en('#mob:vhr:request_details:time','time');
uis.lang_en('#mob:vhr:request_details:waiting','Pending');
uis.lang_en('#mob:vhr:request_list:april','April');
uis.lang_en('#mob:vhr:request_list:august','August');
uis.lang_en('#mob:vhr:request_list:december','December');
uis.lang_en('#mob:vhr:request_list:february','February');
uis.lang_en('#mob:vhr:request_list:january','January');
uis.lang_en('#mob:vhr:request_list:july','July');
uis.lang_en('#mob:vhr:request_list:june','June');
uis.lang_en('#mob:vhr:request_list:march','March');
uis.lang_en('#mob:vhr:request_list:may','May');
uis.lang_en('#mob:vhr:request_list:no_requests','No requests');
uis.lang_en('#mob:vhr:request_list:november','November');
uis.lang_en('#mob:vhr:request_list:october','October');
uis.lang_en('#mob:vhr:request_list:september','September');
uis.lang_en('#mob:vhr:requests:approved','Approved');
uis.lang_en('#mob:vhr:requests:back','Back');
uis.lang_en('#mob:vhr:requests:cancel','Cancel');
uis.lang_en('#mob:vhr:requests:change','Change schedule');
uis.lang_en('#mob:vhr:requests:comment','Comment');
uis.lang_en('#mob:vhr:requests:comment_text','Text');
uis.lang_en('#mob:vhr:requests:date','data');
uis.lang_en('#mob:vhr:requests:dates','dates');
uis.lang_en('#mob:vhr:requests:day_end','end day');
uis.lang_en('#mob:vhr:requests:day_start','start day');
uis.lang_en('#mob:vhr:requests:delete','Delete');
uis.lang_en('#mob:vhr:requests:denied','Disapproved');
uis.lang_en('#mob:vhr:requests:edit','Edit');
uis.lang_en('#mob:vhr:requests:free_schedule','Flextime');
uis.lang_en('#mob:vhr:requests:leave','Request for absence');
uis.lang_en('#mob:vhr:requests:leave_reason','Absence reason');
uis.lang_en('#mob:vhr:requests:leave_type','Absence type');
uis.lang_en('#mob:vhr:requests:leave_type_day','Day');
uis.lang_en('#mob:vhr:requests:leave_type_days','Several days');
uis.lang_en('#mob:vhr:requests:leave_type_hourly','By hours');
uis.lang_en('#mob:vhr:requests:lunch','Lunch break');
uis.lang_en('#mob:vhr:requests:lunch_end','Lunch end');
uis.lang_en('#mob:vhr:requests:lunch_start','Lunch start');
uis.lang_en('#mob:vhr:requests:manager_approval','Manager approval');
uis.lang_en('#mob:vhr:requests:no_choice','Not selected');
uis.lang_en('#mob:vhr:requests:not_specified','Not specified');
uis.lang_en('#mob:vhr:requests:replaced_day','Replacement day');
uis.lang_en('#mob:vhr:requests:replacing_day','Replacing day');
uis.lang_en('#mob:vhr:requests:request_state','request status');
uis.lang_en('#mob:vhr:requests:schedule_change','Change schedule');
uis.lang_en('#mob:vhr:requests:send','Send');
uis.lang_en('#mob:vhr:requests:specify','Specify');
uis.lang_en('#mob:vhr:requests:swap','Day swap');
uis.lang_en('#mob:vhr:requests:time','time');
uis.lang_en('#mob:vhr:requests:time_end','End time');
uis.lang_en('#mob:vhr:requests:time_start','Start time');
uis.lang_en('#mob:vhr:requests:waiting','Pending');
uis.lang_en('#mob:vhr:requests:working_hours_number','Working hours');
uis.lang_en('#mob:vhr:setting:account_btn','Accounts');
uis.lang_en('#mob:vhr:setting:back','Back');
uis.lang_en('#mob:vhr:setting:background','App background');
uis.lang_en('#mob:vhr:setting:components','Components');
uis.lang_en('#mob:vhr:setting:dark','Dark');
uis.lang_en('#mob:vhr:setting:default_system','System (default)');
uis.lang_en('#mob:vhr:setting:for_developer','For developers');
uis.lang_en('#mob:vhr:setting:interface','Interface');
uis.lang_en('#mob:vhr:setting:lang','language');
uis.lang_en('#mob:vhr:setting:light','Light');
uis.lang_en('#mob:vhr:setting:load_vector','Face load %1s/%2s');
uis.lang_en('#mob:vhr:setting:load_vector_error','Face load %1s/%2s, %3s');
uis.lang_en('#mob:vhr:setting:main_page','Start-up screen');
uis.lang_en('#mob:vhr:setting:please_wait','Please, wait');
uis.lang_en('#mob:vhr:setting:reload_btn','Try again');
uis.lang_en('#mob:vhr:setting:setting_downloads','Settings loading');
uis.lang_en('#mob:vhr:setting:theme','theme');
uis.lang_en('#mob:vhr:setting:toolbar_title','Settings');
uis.lang_en('#mob:vhr:setting_options:back','Back');
uis.lang_en('#mob:vhr:setting_options:dark','Dark');
uis.lang_en('#mob:vhr:setting_options:default_system','System (default)');
uis.lang_en('#mob:vhr:setting_options:light','Light');
uis.lang_en('#mob:vhr:setting_options:theme','theme');
uis.lang_en('#mob:vhr:setting_options:toolbar_title','Options');
uis.lang_en('#mob:vhr:subordinate:show_all','All');
uis.lang_en('#mob:vhr:subordinate:sub_show_all','All');
uis.lang_en('#mob:vhr:subordinate:subordinate_requests','Requests for absence');
uis.lang_en('#mob:vhr:subordinate:subordinates','Subordinates');
uis.lang_en('#mob:vhr:subordinate:toolbar_title','Subordinates');
uis.lang_en('#mob:vhr:subordinate_dialog:btn_close','Close');
uis.lang_en('#mob:vhr:subordinate_dialog:list_is_empty','Employee list is empty');
uis.lang_en('#mob:vhr:subordinate_dialog:search_hint','Search');
uis.lang_en('#mob:vhr:subordinate_dialog:toolbar_title','Employees');
uis.lang_en('#mob:vhr:subordinate_kpi:calendar','Calendar');
uis.lang_en('#mob:vhr:subordinate_kpi:search','Search');
uis.lang_en('#mob:vhr:subordinate_kpi:toolbar_title','Subordinates KPI');
uis.lang_en('#mob:vhr:subordinate_kpi_detailed:calculation_type','Calculation type');
uis.lang_en('#mob:vhr:subordinate_kpi_detailed:calendar','Calendar');
uis.lang_en('#mob:vhr:subordinate_kpi_detailed:toolbar_title','KPI');
uis.lang_en('#mob:vhr:subordinate_kpi_detailed:weight','Weight');
uis.lang_en('#mob:vhr:swap:add','Add');
uis.lang_en('#mob:vhr:swap:cancel','Cancel');
uis.lang_en('#mob:vhr:swap:comment','Comment');
uis.lang_en('#mob:vhr:swap:comment_text','Text');
uis.lang_en('#mob:vhr:swap:send','Send');
uis.lang_en('#mob:vhr:swap:toolbar_title','Day swap');
uis.lang_en('#mob:vhr:swap_item:not_specified','Not specified');
uis.lang_en('#mob:vhr:swap_item:remove','Delete');
uis.lang_en('#mob:vhr:swap_item:replaced_day','Replacement day');
uis.lang_en('#mob:vhr:swap_item:replacing_day','Replacing day');
uis.lang_en('#mob:vhr:swap_item:specify','Specify');
uis.lang_en('#mob:vhr:timesheet:april','April');
uis.lang_en('#mob:vhr:timesheet:at_work','At work');
uis.lang_en('#mob:vhr:timesheet:august','August');
uis.lang_en('#mob:vhr:timesheet:back_pressed','Back');
uis.lang_en('#mob:vhr:timesheet:december','December');
uis.lang_en('#mob:vhr:timesheet:employee_change','Change working day');
uis.lang_en('#mob:vhr:timesheet:february','February');
uis.lang_en('#mob:vhr:timesheet:has_leave_full_day','Whole day absence');
uis.lang_en('#mob:vhr:timesheet:january','January');
uis.lang_en('#mob:vhr:timesheet:july','July');
uis.lang_en('#mob:vhr:timesheet:june','June');
uis.lang_en('#mob:vhr:timesheet:march','March');
uis.lang_en('#mob:vhr:timesheet:may','May');
uis.lang_en('#mob:vhr:timesheet:november','November');
uis.lang_en('#mob:vhr:timesheet:october','October');
uis.lang_en('#mob:vhr:timesheet:schedule','Schedule');
uis.lang_en('#mob:vhr:timesheet:september','September');
uis.lang_en('#mob:vhr:timesheet:toolbar_title','Calendar');
uis.lang_en('#mob:vhr:timesheet:track_title','Tracking');
uis.lang_en('#mob:vhr:timesheet:weekend','Rest day');
uis.lang_en('#mob:vhr:timesheet:work_pass','Absence');
uis.lang_en('#mob:vhr:timesheet_employee_info:back','Back');
uis.lang_en('#mob:vhr:timesheet_employee_info:calendar','Calendar');
uis.lang_en('#mob:vhr:timesheet_employee_info:employee_statistic','Employee profile');
uis.lang_en('#mob:vhr:timesheet_employee_info:schedule_requests','Requests');
uis.lang_en('#mob:vhr:timesheet_employee_info:show_all','All');
uis.lang_en('#mob:vhr:timesheet_employee_info:track_title','Tracking');
uis.lang_en('#mob:vhr:timesheet_inout:input','Check in');
uis.lang_en('#mob:vhr:timesheet_inout:output','Check out');
uis.lang_en('#mob:vhr:timesheet_schedule:change_change','Change schedule');
uis.lang_en('#mob:vhr:timesheet_schedule:change_swap','Change days');
uis.lang_en('#mob:vhr:timesheet_schedule:dinner','Break');
uis.lang_en('#mob:vhr:timesheet_schedule:leave','Absence');
uis.lang_en('#mob:vhr:timesheet_schedule:leave_full_day','Whole day absence');
uis.lang_en('#mob:vhr:timesheet_schedule:schedule','Schedule');
uis.lang_en('#mob:vhr:timesheet_schedule:work_day','Working day');
uis.lang_en('#mob:vhr:timesheet_statistic:day_result_title','Day statistics');
uis.lang_en('#mob:vhr:timesheet_statistic:freetime','Flextime');
uis.lang_en('#mob:vhr:timesheet_statistic:intime','On time');
uis.lang_en('#mob:vhr:timesheet_statistic:not_worked','Not worked');
uis.lang_en('#mob:vhr:timesheet_statistic:overtime','Overtime pay');
uis.lang_en('#mob:vhr:timesheet_statistic:plan_time','By plan');
uis.lang_en('#mob:vhr:timesheet_statistic:toolbar_title','Day totals');
uis.lang_en('#mob:vhr:timesheet_tracking:more_tracks','All');
uis.lang_en('#mob:vhr:today_attendance:back','Back');
uis.lang_en('#mob:vhr:today_attendance:calendar','Calendar');
uis.lang_en('#mob:vhr:today_attendance:close','Close');
uis.lang_en('#mob:vhr:today_attendance:filter','Filter');
uis.lang_en('#mob:vhr:today_attendance:more_info','Details');
uis.lang_en('#mob:vhr:today_attendance:sort','Sort');
uis.lang_en('#mob:vhr:today_attendance:sort_full','Sort');
uis.lang_en('#mob:vhr:today_attendance:visits','Attendace');
uis.lang_en('#mob:vhr:today_attendance_filter_dialog:all','All');
uis.lang_en('#mob:vhr:today_attendance_filter_dialog:close','Close');
uis.lang_en('#mob:vhr:today_attendance_filter_dialog:filter','Filter');
uis.lang_en('#mob:vhr:today_attendance_filter_dialog:free_day','Rest day');
uis.lang_en('#mob:vhr:today_attendance_filter_dialog:intime','On time');
uis.lang_en('#mob:vhr:today_attendance_filter_dialog:late','Late');
uis.lang_en('#mob:vhr:today_attendance_filter_dialog:no_schedule','No schedule');
uis.lang_en('#mob:vhr:today_attendance_filter_dialog:not_begin','Not working time');
uis.lang_en('#mob:vhr:today_attendance_filter_dialog:not_come','Absent');
uis.lang_en('#mob:vhr:today_attendance_filter_dialog:select','Accept');
uis.lang_en('#mob:vhr:today_attendance_filter_dialog:take_leave','Requested for absence');
uis.lang_en('#mob:vhr:today_timesheet:breaks','Break');
uis.lang_en('#mob:vhr:today_timesheet:input','Check in');
uis.lang_en('#mob:vhr:today_timesheet:output','Check out');
uis.lang_en('#mob:vhr:today_timesheet:weekend','Rest day');
uis.lang_en('#mob:vhr:today_timesheet:work_day','Work. day');
uis.lang_en('#mob:vhr:track_filter:cancel','Cancel');
uis.lang_en('#mob:vhr:track_filter:current_month','This month');
uis.lang_en('#mob:vhr:track_filter:filter','Filter');
uis.lang_en('#mob:vhr:track_filter:filter_tracks_title','Filter tracks');
uis.lang_en('#mob:vhr:track_filter:last30day','Last 30 days');
uis.lang_en('#mob:vhr:track_filter:last7day','Last 7 days');
uis.lang_en('#mob:vhr:track_filter:last_month','Last month');
uis.lang_en('#mob:vhr:track_filter:today','Today');
uis.lang_en('#mob:vhr:track_filter:yesterday','Yesterday');
uis.lang_en('#mob:vhr:track_info:back','Back');
uis.lang_en('#mob:vhr:track_info:location','Coordinates');
uis.lang_en('#mob:vhr:track_info:location_accuracy','Accuracy: %1s m');
uis.lang_en('#mob:vhr:track_info:not_valid','Invalid');
uis.lang_en('#mob:vhr:track_info:toolbar_title','Track (%1s)');
uis.lang_en('#mob:vhr:track_info:track_location','Location');
uis.lang_en('#mob:vhr:track_info:track_note','Note');
uis.lang_en('#mob:vhr:track_info:track_photo','Photo');
uis.lang_en('#mob:vhr:track_info:track_time','Time');
uis.lang_en('#mob:vhr:track_info:tracking_type','Tracking type');
uis.lang_en('#mob:vhr:track_widget:not_valid','Invalid');
uis.lang_en('#mob:vhr:tracking:all_tracks_title','All tracks');
uis.lang_en('#mob:vhr:tracking:check-in','Track');
uis.lang_en('#mob:vhr:tracking:employee_close_btn','Close');
uis.lang_en('#mob:vhr:tracking:employee_list_is_empty','Employee list is empty');
uis.lang_en('#mob:vhr:tracking:employee_list_title','Subordinate list');
uis.lang_en('#mob:vhr:tracking:employee_select_btn','Select');
uis.lang_en('#mob:vhr:tracking:employee_title','Employees');
uis.lang_en('#mob:vhr:tracking:employee_tracks_title','Employee tracks');
uis.lang_en('#mob:vhr:tracking:filter_title','Filter');
uis.lang_en('#mob:vhr:tracking:input','Check in');
uis.lang_en('#mob:vhr:tracking:more_tracks','All');
uis.lang_en('#mob:vhr:tracking:output','Check out');
uis.lang_en('#mob:vhr:tracking:search_hint','Search');
uis.lang_en('#mob:vhr:tracking:track_at_date','%1s on %2s');
uis.lang_en('#mob:vhr:tracking:track_input','Check in');
uis.lang_en('#mob:vhr:tracking:track_is_empty','Tracking list is empty');
uis.lang_en('#mob:vhr:tracking:track_list_is_empty','Tracking list is empty');
uis.lang_en('#mob:vhr:tracking:track_location','Location');
uis.lang_en('#mob:vhr:tracking:track_mark','Track');
uis.lang_en('#mob:vhr:tracking:track_not_valid','Invalid');
uis.lang_en('#mob:vhr:tracking:track_note','Note');
uis.lang_en('#mob:vhr:tracking:track_output','Check out');
uis.lang_en('#mob:vhr:tracking:track_time','Time');
uis.lang_en('#mob:vhr:tracking:track_title','Tracking');
uis.lang_en('#mob:vhr:tracking:track_today','Today at %1s');
uis.lang_en('#mob:vhr:tracking:tracking_type','Tracking type');
uis.lang_en('#mob:vhr:tracking_list:all_tracks_title','All tracks');
uis.lang_en('#mob:vhr:tracking_list:back','Back');
uis.lang_en('#mob:vhr:tracking_list:employee','Subordinates');
uis.lang_en('#mob:vhr:tracking_list:employee_tracks_title','Employee tracks');
uis.lang_en('#mob:vhr:tracking_list:filter','Filter');
uis.lang_en('#mob:vhr:tracking_list:track_list_is_empty','Tracking list is empty');
commit;
end;
/
