set define off
prompt TABLE RECORD TRANSLATE
begin
uis.table_record_translate('HPD_JOURNAL_TYPES','VHR:HPD:1','NAME','en','Hiring');
uis.table_record_translate('HPD_JOURNAL_TYPES','VHR:HPD:2','NAME','en','Massive Hiring');
uis.table_record_translate('HPD_JOURNAL_TYPES','VHR:HPD:3','NAME','en','HR Transfer');
uis.table_record_translate('HPD_JOURNAL_TYPES','VHR:HPD:4','NAME','en','Massive HR Transfer');
uis.table_record_translate('HPD_JOURNAL_TYPES','VHR:HPD:5','NAME','en','Dismissal');
uis.table_record_translate('HPD_JOURNAL_TYPES','VHR:HPD:6','NAME','en','Massive Dismissal');
uis.table_record_translate('HPD_JOURNAL_TYPES','VHR:HPD:7','NAME','en','Salary Change');
uis.table_record_translate('HPD_JOURNAL_TYPES','VHR:HPD:8','NAME','en','Massive  Work Schedule Change');
uis.table_record_translate('HPD_JOURNAL_TYPES','VHR:HPD:9','NAME','en','Sick Note');
uis.table_record_translate('HPD_JOURNAL_TYPES','VHR:HPD:10','NAME','en','Business Trip');
uis.table_record_translate('HPD_JOURNAL_TYPES','VHR:HPD:11','NAME','en','Vacation');
uis.table_record_translate('HPD_JOURNAL_TYPES','VHR:HPD:12','NAME','en','Rank Change');
uis.table_record_translate('HPD_JOURNAL_TYPES','VHR:HPD:13','NAME','en','Vacation Days Quantity');
uis.table_record_translate('HPD_JOURNAL_TYPES','VHR:HPD:14','NAME','en','Overtime');
uis.table_record_translate('HPD_JOURNAL_TYPES','VHR:HPD:15','NAME','en','Massive Salary Change');
uis.table_record_translate('HPD_JOURNAL_TYPES','VHR:HPD:16','NAME','en','Timesheet adjustment');
uis.table_record_translate('HPD_JOURNAL_TYPES','VHR:HPD:17','NAME','en','Changing qualifications by list');
uis.table_record_translate('HPD_JOURNAL_TYPES','VHR:HPD:18','NAME','en','Business trip list');
uis.table_record_translate('HPD_JOURNAL_TYPES','VHR:HPD:19','NAME','en','Acceptance for Civil contract');
uis.table_record_translate('HPD_JOURNAL_TYPES','VHR:HPD:20','NAME','en','Sick leave list');
uis.table_record_translate('HPR_BOOK_TYPES','VHR:1','NAME','en','Payroll');
uis.table_record_translate('HPR_BOOK_TYPES','VHR:2','NAME','en','Wage Payment (Sick Note)');
uis.table_record_translate('HPR_BOOK_TYPES','VHR:3','NAME','en','Wage Payment (Business Trip)');
uis.table_record_translate('HPR_BOOK_TYPES','VHR:4','NAME','en','Wage Payment (Vacation)');
uis.table_record_translate('HPR_BOOK_TYPES','VHR:5','NAME','en','Wage Payment (All types)');
uis.table_record_translate('HPR_OPER_GROUPS','VHR:1','NAME','en','Pay by the hour and extra payment');
uis.table_record_translate('HPR_OPER_GROUPS','VHR:2','NAME','en','Effectiveness Bonus');
uis.table_record_translate('HPR_OPER_GROUPS','VHR:3','NAME','en','Sick Note');
uis.table_record_translate('HPR_OPER_GROUPS','VHR:4','NAME','en','Business Trip');
uis.table_record_translate('HPR_OPER_GROUPS','VHR:5','NAME','en','Vacation');
uis.table_record_translate('HPR_OPER_GROUPS','VHR:6','NAME','en','Overtime Pay');
uis.table_record_translate('HPR_OPER_GROUPS','VHR:7','NAME','en','Fines for violation of discipline');
uis.table_record_translate('HPR_OPER_GROUPS','VHR:8','NAME','en','Penalty for inefficiency');
uis.table_record_translate('HPR_OPER_GROUPS','VHR:9','NAME','en','Pay by the hour and extra payment (no penalties)');
uis.table_record_translate('HREF_DOCUMENT_TYPES','VHR:1','NAME','en','Passport (default)');
uis.table_record_translate('HREF_FTES','VHR:1','NAME','en','Full Time');
uis.table_record_translate('HREF_FTES','VHR:2','NAME','en','Part Time');
uis.table_record_translate('HREF_FTES','VHR:3','NAME','en','Quarter Time');
uis.table_record_translate('HREF_INDICATORS','VHR:1','IDENTIFIER','en','Salary');
uis.table_record_translate('HREF_INDICATORS','VHR:1','NAME','en','Salary');
uis.table_record_translate('HREF_INDICATORS','VHR:1','SHORT_NAME','en','Salary');
uis.table_record_translate('HREF_INDICATORS','VHR:10','IDENTIFIER','en','WorkingTimeInHours');
uis.table_record_translate('HREF_INDICATORS','VHR:10','NAME','en','Working Time (in hours)');
uis.table_record_translate('HREF_INDICATORS','VHR:10','SHORT_NAME','en','Working Time (in hours)');
uis.table_record_translate('HREF_INDICATORS','VHR:11','IDENTIFIER','en','CoefficientSickLeaves');
uis.table_record_translate('HREF_INDICATORS','VHR:11','NAME','en','Sick Note Coefficient');
uis.table_record_translate('HREF_INDICATORS','VHR:11','SHORT_NAME','en','Coefficient (Sick leave)');
uis.table_record_translate('HREF_INDICATORS','VHR:12','IDENTIFIER','en','BusinessTripDaysQty');
uis.table_record_translate('HREF_INDICATORS','VHR:12','NAME','en','Business Trip Days Qty');
uis.table_record_translate('HREF_INDICATORS','VHR:12','SHORT_NAME','en','Bus. Trip Days Qty');
uis.table_record_translate('HREF_INDICATORS','VHR:13','IDENTIFIER','en','VacationDaysQty');
uis.table_record_translate('HREF_INDICATORS','VHR:13','NAME','en','Vacation Days Qty');
uis.table_record_translate('HREF_INDICATORS','VHR:13','SHORT_NAME','en','Vacation Days Qty');
uis.table_record_translate('HREF_INDICATORS','VHR:14','IDENTIFIER','en','MonthlyAverageWorkingDays');
uis.table_record_translate('HREF_INDICATORS','VHR:14','NAME','en','Monthly Average Working Days Qty');
uis.table_record_translate('HREF_INDICATORS','VHR:14','SHORT_NAME','en','Month. Avg. Working Days Qty');
uis.table_record_translate('HREF_INDICATORS','VHR:15','IDENTIFIER','en','SickLeaveDaysQty');
uis.table_record_translate('HREF_INDICATORS','VHR:15','NAME','en','Sick Leave Days Qty');
uis.table_record_translate('HREF_INDICATORS','VHR:15','SHORT_NAME','en','Sick Leave Days Qty');
uis.table_record_translate('HREF_INDICATORS','VHR:16','IDENTIFIER','en','AverageHourlySalary');
uis.table_record_translate('HREF_INDICATORS','VHR:16','NAME','en','Average Hourly Salary');
uis.table_record_translate('HREF_INDICATORS','VHR:16','SHORT_NAME','en','Avg. Hour. Salary');
uis.table_record_translate('HREF_INDICATORS','VHR:17','IDENTIFIER','en','OvertimeHours');
uis.table_record_translate('HREF_INDICATORS','VHR:17','NAME','en','Overtime Hours');
uis.table_record_translate('HREF_INDICATORS','VHR:17','SHORT_NAME','en','Overtime Hours');
uis.table_record_translate('HREF_INDICATORS','VHR:18','IDENTIFIER','en','OvertimeCoefficient');
uis.table_record_translate('HREF_INDICATORS','VHR:18','NAME','en','Overtime Coefficient');
uis.table_record_translate('HREF_INDICATORS','VHR:18','SHORT_NAME','en','Overtime Coef.');
uis.table_record_translate('HREF_INDICATORS','VHR:19','IDENTIFIER','en','FinesForLateness');
uis.table_record_translate('HREF_INDICATORS','VHR:19','NAME','en','Fine for Lateness');
uis.table_record_translate('HREF_INDICATORS','VHR:19','SHORT_NAME','en','Fine for Lateness');
uis.table_record_translate('HREF_INDICATORS','VHR:2','IDENTIFIER','en','PartTimeWorkRate');
uis.table_record_translate('HREF_INDICATORS','VHR:2','NAME','en','Part-time Work Rate');
uis.table_record_translate('HREF_INDICATORS','VHR:2','SHORT_NAME','en','Part-time Work Rate');
uis.table_record_translate('HREF_INDICATORS','VHR:20','IDENTIFIER','en','FineForEarlyLeaving');
uis.table_record_translate('HREF_INDICATORS','VHR:20','NAME','en','Fine for Early leaving');
uis.table_record_translate('HREF_INDICATORS','VHR:20','SHORT_NAME','en','Fine for Early leaving');
uis.table_record_translate('HREF_INDICATORS','VHR:21','IDENTIFIER','en','FineForAbsence');
uis.table_record_translate('HREF_INDICATORS','VHR:21','NAME','en','Fine for Absence');
uis.table_record_translate('HREF_INDICATORS','VHR:21','SHORT_NAME','en','Fine for Absence');
uis.table_record_translate('HREF_INDICATORS','VHR:22','IDENTIFIER','en','FineForDaySkip');
uis.table_record_translate('HREF_INDICATORS','VHR:22','NAME','en','Fine for Day skip');
uis.table_record_translate('HREF_INDICATORS','VHR:22','SHORT_NAME','en','Fine for Day skip');
uis.table_record_translate('HREF_INDICATORS','VHR:3','IDENTIFIER','en','DayRate');
uis.table_record_translate('HREF_INDICATORS','VHR:3','NAME','en','Day Rate');
uis.table_record_translate('HREF_INDICATORS','VHR:3','SHORT_NAME','en','Day Rate');
uis.table_record_translate('HREF_INDICATORS','VHR:4','IDENTIFIER','en','FactTimeInDays');
uis.table_record_translate('HREF_INDICATORS','VHR:4','NAME','en','Fact Time (in days)');
uis.table_record_translate('HREF_INDICATORS','VHR:4','SHORT_NAME','en','Fact Time (in days)');
uis.table_record_translate('HREF_INDICATORS','VHR:5','IDENTIFIER','en','HoursRate');
uis.table_record_translate('HREF_INDICATORS','VHR:5','NAME','en','Hours Rate');
uis.table_record_translate('HREF_INDICATORS','VHR:5','SHORT_NAME','en','Hours Rate');
uis.table_record_translate('HREF_INDICATORS','VHR:6','IDENTIFIER','en','FactTimeInHours');
uis.table_record_translate('HREF_INDICATORS','VHR:6','NAME','en','Fact Time (in hours)');
uis.table_record_translate('HREF_INDICATORS','VHR:6','SHORT_NAME','en','Fact Time (in hours)');
uis.table_record_translate('HREF_INDICATORS','VHR:7','IDENTIFIER','en','EffectivenessBonus');
uis.table_record_translate('HREF_INDICATORS','VHR:7','NAME','en','Effectiveness Bonus');
uis.table_record_translate('HREF_INDICATORS','VHR:7','SHORT_NAME','en','Effect. Bonus');
uis.table_record_translate('HREF_INDICATORS','VHR:8','IDENTIFIER','en','EffectivenessExtraBonus');
uis.table_record_translate('HREF_INDICATORS','VHR:8','NAME','en','Effectiveness Extra Bonus');
uis.table_record_translate('HREF_INDICATORS','VHR:8','SHORT_NAME','en','Effect. Extra Bonus');
uis.table_record_translate('HREF_INDICATORS','VHR:9','IDENTIFIER','en','WorkingTimeInDays');
uis.table_record_translate('HREF_INDICATORS','VHR:9','NAME','en','Working Time (in days)');
uis.table_record_translate('HREF_INDICATORS','VHR:9','SHORT_NAME','en','Working Time (in days)');
uis.table_record_translate('HREF_INDICATORS','VHR:23','IDENTIFIER','en','PenaltyForInefficiency');
uis.table_record_translate('HREF_INDICATORS','VHR:23','NAME','en','Penalty for inefficiency');
uis.table_record_translate('HREF_INDICATORS','VHR:23','SHORT_NAME','en','Penalty for inefficiency');
uis.table_record_translate('HREF_INDICATORS','VHR:24','IDENTIFIER','en','AddPenaltyForInefficiency');
uis.table_record_translate('HREF_INDICATORS','VHR:24','NAME','en','Additional penalty for inefficiency');
uis.table_record_translate('HREF_INDICATORS','VHR:24','SHORT_NAME','en','Additional penalty for inefficiency');
uis.table_record_translate('HREF_INDICATORS','VHR:25','IDENTIFIER','en','PenaltyForMissingMark');
uis.table_record_translate('HREF_INDICATORS','VHR:25','NAME','en','Penalty for missing a mark');
uis.table_record_translate('HREF_INDICATORS','VHR:25','SHORT_NAME','en','Penalty for missing a mark');
uis.table_record_translate('HREF_INDICATORS','VHR:26','IDENTIFIER','en','AdditionalNightTime');
uis.table_record_translate('HREF_INDICATORS','VHR:26','NAME','en','Additional night time');
uis.table_record_translate('HREF_INDICATORS','VHR:26','SHORT_NAME','en','Additional night time');
uis.table_record_translate('HREF_INDICATORS','VHR:27','IDENTIFIER','en','WeightedTurnout');
uis.table_record_translate('HREF_INDICATORS','VHR:27','NAME','en','Weighted turnout');
uis.table_record_translate('HREF_INDICATORS','VHR:27','SHORT_NAME','en','Weighted turnout');
uis.table_record_translate('HREF_INDICATORS','VHR:28','IDENTIFIER','en','AvgMonthlyPerfBonus');
uis.table_record_translate('HREF_INDICATORS','VHR:28','NAME','en','Average monthly performance bonus');
uis.table_record_translate('HREF_INDICATORS','VHR:28','SHORT_NAME','en','Average monthly performance bonus');
uis.table_record_translate('HREF_INDICATORS','VHR:29','IDENTIFIER','en','AvgMonthlyAddPerfBonus');
uis.table_record_translate('HREF_INDICATORS','VHR:29','NAME','en','Average Monthly Additional Performance Bonus');
uis.table_record_translate('HREF_INDICATORS','VHR:29','SHORT_NAME','en','Average Monthly Additional Performance Bonus');
uis.table_record_translate('HTT_CALENDARS','VHR:1','NAME','en','Production Calendar');
uis.table_record_translate('HTT_REQUEST_KINDS','VHR:1','NAME','en','Sick Leave');
uis.table_record_translate('HTT_REQUEST_KINDS','VHR:2','NAME','en','Vacation');
uis.table_record_translate('HTT_REQUEST_KINDS','VHR:3','NAME','en','Business Trip');
uis.table_record_translate('HTT_REQUEST_KINDS','VHR:4','NAME','en','Time Off');
uis.table_record_translate('HTT_REQUEST_KINDS','VHR:5','NAME','en','Business Meeting');
uis.table_record_translate('HTT_SCHEDULES','VHR:1','NAME','en','Individual Work Schedule');
uis.table_record_translate('HTT_SCHEDULES','VHR:2','NAME','en','Individual Work Schedule for Positions');
uis.table_record_translate('HTT_TIME_KINDS','VHR:1','LETTER_CODE','en','T');
uis.table_record_translate('HTT_TIME_KINDS','VHR:1','NAME','en','Turnout');
uis.table_record_translate('HTT_TIME_KINDS','VHR:10','LETTER_CODE','en','BT');
uis.table_record_translate('HTT_TIME_KINDS','VHR:10','NAME','en','Business Trip');
uis.table_record_translate('HTT_TIME_KINDS','VHR:11','LETTER_CODE','en','V');
uis.table_record_translate('HTT_TIME_KINDS','VHR:11','NAME','en','Vacation');
uis.table_record_translate('HTT_TIME_KINDS','VHR:12','LETTER_CODE','en','OT');
uis.table_record_translate('HTT_TIME_KINDS','VHR:12','NAME','en','Overtime Pay');
uis.table_record_translate('HTT_TIME_KINDS','VHR:13','LETTER_CODE','en','BM');
uis.table_record_translate('HTT_TIME_KINDS','VHR:13','NAME','en','Business Meeting');
uis.table_record_translate('HTT_TIME_KINDS','VHR:14','LETTER_CODE','en','H');
uis.table_record_translate('HTT_TIME_KINDS','VHR:14','NAME','en','Holiday');
uis.table_record_translate('HTT_TIME_KINDS','VHR:15','LETTER_CODE','en','NW');
uis.table_record_translate('HTT_TIME_KINDS','VHR:15','NAME','en','Non-working Day');
uis.table_record_translate('HTT_TIME_KINDS','VHR:16','LETTER_CODE','en','BW');
uis.table_record_translate('HTT_TIME_KINDS','VHR:16','NAME','en','Before Work');
uis.table_record_translate('HTT_TIME_KINDS','VHR:17','LETTER_CODE','en','AW');
uis.table_record_translate('HTT_TIME_KINDS','VHR:17','NAME','en','After Work');
uis.table_record_translate('HTT_TIME_KINDS','VHR:18','LETTER_CODE','en','LT');
uis.table_record_translate('HTT_TIME_KINDS','VHR:18','NAME','en','Lunchtime');
uis.table_record_translate('HTT_TIME_KINDS','VHR:19','LETTER_CODE','en','FTP');
uis.table_record_translate('HTT_TIME_KINDS','VHR:19','NAME','en','Free Time in Plan');
uis.table_record_translate('HTT_TIME_KINDS','VHR:2','LETTER_CODE','en','L');
uis.table_record_translate('HTT_TIME_KINDS','VHR:2','NAME','en','Lateness');
uis.table_record_translate('HTT_TIME_KINDS','VHR:20','LETTER_CODE','en','TA');
uis.table_record_translate('HTT_TIME_KINDS','VHR:20','NAME','en','Turnout from Adjustment');
uis.table_record_translate('HTT_TIME_KINDS','VHR:21','LETTER_CODE','en','OA');
uis.table_record_translate('HTT_TIME_KINDS','VHR:21','NAME','en','Overtime from Adjustment');
uis.table_record_translate('HTT_TIME_KINDS','VHR:3','LETTER_CODE','en','EO');
uis.table_record_translate('HTT_TIME_KINDS','VHR:3','NAME','en','Early Check Out');
uis.table_record_translate('HTT_TIME_KINDS','VHR:4','LETTER_CODE','en','HTO');
uis.table_record_translate('HTT_TIME_KINDS','VHR:4','NAME','en','Hourly Compensatory Time Off');
uis.table_record_translate('HTT_TIME_KINDS','VHR:5','LETTER_CODE','en','R');
uis.table_record_translate('HTT_TIME_KINDS','VHR:5','NAME','en','Rest');
uis.table_record_translate('HTT_TIME_KINDS','VHR:6','LETTER_CODE','en','ABS');
uis.table_record_translate('HTT_TIME_KINDS','VHR:6','NAME','en','Absence');
uis.table_record_translate('HTT_TIME_KINDS','VHR:7','LETTER_CODE','en','FT');
uis.table_record_translate('HTT_TIME_KINDS','VHR:7','NAME','en','Free Time');
uis.table_record_translate('HTT_TIME_KINDS','VHR:8','LETTER_CODE','en','SL');
uis.table_record_translate('HTT_TIME_KINDS','VHR:8','NAME','en','Sick Leave');
uis.table_record_translate('HTT_TIME_KINDS','VHR:9','LETTER_CODE','en','TO');
uis.table_record_translate('HTT_TIME_KINDS','VHR:9','NAME','en','Time Off');
uis.table_record_translate('HTT_TIME_KINDS','VHR:22','LETTER_CODE','en','ADO');
uis.table_record_translate('HTT_TIME_KINDS','VHR:22','NAME','en','Additional day off');
uis.table_record_translate('MD_ROLES','VHR:1','NAME','en','HR Manager');
uis.table_record_translate('MD_ROLES','VHR:2','NAME','en','Manager');
uis.table_record_translate('MD_ROLES','VHR:3','NAME','en','Employee');
uis.table_record_translate('MD_ROLES','VHR:4','NAME','en','Accountant Officer');
uis.table_record_translate('MD_ROLES','VHR:6','NAME','en','Recruiter');
uis.table_record_translate('MPR_OPER_TYPES','VHR:1','NAME','en','Sick Leave');
uis.table_record_translate('MPR_OPER_TYPES','VHR:1','SHORT_NAME','en','Sick Leave');
uis.table_record_translate('MPR_OPER_TYPES','VHR:2','NAME','en','Business Trip');
uis.table_record_translate('MPR_OPER_TYPES','VHR:2','SHORT_NAME','en','Business Trip');
uis.table_record_translate('MPR_OPER_TYPES','VHR:3','NAME','en','Vacation');
uis.table_record_translate('MPR_OPER_TYPES','VHR:3','SHORT_NAME','en','Vacation');
uis.table_record_translate('MPR_OPER_TYPES','VHR:4','NAME','en','Hourly Pay');
uis.table_record_translate('MPR_OPER_TYPES','VHR:4','SHORT_NAME','en','Hourly');
uis.table_record_translate('MPR_OPER_TYPES','VHR:5','NAME','en','Daily Pay');
uis.table_record_translate('MPR_OPER_TYPES','VHR:5','SHORT_NAME','en','Daily');
uis.table_record_translate('MPR_OPER_TYPES','VHR:6','NAME','en','Monthly Pay');
uis.table_record_translate('MPR_OPER_TYPES','VHR:6','SHORT_NAME','en','Monthly');
uis.table_record_translate('MPR_OPER_TYPES','VHR:7','NAME','en','Overtime Pay');
uis.table_record_translate('MPR_OPER_TYPES','VHR:7','SHORT_NAME','en','Overtime');
uis.table_record_translate('MPR_OPER_TYPES','VHR:8','NAME','en','Monthly Pay (by fact hours)');
uis.table_record_translate('MPR_OPER_TYPES','VHR:8','SHORT_NAME','en','Monthly (by hours)');
uis.table_record_translate('MPR_OPER_TYPES','VHR:9','NAME','en','Fines for violation of discipline');
uis.table_record_translate('MPR_OPER_TYPES','VHR:9','SHORT_NAME','en','Fines for violation of discipline');
uis.table_record_translate('MPR_OPER_TYPES','VHR:10','NAME','en','Additional pay for night work');
uis.table_record_translate('MPR_OPER_TYPES','VHR:10','SHORT_NAME','en','Night work');
uis.table_record_translate('MPR_OPER_TYPES','VHR:11','NAME','en','Weighted wages (per hours worked)');
uis.table_record_translate('MPR_OPER_TYPES','VHR:11','SHORT_NAME','en','Weighted wages (per hours worked)');
uis.table_record_translate('MS_TASK_GROUPS','VHR:1','NAME','en','Plan');
commit;
end;
/
