prompt PATH TRANSLATE /vhr/hrm/robot
begin
uis.lang_uz('#a:/vhr/hrm/robot+add$add_accrual_oper_type','Hisoblash yaratish');
uis.lang_uz('#a:/vhr/hrm/robot+add$add_deduction_oper_type','Ushlab qolish yaratish');
uis.lang_uz('#a:/vhr/hrm/robot+add$add_job','Lavozim yaratish');
uis.lang_uz('#a:/vhr/hrm/robot+add$add_labor_function','Mehnat funksiyasi qo''shish');
uis.lang_uz('#a:/vhr/hrm/robot+add$add_rank','Daraja qo''shish');
uis.lang_uz('#a:/vhr/hrm/robot+add$add_robot_group','Ish o''rni guruhi yaratish');
uis.lang_uz('#a:/vhr/hrm/robot+add$add_schedule','Ish jadvali qo''shish');
uis.lang_uz('#a:/vhr/hrm/robot+add$add_wage_scale','Tarif setkasi qo''shish');
uis.lang_uz('#a:/vhr/hrm/robot+add$restrict_hidden_salary','Yashirin ish haqlarini ko''rish uchun ruxsat');
uis.lang_uz('#a:/vhr/hrm/robot+add$select_accrual_oper_type','Hisoblashni tanlash');
uis.lang_uz('#a:/vhr/hrm/robot+add$select_deduction_oper_type','Ushlab qolishni tanlash');
uis.lang_uz('#a:/vhr/hrm/robot+add$select_job','Lavozim tanlash');
uis.lang_uz('#a:/vhr/hrm/robot+add$select_job_group','Lavozim guruhini tanlash');
uis.lang_uz('#a:/vhr/hrm/robot+add$select_labor_function','Mehnat funksiyasini tanlash');
uis.lang_uz('#a:/vhr/hrm/robot+add$select_rank','Daraja tanlash');
uis.lang_uz('#a:/vhr/hrm/robot+add$select_robot_group','Ish o''rni guruhini tanlash');
uis.lang_uz('#a:/vhr/hrm/robot+add$select_schedule','Ish jadvali tanlash');
uis.lang_uz('#a:/vhr/hrm/robot+add$select_wage_scale','Tarif setkasini tanlash');
uis.lang_uz('#a:/vhr/hrm/robot+edit$add_accrual_oper_type','Hisoblash yaratish');
uis.lang_uz('#a:/vhr/hrm/robot+edit$add_deduction_oper_type','Ushlab qolish yaratish');
uis.lang_uz('#a:/vhr/hrm/robot+edit$add_job','Lavozim yaratish');
uis.lang_uz('#a:/vhr/hrm/robot+edit$add_labor_function','Mehnat funksiyasi qo''shish');
uis.lang_uz('#a:/vhr/hrm/robot+edit$add_rank','Daraja qo''shish');
uis.lang_uz('#a:/vhr/hrm/robot+edit$add_robot_group','Ish o''rni guruhi yaratish');
uis.lang_uz('#a:/vhr/hrm/robot+edit$add_schedule','Ish jadvali qo''shish');
uis.lang_uz('#a:/vhr/hrm/robot+edit$add_wage_scale','Tarif setkasi qo''shish');
uis.lang_uz('#a:/vhr/hrm/robot+edit$restrict_hidden_salary','Yashirin ish haqlarini ko''rish uchun ruxsat');
uis.lang_uz('#a:/vhr/hrm/robot+edit$select_accrual_oper_type','Hisoblashni tanlash');
uis.lang_uz('#a:/vhr/hrm/robot+edit$select_deduction_oper_type','Ushlab qolishni tanlash');
uis.lang_uz('#a:/vhr/hrm/robot+edit$select_job','Lavozim tanlash');
uis.lang_uz('#a:/vhr/hrm/robot+edit$select_job_group','Lavozim guruhini tanlash');
uis.lang_uz('#a:/vhr/hrm/robot+edit$select_labor_function','Mehnat funksiyasini tanlash');
uis.lang_uz('#a:/vhr/hrm/robot+edit$select_rank','Daraja tanlash');
uis.lang_uz('#a:/vhr/hrm/robot+edit$select_robot_group','Ish o''rni guruhini tanlash');
uis.lang_uz('#a:/vhr/hrm/robot+edit$select_schedule','Ish jadvali tanlash');
uis.lang_uz('#a:/vhr/hrm/robot+edit$select_wage_scale','Tarif setkasini tanlash');
uis.lang_uz('#f:/vhr/hrm/robot+add','Ish o''rni (yaratish)');
uis.lang_uz('#f:/vhr/hrm/robot+edit','Ish o''rni (tahrirlash)');
commit;
end;
/
