prompt PATH TRANSLATE /vhr/hpr/start/wage_sheet_list
begin
uis.lang_en('#a:/vhr/hpr/start/wage_sheet_list$add','Create');
uis.lang_en('#a:/vhr/hpr/start/wage_sheet_list$delete','Delete');
uis.lang_en('#a:/vhr/hpr/start/wage_sheet_list$edit','Edit');
uis.lang_en('#a:/vhr/hpr/start/wage_sheet_list$post','Post');
uis.lang_en('#a:/vhr/hpr/start/wage_sheet_list$run','Generate');
uis.lang_en('#a:/vhr/hpr/start/wage_sheet_list$unpost','Cancel');
uis.lang_en('#a:/vhr/hpr/start/wage_sheet_list+onetime$add','Create');
uis.lang_en('#a:/vhr/hpr/start/wage_sheet_list+onetime$delete','Delete');
uis.lang_en('#a:/vhr/hpr/start/wage_sheet_list+onetime$edit','Edit');
uis.lang_en('#a:/vhr/hpr/start/wage_sheet_list+onetime$post','Post');
uis.lang_en('#a:/vhr/hpr/start/wage_sheet_list+onetime$unpost','Unpost');
uis.lang_en('#f:/vhr/hpr/start/wage_sheet_list','Wage Calculation');
uis.lang_en('#f:/vhr/hpr/start/wage_sheet_list+onetime','One-time accruals');
uis.lang_en('ui-vhr315:accrual','Accrued');
uis.lang_en('ui-vhr315:accrual amount','Total');
uis.lang_en('ui-vhr315:accrued','Accrued');
uis.lang_en('ui-vhr315:amount','Amount');
uis.lang_en('ui-vhr315:break time','Break');
uis.lang_en('ui-vhr315:date','Date');
uis.lang_en('ui-vhr315:day','Day');
uis.lang_en('ui-vhr315:day_skip_amount','Skip day total');
uis.lang_en('ui-vhr315:days','Days');
uis.lang_en('ui-vhr315:deduction','Deducted');
uis.lang_en('ui-vhr315:division','Department');
uis.lang_en('ui-vhr315:division: $1','Department: $1');
uis.lang_en('ui-vhr315:division: $1{division_name}','Department: $1');
uis.lang_en('ui-vhr315:early','Early Check Out');
uis.lang_en('ui-vhr315:early amount','Early Check Out');
uis.lang_en('ui-vhr315:early fact','Early check out (time)');
uis.lang_en('ui-vhr315:fact','Fact');
uis.lang_en('ui-vhr315:fact time','Worked');
uis.lang_en('ui-vhr315:fte: $1{fte_name}','Employment Type: $1');
uis.lang_en('ui-vhr315:input','Check In');
uis.lang_en('ui-vhr315:job','Job');
uis.lang_en('ui-vhr315:job: $1{job_name}','Job: $1');
uis.lang_en('ui-vhr315:lack','Absence');
uis.lang_en('ui-vhr315:lack amount','Absence');
uis.lang_en('ui-vhr315:lack fact','Absence (time)');
uis.lang_en('ui-vhr315:late','Lateness');
uis.lang_en('ui-vhr315:late amount','Lateness');
uis.lang_en('ui-vhr315:late fact','Late check in (time)');
uis.lang_en('ui-vhr315:manager: $1{manager_name}','Manager: $1');
uis.lang_en('ui-vhr315:mark_skip_amount','Skip track');
uis.lang_en('ui-vhr315:month: $1','Month: $1');
uis.lang_en('ui-vhr315:monthly amount','Wage');
uis.lang_en('ui-vhr315:monthly days','Days');
uis.lang_en('ui-vhr315:monthly plan','Planned (monthly)');
uis.lang_en('ui-vhr315:monthly time','Hours');
uis.lang_en('ui-vhr315:nighttime','Night-time');
uis.lang_en('ui-vhr315:nighttime amount','Night-time Amount');
uis.lang_en('ui-vhr315:onetime accrual','One-time accrual');
uis.lang_en('ui-vhr315:onetime penalty','One-time deduction');
uis.lang_en('ui-vhr315:others ..','Others');
uis.lang_en('ui-vhr315:output','Check Out');
uis.lang_en('ui-vhr315:overtime','Overtime');
uis.lang_en('ui-vhr315:overtime amount','Overtime');
uis.lang_en('ui-vhr315:overtime fact','Overtime (time)');
uis.lang_en('ui-vhr315:part begin','Begin date');
uis.lang_en('ui-vhr315:penalty','Fine');
uis.lang_en('ui-vhr315:penalty amount','Total');
uis.lang_en('ui-vhr315:period kind: $1{period_kind} ($2{period_begin} - $3{period_end})','Period type: <b>$1</b> ($2 - $3)');
uis.lang_en('ui-vhr315:period plan','According to plan (period)');
uis.lang_en('ui-vhr315:period: from $1{begin_date} to $2{end_date}','Period: $1 - $2');
uis.lang_en('ui-vhr315:plan','Plan');
uis.lang_en('ui-vhr315:plan amount','Salary');
uis.lang_en('ui-vhr315:plan days','Days');
uis.lang_en('ui-vhr315:plan time','Hours');
uis.lang_en('ui-vhr315:rest day','Rest day');
uis.lang_en('ui-vhr315:rownum','№');
uis.lang_en('ui-vhr315:schedule','Work Schedule');
uis.lang_en('ui-vhr315:schedule: $1{schedule_name}','Work Schedule: $1');
uis.lang_en('ui-vhr315:sheet is not posted, sheet_id=$1','Wage calculation is not posted, ID=$1');
uis.lang_en('ui-vhr315:sheet_number: $1','Number: $1');
uis.lang_en('ui-vhr315:skip day','Skip days');
uis.lang_en('ui-vhr315:skip mark','Skip tracks');
uis.lang_en('ui-vhr315:staff name','Employee');
uis.lang_en('ui-vhr315:staff number','PersNo');
uis.lang_en('ui-vhr315:staff: $1{staff_name}','Employee: $1');
uis.lang_en('ui-vhr315:time','Time');
uis.lang_en('ui-vhr315:total','Total');
uis.lang_en('ui-vhr315:total amount','Total Amount');
uis.lang_en('ui-vhr315:total:','Total:');
uis.lang_en('ui-vhr315:type','Type');
uis.lang_en('ui-vhr315:wage','Salary');
uis.lang_en('ui-vhr315:wage amount','Salary');
uis.lang_en('ui-vhr315:wage days','Days');
uis.lang_en('ui-vhr315:wage time','Hours');
uis.lang_en('ui-vhr315:you can not see rows that contain jobs that you do not have access to','⚠️ You cannot see information on those employees whose access to wages is restricted for you');
commit;
end;
/
