prompt PATH TRANSLATE /vhr/hpd/hiring_import
begin
uis.lang_en('#a:/vhr/hpd/hiring_import$save_setting','Save Settings');
uis.lang_en('#f:/vhr/hpd/hiring_import','Hiring / Import');
uis.lang_en('ui-vhr126:$1{error message} with concluding term $2{concluding_term}','Error $1 in Concluding Term: $2');
uis.lang_en('ui-vhr126:$1{error message} with contract date $2{hiring_date}','Error $1 in Contract Date: $2');
uis.lang_en('ui-vhr126:$1{error message} with contract number $2{contract_number}','Error $1 in Contract Number: $2');
uis.lang_en('ui-vhr126:$1{error message} with division $2{division}','Error $1 in Department: $2');
uis.lang_en('ui-vhr126:$1{error message} with employee $2{employee}','Error $1 in Employee: $2');
uis.lang_en('ui-vhr126:$1{error message} with expiry date $2{expiry_date}','Error $1 in Contract Expiry Date: $2');
uis.lang_en('ui-vhr126:$1{error message} with fixed term $2{fixed_term}','Error $1 in Fixed-term Contract Reason: $2');
uis.lang_en('ui-vhr126:$1{error message} with fte $2{fte}','Error $1 in Full-time equivalent $2');
uis.lang_en('ui-vhr126:$1{error message} with hiring conditions $2{hiring_conditions}','Error $1 in Hiring Requirements: $2');
uis.lang_en('ui-vhr126:$1{error message} with hiring date $2{hiring_date}','Error $1 in Hiring Date: $2');
uis.lang_en('ui-vhr126:$1{error message} with indicator value $2{indicator_value}','Error $1 in Measure: $2');
uis.lang_en('ui-vhr126:$1{error message} with job $2{job}','Error $1 in Job: $2');
uis.lang_en('ui-vhr126:$1{error message} with oper type $2{oper_type_name}','Error $1 in Accrual: $2');
uis.lang_en('ui-vhr126:$1{error message} with other conditions $2{other_conditions}','Error $1 in Other Requirements: $2');
uis.lang_en('ui-vhr126:$1{error message} with rank $2{rank}','Error $1 in Rank: $2');
uis.lang_en('ui-vhr126:$1{error message} with representative basis $2{representative_basis}','Error $1 in Representative Reason: $2');
uis.lang_en('ui-vhr126:$1{error message} with robot $2{robot}','Error $1 in Position $2');
uis.lang_en('ui-vhr126:$1{error message} with schedule $2{schedule}','Error $1 in Work Schedule: $2');
uis.lang_en('ui-vhr126:$1{error message} with staff number $2{staff_number}','Error $1 in PersNo: $2');
uis.lang_en('ui-vhr126:$1{error message} with trial period $2{trial_period}','Error $1 in Initial Assessment Period: $2');
uis.lang_en('ui-vhr126:$1{error message} with vacation days limit $2{vacation_days_limit}','Error $1 in Vacation Days: $2');
uis.lang_en('ui-vhr126:$1{error message} with workplace equipment $2{workplace_equipment}','Error $1 in Wokspace Equipment: $2');
uis.lang_en('ui-vhr126:concluding term','Concluding Term');
uis.lang_en('ui-vhr126:contract date','Contract Date');
uis.lang_en('ui-vhr126:contract number','Contract Number');
uis.lang_en('ui-vhr126:division code','Department Code');
uis.lang_en('ui-vhr126:division name','Department');
uis.lang_en('ui-vhr126:employee code','Employee Code');
uis.lang_en('ui-vhr126:employee name','Full Name');
uis.lang_en('ui-vhr126:employment type name','Employment Type');
uis.lang_en('ui-vhr126:expiry date','Contract Expiry Date');
uis.lang_en('ui-vhr126:fixed term','Fixed-term Labour Contract');
uis.lang_en('ui-vhr126:fixed term base code','Fixed-term Contract Reason Code');
uis.lang_en('ui-vhr126:fixed term base name','Fixed-term Contract Reason');
uis.lang_en('ui-vhr126:fixed_term:no','No');
uis.lang_en('ui-vhr126:fixed_term:yes','Yes');
uis.lang_en('ui-vhr126:fte','Full-time equivalent');
uis.lang_en('ui-vhr126:hiring conditions','Hiring Requirements');
uis.lang_en('ui-vhr126:hiring date','Hiring Date');
uis.lang_en('ui-vhr126:hirings','Massive Hiring');
uis.lang_en('ui-vhr126:identifier:code','Code');
uis.lang_en('ui-vhr126:identifier:name','Name');
uis.lang_en('ui-vhr126:indicator value','Measure');
uis.lang_en('ui-vhr126:job code','Job Code');
uis.lang_en('ui-vhr126:job name','Job');
uis.lang_en('ui-vhr126:oper type name','Wage Payment');
uis.lang_en('ui-vhr126:other conditions','Other Requirements');
uis.lang_en('ui-vhr126:rank','Rank');
uis.lang_en('ui-vhr126:rank code','Rank Code');
uis.lang_en('ui-vhr126:rank name','Rank');
uis.lang_en('ui-vhr126:representative basis','Representative Reason');
uis.lang_en('ui-vhr126:robot code','Position Code');
uis.lang_en('ui-vhr126:robot name','Position');
uis.lang_en('ui-vhr126:schedule code','Work Schedule Code');
uis.lang_en('ui-vhr126:schedule name','Work Schedule');
uis.lang_en('ui-vhr126:staff_number','PersNo');
uis.lang_en('ui-vhr126:trial period','Initial Assessment Period');
uis.lang_en('ui-vhr126:vacation days limit','Vacation Days');
uis.lang_en('ui-vhr126:vacation days limit must be between 0 and 365','Vacation Days must be between 0 and 365');
uis.lang_en('ui-vhr126:workplace equipment','Workspace Equipment');
commit;
end;
/
