prompt PATH TRANSLATE /vhr/hpd/hiring
begin
uis.lang_en('#a:/vhr/hpd/hiring+add$add_accrual','Create wage payment');
uis.lang_en('#a:/vhr/hpd/hiring+add$add_deduction','Create wage deduction');
uis.lang_en('#a:/vhr/hpd/hiring+add$add_employee','Create employee');
uis.lang_en('#a:/vhr/hpd/hiring+add$add_employment_source','Create employment source');
uis.lang_en('#a:/vhr/hpd/hiring+add$add_fixed_term_base','Create fixed-term contract proof');
uis.lang_en('#a:/vhr/hpd/hiring+add$add_fte','Create employment type');
uis.lang_en('#a:/vhr/hpd/hiring+add$add_job','Create job');
uis.lang_en('#a:/vhr/hpd/hiring+add$add_rank','Create qualification rank');
uis.lang_en('#a:/vhr/hpd/hiring+add$add_schedule','Create work schedule');
uis.lang_en('#a:/vhr/hpd/hiring+add$add_wage_scale','Create tariff group');
uis.lang_en('#a:/vhr/hpd/hiring+add$select_accrual','Select wage payments');
uis.lang_en('#a:/vhr/hpd/hiring+add$select_deduction','Select wage deduction');
uis.lang_en('#a:/vhr/hpd/hiring+add$select_employee','Select employee');
uis.lang_en('#a:/vhr/hpd/hiring+add$select_employment_source','Select employment source');
uis.lang_en('#a:/vhr/hpd/hiring+add$select_fixed_term_base','Select fixed-term contract proof');
uis.lang_en('#a:/vhr/hpd/hiring+add$select_fte','Select employment type');
uis.lang_en('#a:/vhr/hpd/hiring+add$select_job','Select job');
uis.lang_en('#a:/vhr/hpd/hiring+add$select_rank','Select qualification rank');
uis.lang_en('#a:/vhr/hpd/hiring+add$select_robot','Select position');
uis.lang_en('#a:/vhr/hpd/hiring+add$select_schedule','Select work schedule');
uis.lang_en('#a:/vhr/hpd/hiring+add$select_wage_scale','Select tariff group');
uis.lang_en('#a:/vhr/hpd/hiring+edit$add_accrual','Create wage payment');
uis.lang_en('#a:/vhr/hpd/hiring+edit$add_deduction','Create wage deduction');
uis.lang_en('#a:/vhr/hpd/hiring+edit$add_employee','Create employee');
uis.lang_en('#a:/vhr/hpd/hiring+edit$add_employment_source','Create employment source');
uis.lang_en('#a:/vhr/hpd/hiring+edit$add_fixed_term_base','Create fixed-term contract proof');
uis.lang_en('#a:/vhr/hpd/hiring+edit$add_fte','Create employment type');
uis.lang_en('#a:/vhr/hpd/hiring+edit$add_job','Create job');
uis.lang_en('#a:/vhr/hpd/hiring+edit$add_rank','Create qualification rank');
uis.lang_en('#a:/vhr/hpd/hiring+edit$add_schedule','Create work schedule');
uis.lang_en('#a:/vhr/hpd/hiring+edit$add_wage_scale','Create tariff group');
uis.lang_en('#a:/vhr/hpd/hiring+edit$select_accrual','Select wage payments');
uis.lang_en('#a:/vhr/hpd/hiring+edit$select_deduction','Select wage deduction');
uis.lang_en('#a:/vhr/hpd/hiring+edit$select_employee','Select employee');
uis.lang_en('#a:/vhr/hpd/hiring+edit$select_employment_source','Select employment source');
uis.lang_en('#a:/vhr/hpd/hiring+edit$select_fixed_term_base','Select fixed-term contract proof');
uis.lang_en('#a:/vhr/hpd/hiring+edit$select_fte','Select employment type');
uis.lang_en('#a:/vhr/hpd/hiring+edit$select_job','Select job');
uis.lang_en('#a:/vhr/hpd/hiring+edit$select_rank','Select qualification rank');
uis.lang_en('#a:/vhr/hpd/hiring+edit$select_robot','Select position');
uis.lang_en('#a:/vhr/hpd/hiring+edit$select_schedule','Select work schedule');
uis.lang_en('#a:/vhr/hpd/hiring+edit$select_wage_scale','Select tariff group');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_add$add_accrual','Create wage payment');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_add$add_deduction','Create wage deduction');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_add$add_employee','Create employee');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_add$add_employment_source','Create employment source');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_add$add_fixed_term_base','Create fixed-term contract proof');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_add$add_fte','Create employment type');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_add$add_job','Create job');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_add$add_rank','Create qualification rank');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_add$add_schedule','Create work schedule');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_add$add_wage_scale','Create tariff group');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_add$hiring_import','Import');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_add$select_accrual','Select wage payments');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_add$select_deduction','Select wage deduction');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_add$select_employee','Select employee');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_add$select_employment_source','Select employment source');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_add$select_fixed_term_base','Select fixed-term contract proof');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_add$select_fte','Select employment type');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_add$select_job','Select job');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_add$select_rank','Select qualification rank');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_add$select_robot','Select position');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_add$select_schedule','Select shift plan');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_add$select_wage_scale','Select tariff group');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_edit$add_accrual','Create wage payment');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_edit$add_deduction','Create wage deduction');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_edit$add_employee','Create employee');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_edit$add_employment_source','Create employment source');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_edit$add_fixed_term_base','Create fixed-term contract proof');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_edit$add_fte','Create employment type');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_edit$add_job','Create job');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_edit$add_rank','Create qualification rank');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_edit$add_schedule','Create shift plan');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_edit$add_wage_scale','Create tariff group');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_edit$hiring_import','Import');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_edit$select_accrual','Select wage payments');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_edit$select_deduction','Select wage deduction');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_edit$select_employee','Select employee');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_edit$select_employment_source','Select employment source');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_edit$select_fixed_term_base','Select fixed-term contract proof');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_edit$select_fte','Select employment type');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_edit$select_job','Select job');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_edit$select_rank','Select qualification rank');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_edit$select_robot','Select position');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_edit$select_schedule','Select shift plan');
uis.lang_en('#a:/vhr/hpd/hiring+multiple_edit$select_wage_scale','Select tariff group');
uis.lang_en('#f:/vhr/hpd/hiring+add','Hiring / New');
uis.lang_en('#f:/vhr/hpd/hiring+edit','Hiring / Edit');
uis.lang_en('#f:/vhr/hpd/hiring+multiple_add','Massive Hiring / New');
uis.lang_en('#f:/vhr/hpd/hiring+multiple_edit','Massive Hiring / Edit');
commit;
end;
/
