prompt PATH TRANSLATE /vhr/hpd/journal_list
begin
uis.lang_en('#a:/vhr/hpd/journal_list$business_trip_add','Business Trip / New');
uis.lang_en('#a:/vhr/hpd/journal_list$business_trip_audit','Audit Log');
uis.lang_en('#a:/vhr/hpd/journal_list$business_trip_edit','Business Trip / Edit');
uis.lang_en('#a:/vhr/hpd/journal_list$business_trip_multiple_add','Massive Business Trip / New');
uis.lang_en('#a:/vhr/hpd/journal_list$business_trip_multiple_edit','Massive Business Trip / Edit');
uis.lang_en('#a:/vhr/hpd/journal_list$business_trip_multiple_view','Massive Business Trip / View');
uis.lang_en('#a:/vhr/hpd/journal_list$business_trip_view','Business Trip / View');
uis.lang_en('#a:/vhr/hpd/journal_list$create_sign_document','Create Workflow');
uis.lang_en('#a:/vhr/hpd/journal_list$delete','Delete');
uis.lang_en('#a:/vhr/hpd/journal_list$dismissal_add','Dismissal / New');
uis.lang_en('#a:/vhr/hpd/journal_list$dismissal_audit','Audit Log');
uis.lang_en('#a:/vhr/hpd/journal_list$dismissal_edit','Dismissal / Edit');
uis.lang_en('#a:/vhr/hpd/journal_list$dismissal_multiple_add','Massive Dismissal / New');
uis.lang_en('#a:/vhr/hpd/journal_list$dismissal_multiple_audit','Audit Log');
uis.lang_en('#a:/vhr/hpd/journal_list$dismissal_multiple_edit','Massive Dismissal / Edit');
uis.lang_en('#a:/vhr/hpd/journal_list$dismissal_multiple_report','Dismissal Order');
uis.lang_en('#a:/vhr/hpd/journal_list$dismissal_multiple_view','Dismissal Multiple / View');
uis.lang_en('#a:/vhr/hpd/journal_list$dismissal_report','Dismissal Order');
uis.lang_en('#a:/vhr/hpd/journal_list$dismissal_view','Dismissal / View');
uis.lang_en('#a:/vhr/hpd/journal_list$hiring_add','Hiring / New');
uis.lang_en('#a:/vhr/hpd/journal_list$hiring_audit','Audit Log');
uis.lang_en('#a:/vhr/hpd/journal_list$hiring_contract_add','Hiring for Civil Law Contracts / New');
uis.lang_en('#a:/vhr/hpd/journal_list$hiring_contract_edit','Hiring for Civil Law Contracts / Edit');
uis.lang_en('#a:/vhr/hpd/journal_list$hiring_contract_view','Hiring for Civil Law Contracts / View');
uis.lang_en('#a:/vhr/hpd/journal_list$hiring_edit','Hiring / Edit');
uis.lang_en('#a:/vhr/hpd/journal_list$hiring_multiple_add','Massive Hiring / New');
uis.lang_en('#a:/vhr/hpd/journal_list$hiring_multiple_audit','Audit Log');
uis.lang_en('#a:/vhr/hpd/journal_list$hiring_multiple_edit','Massive Hiring / Edit');
uis.lang_en('#a:/vhr/hpd/journal_list$hiring_multiple_report','Hiring Order');
uis.lang_en('#a:/vhr/hpd/journal_list$hiring_multiple_view','Hiring Multiple / View');
uis.lang_en('#a:/vhr/hpd/journal_list$hiring_report','Hiring Order');
uis.lang_en('#a:/vhr/hpd/journal_list$hiring_view','Hiring / View');
uis.lang_en('#a:/vhr/hpd/journal_list$labor_contract','Labour Contract');
uis.lang_en('#a:/vhr/hpd/journal_list$overtime_add','Overtime / View');
uis.lang_en('#a:/vhr/hpd/journal_list$overtime_audit','Audit Log');
uis.lang_en('#a:/vhr/hpd/journal_list$overtime_edit','Overtime / Edit');
uis.lang_en('#a:/vhr/hpd/journal_list$overtime_view','Overtime / View');
uis.lang_en('#a:/vhr/hpd/journal_list$post','Post');
uis.lang_en('#a:/vhr/hpd/journal_list$rank_change_add','Rank Change / New');
uis.lang_en('#a:/vhr/hpd/journal_list$rank_change_audit','Rank Change Audit Log');
uis.lang_en('#a:/vhr/hpd/journal_list$rank_change_edit','Rank Change / Edit');
uis.lang_en('#a:/vhr/hpd/journal_list$rank_change_multiple_add','Massive Rank Change / New');
uis.lang_en('#a:/vhr/hpd/journal_list$rank_change_multiple_edit','Massive Rank Change / Edit');
uis.lang_en('#a:/vhr/hpd/journal_list$rank_change_multiple_view','Massive Rank Change / View');
uis.lang_en('#a:/vhr/hpd/journal_list$rank_change_view','Rank Change / View');
uis.lang_en('#a:/vhr/hpd/journal_list$schedule_change_add','Massive Shift Plan Change / New');
uis.lang_en('#a:/vhr/hpd/journal_list$schedule_change_audit','Audit Log');
uis.lang_en('#a:/vhr/hpd/journal_list$schedule_change_edit','Massive Shift Plan Change / Edit');
uis.lang_en('#a:/vhr/hpd/journal_list$schedule_change_view','Massive Work Schedule Change / View');
uis.lang_en('#a:/vhr/hpd/journal_list$sick_leave_add','Sick Note / New');
uis.lang_en('#a:/vhr/hpd/journal_list$sick_leave_audit','Audit Log');
uis.lang_en('#a:/vhr/hpd/journal_list$sick_leave_edit','Sick Note / Edit');
uis.lang_en('#a:/vhr/hpd/journal_list$sick_leave_multiple_add','Massive Sick Note / New');
uis.lang_en('#a:/vhr/hpd/journal_list$sick_leave_multiple_audit','Audit Log');
uis.lang_en('#a:/vhr/hpd/journal_list$sick_leave_multiple_edit','Massive Sick Note / Edit');
uis.lang_en('#a:/vhr/hpd/journal_list$sick_leave_multiple_view','Massive Sick Note / View');
uis.lang_en('#a:/vhr/hpd/journal_list$sick_leave_view','Sick Note / New');
uis.lang_en('#a:/vhr/hpd/journal_list$timebook_adjustment_add','Time Sheet Adjustment / New');
uis.lang_en('#a:/vhr/hpd/journal_list$timebook_adjustment_audit','Audit Log');
uis.lang_en('#a:/vhr/hpd/journal_list$timebook_adjustment_edit','Time Sheet Adjustment / Edit');
uis.lang_en('#a:/vhr/hpd/journal_list$timebook_adjustment_view','Timebook Adjustment / View');
uis.lang_en('#a:/vhr/hpd/journal_list$to_draft','Workflow to Draft');
uis.lang_en('#a:/vhr/hpd/journal_list$to_progress','Workflow for Signing');
uis.lang_en('#a:/vhr/hpd/journal_list$transfer_add','HR Transfer / New');
uis.lang_en('#a:/vhr/hpd/journal_list$transfer_audit','Audit Log');
uis.lang_en('#a:/vhr/hpd/journal_list$transfer_edit','HR Transfer / Edit');
uis.lang_en('#a:/vhr/hpd/journal_list$transfer_multiple_add','Massive HR Transfer / New');
uis.lang_en('#a:/vhr/hpd/journal_list$transfer_multiple_audit','Audit Log');
uis.lang_en('#a:/vhr/hpd/journal_list$transfer_multiple_edit','Massive HR Transfer / Edit');
uis.lang_en('#a:/vhr/hpd/journal_list$transfer_multiple_report','HR Transfer Order');
uis.lang_en('#a:/vhr/hpd/journal_list$transfer_multiple_view','Transfer Multiple / View');
uis.lang_en('#a:/vhr/hpd/journal_list$transfer_report','HR Transfer Order');
uis.lang_en('#a:/vhr/hpd/journal_list$transfer_view','Transfer / View');
uis.lang_en('#a:/vhr/hpd/journal_list$unpost','Cancel');
uis.lang_en('#a:/vhr/hpd/journal_list$update_sign_document','Update Workflow');
uis.lang_en('#a:/vhr/hpd/journal_list$vacation_add','Vacation / New');
uis.lang_en('#a:/vhr/hpd/journal_list$vacation_edit','Vacation / Edit');
uis.lang_en('#a:/vhr/hpd/journal_list$vacation_limit_change_add','Vacation Days Change / New');
uis.lang_en('#a:/vhr/hpd/journal_list$vacation_limit_change_edit','Vacation Days Change / Edit');
uis.lang_en('#a:/vhr/hpd/journal_list$vacation_limit_change_view','Vacation Days Change / View');
uis.lang_en('#a:/vhr/hpd/journal_list$vacation_multiple_add','Massive Vacation / New');
uis.lang_en('#a:/vhr/hpd/journal_list$vacation_multiple_edit','Massive Vacation / Edit');
uis.lang_en('#a:/vhr/hpd/journal_list$vacation_multiple_view','Massive Vacation / View');
uis.lang_en('#a:/vhr/hpd/journal_list$vacation_view','Vacation / View');
uis.lang_en('#a:/vhr/hpd/journal_list$wage_change_add','Remuneration / New');
uis.lang_en('#a:/vhr/hpd/journal_list$wage_change_audit','Audit Log');
uis.lang_en('#a:/vhr/hpd/journal_list$wage_change_edit','Remuneration / Edit');
uis.lang_en('#a:/vhr/hpd/journal_list$wage_change_multiple_add','Wage Change Multiple / View');
uis.lang_en('#a:/vhr/hpd/journal_list$wage_change_multiple_audit','Audit Log');
uis.lang_en('#a:/vhr/hpd/journal_list$wage_change_multiple_edit','Wage Change Multiple / Edit');
uis.lang_en('#a:/vhr/hpd/journal_list$wage_change_multiple_view','Massive Remuneration Change / View');
uis.lang_en('#a:/vhr/hpd/journal_list$wage_change_view','Wage Change / View');
uis.lang_en('#f:/vhr/hpd/journal_list','HR Documents');
commit;
end;
/
