prompt PATH TRANSLATE /vhr/hpd/transfer
begin
uis.lang_en('#a:/vhr/hpd/transfer+add$add_accrual','Create wage payment');
uis.lang_en('#a:/vhr/hpd/transfer+add$add_deduction','Create wage deduction');
uis.lang_en('#a:/vhr/hpd/transfer+add$add_fixed_term_base','Create fixed-term contract proof');
uis.lang_en('#a:/vhr/hpd/transfer+add$add_fte','Create employment type');
uis.lang_en('#a:/vhr/hpd/transfer+add$add_rank','Create qualification rank');
uis.lang_en('#a:/vhr/hpd/transfer+add$add_schedule','Create work schedule');
uis.lang_en('#a:/vhr/hpd/transfer+add$add_wage_scale','Create tariff group');
uis.lang_en('#a:/vhr/hpd/transfer+add$select_accrual','Select wage payments');
uis.lang_en('#a:/vhr/hpd/transfer+add$select_deduction','Select wage deduction');
uis.lang_en('#a:/vhr/hpd/transfer+add$select_fixed_term_base','Select fixed-term contract proof');
uis.lang_en('#a:/vhr/hpd/transfer+add$select_fte','Select employment type');
uis.lang_en('#a:/vhr/hpd/transfer+add$select_rank','Select qualification rank');
uis.lang_en('#a:/vhr/hpd/transfer+add$select_robot','Select position');
uis.lang_en('#a:/vhr/hpd/transfer+add$select_schedule','Select work schedule');
uis.lang_en('#a:/vhr/hpd/transfer+add$select_staff','Select employee');
uis.lang_en('#a:/vhr/hpd/transfer+add$select_wage_scale','Select tariff group');
uis.lang_en('#a:/vhr/hpd/transfer+edit$add_accrual','Create wage payment');
uis.lang_en('#a:/vhr/hpd/transfer+edit$add_deduction','Create wage deduction');
uis.lang_en('#a:/vhr/hpd/transfer+edit$add_fixed_term_base','Create fixed-term contract proof');
uis.lang_en('#a:/vhr/hpd/transfer+edit$add_fte','Create employment type');
uis.lang_en('#a:/vhr/hpd/transfer+edit$add_rank','Create qualification rank');
uis.lang_en('#a:/vhr/hpd/transfer+edit$add_schedule','Create shift plan');
uis.lang_en('#a:/vhr/hpd/transfer+edit$add_wage_scale','Create tariff group');
uis.lang_en('#a:/vhr/hpd/transfer+edit$select_accrual','Select wage payments');
uis.lang_en('#a:/vhr/hpd/transfer+edit$select_deduction','Select wage deduction');
uis.lang_en('#a:/vhr/hpd/transfer+edit$select_fixed_term_base','Select fixed-term contract proof');
uis.lang_en('#a:/vhr/hpd/transfer+edit$select_fte','Select employment type');
uis.lang_en('#a:/vhr/hpd/transfer+edit$select_rank','Select qualification rank');
uis.lang_en('#a:/vhr/hpd/transfer+edit$select_robot','Select position');
uis.lang_en('#a:/vhr/hpd/transfer+edit$select_schedule','Select shift plan');
uis.lang_en('#a:/vhr/hpd/transfer+edit$select_staff','Select employee');
uis.lang_en('#a:/vhr/hpd/transfer+edit$select_wage_scale','Select tariff group');
uis.lang_en('#a:/vhr/hpd/transfer+multiple_add$add_accrual','Create wage payment');
uis.lang_en('#a:/vhr/hpd/transfer+multiple_add$add_deduction','Create wage deduction');
uis.lang_en('#a:/vhr/hpd/transfer+multiple_add$add_fixed_term_base','Create fixed-term contract reason');
uis.lang_en('#a:/vhr/hpd/transfer+multiple_add$add_fte','Create employment type');
uis.lang_en('#a:/vhr/hpd/transfer+multiple_add$add_rank','Create qualification rank');
uis.lang_en('#a:/vhr/hpd/transfer+multiple_add$add_schedule','Create shift plan');
uis.lang_en('#a:/vhr/hpd/transfer+multiple_add$add_wage_scale','Create tariff group');
uis.lang_en('#a:/vhr/hpd/transfer+multiple_add$select_accrual','Select wage payments');
uis.lang_en('#a:/vhr/hpd/transfer+multiple_add$select_deduction','Select wage deduction');
uis.lang_en('#a:/vhr/hpd/transfer+multiple_add$select_fixed_term_base','Select fixed-term contract reason');
uis.lang_en('#a:/vhr/hpd/transfer+multiple_add$select_fte','Select employment type');
uis.lang_en('#a:/vhr/hpd/transfer+multiple_add$select_rank','Select qualification rank');
uis.lang_en('#a:/vhr/hpd/transfer+multiple_add$select_robot','Select position');
uis.lang_en('#a:/vhr/hpd/transfer+multiple_add$select_schedule','Select shift plan');
uis.lang_en('#a:/vhr/hpd/transfer+multiple_add$select_staff','Select employee');
uis.lang_en('#a:/vhr/hpd/transfer+multiple_add$select_wage_scale','Select tariff group');
uis.lang_en('#a:/vhr/hpd/transfer+multiple_edit$add_fixed_term_base','Create fixed-term contract proof');
uis.lang_en('#a:/vhr/hpd/transfer+multiple_edit$add_fte','Create employment type');
uis.lang_en('#a:/vhr/hpd/transfer+multiple_edit$add_oper_type','Create wage payment');
uis.lang_en('#a:/vhr/hpd/transfer+multiple_edit$add_rank','Create qualification rank');
uis.lang_en('#a:/vhr/hpd/transfer+multiple_edit$add_schedule','Create shift plan');
uis.lang_en('#a:/vhr/hpd/transfer+multiple_edit$add_wage_scale','Create tariff group');
uis.lang_en('#a:/vhr/hpd/transfer+multiple_edit$select_accrual','Select wage payments');
uis.lang_en('#a:/vhr/hpd/transfer+multiple_edit$select_deduction','Select wage deduction');
uis.lang_en('#a:/vhr/hpd/transfer+multiple_edit$select_fixed_term_base','Select fixed-term contract proof');
uis.lang_en('#a:/vhr/hpd/transfer+multiple_edit$select_fte','Select employment type');
uis.lang_en('#a:/vhr/hpd/transfer+multiple_edit$select_rank','Select qualification rank');
uis.lang_en('#a:/vhr/hpd/transfer+multiple_edit$select_robot','Select position');
uis.lang_en('#a:/vhr/hpd/transfer+multiple_edit$select_schedule','Select shift plan');
uis.lang_en('#a:/vhr/hpd/transfer+multiple_edit$select_staff','Select employee');
uis.lang_en('#a:/vhr/hpd/transfer+multiple_edit$select_wage_scale','Select tariff group');
uis.lang_en('#f:/vhr/hpd/transfer+add','HR Transfer / New');
uis.lang_en('#f:/vhr/hpd/transfer+edit','HR Transfer / Edit');
uis.lang_en('#f:/vhr/hpd/transfer+multiple_add','Massive HR Transfer / New');
uis.lang_en('#f:/vhr/hpd/transfer+multiple_edit','Massive HR Transfer / Edit');
commit;
end;
/
