prompt PATH TRANSLATE /vhr/href/start/employee_import
begin
uis.lang_en('#a:/vhr/href/start/employee_import$save_setting','Save settings');
uis.lang_en('#f:/vhr/href/start/employee_import','Employees / Import');
uis.lang_en('ui-vhr309:$1{error message} with address $2{address}','Error $1 in Address: $2');
uis.lang_en('ui-vhr309:$1{error message} with birthday $2{birthday}','Error $1 in Birth Date: $2');
uis.lang_en('ui-vhr309:$1{error message} with division $2{division}','Error $1 in Department: $2');
uis.lang_en('ui-vhr309:$1{error message} with email $2{email}','Error $1 in Email: $2');
uis.lang_en('ui-vhr309:$1{error message} with fte $2{fte}','Error $1 in Full-time equivalent $2');
uis.lang_en('ui-vhr309:$1{error message} with gender $2{gender}','Error $1 in Gender: $2');
uis.lang_en('ui-vhr309:$1{error message} with hiring_date $2{hiring_date}','Error $1 in Hiring Date: $2');
uis.lang_en('ui-vhr309:$1{error message} with iapa $2{iapa}','Error $1 in IPSA: $2');
uis.lang_en('ui-vhr309:$1{error message} with job $2{job}','Error $1 in Job: $2');
uis.lang_en('ui-vhr309:$1{error message} with legal address $2{legal_address}','Error $1 in Legal Address: $2');
uis.lang_en('ui-vhr309:$1{error message} with location $2{location}','Error $1 in Location: $2');
uis.lang_en('ui-vhr309:$1{error message} with login $2{login}','Error $1 in Login: $2');
uis.lang_en('ui-vhr309:$1{error message} with main phone $2{main phone}','Error $1 in Phone: $2');
uis.lang_en('ui-vhr309:$1{error message} with nationality $2{nationality}','Error $1 in Nationality: $2');
uis.lang_en('ui-vhr309:$1{error message} with natural person first name $2{natural person}','Error $1 in First Name: $2');
uis.lang_en('ui-vhr309:$1{error message} with natural person last name $2{natural person}','Error $1 in Last Name: $2');
uis.lang_en('ui-vhr309:$1{error message} with natural person middle name $2{natural person}','Error $1 in Patronymic: $2');
uis.lang_en('ui-vhr309:$1{error message} with npin $2{npin}','Error $1 in IPIN: $2');
uis.lang_en('ui-vhr309:$1{error message} with region $2{region}','Error $1 in Region: $2');
uis.lang_en('ui-vhr309:$1{error message} with salary_amount $2{salary_amount}','Error $1 in Salary: $2');
uis.lang_en('ui-vhr309:$1{error message} with salary_type $2{salary_type}','Error $1 in Salary Type: $2');
uis.lang_en('ui-vhr309:$1{error message} with schedule $2{schedule}','Error $1 in Work Schedule: $2');
uis.lang_en('ui-vhr309:$1{error message} with staff_number $2{employee number}','Error $1 in PersNo: $2');
uis.lang_en('ui-vhr309:address','Address');
uis.lang_en('ui-vhr309:birthday','Birth Date');
uis.lang_en('ui-vhr309:chosen job is not belongs to chosen division, job_id=$1, division_id=$2','The selected job does not belong to the selected department, job ID=$1, department ID=$2');
uis.lang_en('ui-vhr309:division','Department');
uis.lang_en('ui-vhr309:email','Email');
uis.lang_en('ui-vhr309:employees','Employees');
uis.lang_en('ui-vhr309:first_name','First Name');
uis.lang_en('ui-vhr309:fte_name','Employment Type');
uis.lang_en('ui-vhr309:gender','Gender');
uis.lang_en('ui-vhr309:hiring_date','Hiring Date');
uis.lang_en('ui-vhr309:iapa','IPSA');
uis.lang_en('ui-vhr309:identifier:code','Code');
uis.lang_en('ui-vhr309:identifier:name','Name');
uis.lang_en('ui-vhr309:job','Job');
uis.lang_en('ui-vhr309:last_name','Last Name');
uis.lang_en('ui-vhr309:legal_address','Legal Address');
uis.lang_en('ui-vhr309:location','Location');
uis.lang_en('ui-vhr309:login','Login');
uis.lang_en('ui-vhr309:login is used, $1=login','Login already taken, login=$1');
uis.lang_en('ui-vhr309:main_phone','Phone');
uis.lang_en('ui-vhr309:middle_name','Patronymic');
uis.lang_en('ui-vhr309:nationality_name','Nationality');
uis.lang_en('ui-vhr309:npin','IPIN');
uis.lang_en('ui-vhr309:region','Region');
uis.lang_en('ui-vhr309:salary_amount','Salary');
uis.lang_en('ui-vhr309:salary_type','Salary type');
uis.lang_en('ui-vhr309:schedule','Work Schedule');
uis.lang_en('ui-vhr309:staff_number','PersNo');
commit;
end;
/
