prompt PATH TRANSLATE /vhr/href/employee/employee_import
begin
uis.lang_ru('#a:/vhr/href/employee/employee_import$save_setting','Сохранить настройки');
uis.lang_ru('#f:/vhr/href/employee/employee_import','Сотрудники (импорт)');
uis.lang_ru('ui-vhr265:$1{error message} with address $2{address}','Ошибка с адресом места проживания: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with birthday $2{birthday}','Ошибка со днем рождения: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with corporate email $2{corporate_email}','Ошибка с корпоративным E-mail: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with division $2{division}','Ошибка с подразделением: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with email $2{email}','Ошибка с E-mail: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with employee id $2{employee id}','Ошибка с ИД: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with employee number $2{employee number}','Ошибка с табельным номером: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with extra phone number $2{extra phone number}','Ошибка с дополнительным номером телефона: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with fte $2{fte}','Ошибка со ставкой: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with gender $2{gender}','Ошибка с полом: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with hiring date $2{hiring_date}','Ошибка с датой приема: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with iapa $2{iapa}','Ошибка с ИНПС: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with job $2{job}','Ошибка с должностью: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with legal address $2{legal_address}','Ошибка с адресом по прописке: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with location $2{location}','Ошибка с локацией: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with main phone $2{main phone}','Ошибка с телефоном: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with nationality $2{nationality}','Ошибка с национальностью: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with natural person first name $2{natural person}','Ошибка с именем: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with natural person last name $2{natural person}','Ошибка с фамилией: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with natural person middle name $2{natural person}','Ошибка с отчеством: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with npin $2{npin}','Ошибка с ПИНФЛ: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with oper type $2{oper_type}','Ошибка с начислением: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with org unit $2{org unit}','Ошибка с Организационной единицей: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with passport_begin_date $2{passport_begin_date}','Ошибка с датой начала действия паспорта: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with passport_expiry_date $2{passport_expiry_date}','Ошибка с датой истечения паспорта: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with passport_issued_by $2{passport_issued_by}','Ошибка с выдачей паспорта: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with passport_issued_date $2{passport_issued_date}','Ошибка с датой выдачи паспорта: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with passport_number $2{passport_number}','Ошибка с номером паспорта: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with passport_series $2{passport_series}','Ошибка с серий паспорта: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with pin $2{pin}','Ошибка с ПИН кодом: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with pin_code $2{pin_code}','Ошибка с паролем: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with rank $2{rank}','Ошибка с разрядом: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with region $2{region}','Ошибка с регионом: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with rfid_code $2{rfid_code}','Ошибка с номером RFID карты: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with robot $2{robot}','Ошибка с позицией: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with schedule $2{schedule}','Ошибка с графиком работы: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with tin $2{tin}','Ошибка с ИНН: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with wage $2{wage}','Ошибка с окладом: $2. $1');
uis.lang_ru('ui-vhr265:$1{error message} with wage scale $2{wage scale}','Ошибка с тарифным группам: $2. $1');
uis.lang_ru('ui-vhr265:address','Адрес места проживания');
uis.lang_ru('ui-vhr265:birthday','Дата рождения');
uis.lang_ru('ui-vhr265:chosen job is not belongs to chosen division, job_id=$1, division_id=$2','Выбранная должность не принадлежит выбранному подразделению, ИД должности=$1, ИД подразделения=$2');
uis.lang_ru('ui-vhr265:corporate_email','Корпоративный E-mail');
uis.lang_ru('ui-vhr265:division','Подразделение');
uis.lang_ru('ui-vhr265:division (code)','Отдел (код)');
uis.lang_ru('ui-vhr265:email','Email');
uis.lang_ru('ui-vhr265:employee_id','ИД');
uis.lang_ru('ui-vhr265:employee_number','Табельный номер');
uis.lang_ru('ui-vhr265:employees','Сотрудники');
uis.lang_ru('ui-vhr265:error with first name=$1{first name}, last name=$2{last_name}, login=$3{login} already used by another user','Ошибка, Имя: $1, Фамилия: $2, Логин: $3 уже используются другим пользователем.');
uis.lang_ru('ui-vhr265:extra_phone_number','Дополнительный номер телефона');
uis.lang_ru('ui-vhr265:first name','Имя');
uis.lang_ru('ui-vhr265:first_name','Имя');
uis.lang_ru('ui-vhr265:fte','Ставка');
uis.lang_ru('ui-vhr265:gender','Пол');
uis.lang_ru('ui-vhr265:hiring_date','Дата приема');
uis.lang_ru('ui-vhr265:iapa','ИНПС');
uis.lang_ru('ui-vhr265:identifier: code','Код');
uis.lang_ru('ui-vhr265:identifier: name','Имя');
uis.lang_ru('ui-vhr265:job','Должность');
uis.lang_ru('ui-vhr265:job (code)','Разряд (код)');
uis.lang_ru('ui-vhr265:last name','Фамилия');
uis.lang_ru('ui-vhr265:last_name','Фамилия');
uis.lang_ru('ui-vhr265:legal_address','Адрес по прописке');
uis.lang_ru('ui-vhr265:location','Локация');
uis.lang_ru('ui-vhr265:location (code)','Локация (код)');
uis.lang_ru('ui-vhr265:login','Логин');
uis.lang_ru('ui-vhr265:login_template: first_name.last_name','имя.фамилия');
uis.lang_ru('ui-vhr265:login_template: first_name_last_name','имя_фамилия');
uis.lang_ru('ui-vhr265:login_template: last_name.first_name','фамилия.имя');
uis.lang_ru('ui-vhr265:login_template: last_name_first_name','фамилия_имя');
uis.lang_ru('ui-vhr265:main phone','Телефон');
uis.lang_ru('ui-vhr265:main_phone','Телефон');
uis.lang_ru('ui-vhr265:middle name','Отчество');
uis.lang_ru('ui-vhr265:middle_name','Отчество');
uis.lang_ru('ui-vhr265:nationality','Национальность');
uis.lang_ru('ui-vhr265:note','Примечание');
uis.lang_ru('ui-vhr265:npin','ПИНФЛ');
uis.lang_ru('ui-vhr265:oper_type','Начисление');
uis.lang_ru('ui-vhr265:org unit','Организационная единица');
uis.lang_ru('ui-vhr265:org unit (code)','Организационная единица (код)');
uis.lang_ru('ui-vhr265:passport_begin_date','Дата начала действия (паспорт)');
uis.lang_ru('ui-vhr265:passport_expiry_date','Дата истечения (паспорт)');
uis.lang_ru('ui-vhr265:passport_issued_by','Выдан (паспорт)');
uis.lang_ru('ui-vhr265:passport_issued_date','Дата выдачи (паспорт)');
uis.lang_ru('ui-vhr265:passport_number','Номер паспорта');
uis.lang_ru('ui-vhr265:passport_series','Серия паспорта');
uis.lang_ru('ui-vhr265:pin','ПИН код');
uis.lang_ru('ui-vhr265:pin_code','Пароль');
uis.lang_ru('ui-vhr265:rank','Разряд');
uis.lang_ru('ui-vhr265:region','Регион');
uis.lang_ru('ui-vhr265:rfid_code','Номер RFID карты');
uis.lang_ru('ui-vhr265:robot','Позиция');
uis.lang_ru('ui-vhr265:schedule','График работы');
uis.lang_ru('ui-vhr265:schedule (code)','График работы (код)');
uis.lang_ru('ui-vhr265:tin','ИНН');
uis.lang_ru('ui-vhr265:wage','Оклад');
uis.lang_ru('ui-vhr265:wage scale','Тарифная группа');
uis.lang_ru('ui-vhr265:wage_scale','Тарифная группа');
commit;
end;
/
