prompt PATH TRANSLATE /vhr/hpr/start/wage_sheet_list
begin
uis.lang_uz('#a:/vhr/hpr/start/wage_sheet_list$add','Yaratish');
uis.lang_uz('#a:/vhr/hpr/start/wage_sheet_list$delete','Oʻchirish');
uis.lang_uz('#a:/vhr/hpr/start/wage_sheet_list$edit','Tahrirlash');
uis.lang_uz('#a:/vhr/hpr/start/wage_sheet_list$post','O''tkazish');
uis.lang_uz('#a:/vhr/hpr/start/wage_sheet_list$run','Hisobot');
uis.lang_uz('#a:/vhr/hpr/start/wage_sheet_list$unpost','Qaytarish');
uis.lang_uz('#a:/vhr/hpr/start/wage_sheet_list+onetime$add','Yaratish');
uis.lang_uz('#a:/vhr/hpr/start/wage_sheet_list+onetime$delete','O''chirish');
uis.lang_uz('#a:/vhr/hpr/start/wage_sheet_list+onetime$edit','Tahrirlash');
uis.lang_uz('#a:/vhr/hpr/start/wage_sheet_list+onetime$post','O''tkazish');
uis.lang_uz('#a:/vhr/hpr/start/wage_sheet_list+onetime$unpost','Qaytarish');
uis.lang_uz('#f:/vhr/hpr/start/wage_sheet_list','Maoshni hisoblash');
uis.lang_uz('#f:/vhr/hpr/start/wage_sheet_list+onetime','Bir martalik hisoblashlar');
uis.lang_uz('ui-vhr315:accrual','Hisoblandi');
uis.lang_uz('ui-vhr315:accrual amount','Jami');
uis.lang_uz('ui-vhr315:accrued','Hisoblandi');
uis.lang_uz('ui-vhr315:amount','Qiymat');
uis.lang_uz('ui-vhr315:break time','Tanaffus');
uis.lang_uz('ui-vhr315:date','Sana');
uis.lang_uz('ui-vhr315:day','Kun');
uis.lang_uz('ui-vhr315:day_skip_amount','Qoldirilgan ish kuni');
uis.lang_uz('ui-vhr315:days','Kunlar');
uis.lang_uz('ui-vhr315:deduction','Ushlab qolindi');
uis.lang_uz('ui-vhr315:division','Bo''lim');
uis.lang_uz('ui-vhr315:division: $1','Bo''lim: $1');
uis.lang_uz('ui-vhr315:division: $1{division_name}','Bo''lim: $1');
uis.lang_uz('ui-vhr315:early','Erta ketish');
uis.lang_uz('ui-vhr315:early amount','Erta ketish');
uis.lang_uz('ui-vhr315:early fact','Erta ketish (vaqt)');
uis.lang_uz('ui-vhr315:fact','Ishlangan vaqt');
uis.lang_uz('ui-vhr315:fact time','Ishlangan vaqt');
uis.lang_uz('ui-vhr315:fte: $1{fte_name}','Ish vaqti turi: $1');
uis.lang_uz('ui-vhr315:input','Kirish');
uis.lang_uz('ui-vhr315:job','Lavozim');
uis.lang_uz('ui-vhr315:job: $1{job_name}','Lavozim: $1');
uis.lang_uz('ui-vhr315:lack','Yo''qlik');
uis.lang_uz('ui-vhr315:lack amount','Yo''qlik');
uis.lang_uz('ui-vhr315:lack fact','Yo''qlik (vaqt)');
uis.lang_uz('ui-vhr315:late','Kech kelish');
uis.lang_uz('ui-vhr315:late amount','Kech kelish');
uis.lang_uz('ui-vhr315:late fact','Kech kelish (vaqt)');
uis.lang_uz('ui-vhr315:manager: $1{manager_name}','Rahbar: $1');
uis.lang_uz('ui-vhr315:mark_skip_amount','Qoldirilgan belgilash');
uis.lang_uz('ui-vhr315:month: $1','Oy: $1');
uis.lang_uz('ui-vhr315:monthly amount','Maosh');
uis.lang_uz('ui-vhr315:monthly days','Kunlar');
uis.lang_uz('ui-vhr315:monthly plan','Reja (oy)');
uis.lang_uz('ui-vhr315:monthly time','Soatlar');
uis.lang_uz('ui-vhr315:onetime accrual','Mukofot');
uis.lang_uz('ui-vhr315:onetime penalty','Jarima');
uis.lang_uz('ui-vhr315:output','Chiqish');
uis.lang_uz('ui-vhr315:overtime','Qo''shimcha ish');
uis.lang_uz('ui-vhr315:overtime amount','Qo''shimcha ish');
uis.lang_uz('ui-vhr315:overtime fact','Qo''shimcha ish (vaqt)');
uis.lang_uz('ui-vhr315:part begin','Boshlanish sanasi');
uis.lang_uz('ui-vhr315:penalty','Jarima');
uis.lang_uz('ui-vhr315:penalty amount','Jami');
uis.lang_uz('ui-vhr315:period kind: $1{period_kind} ($2{period_begin} - $3{period_end})','Davr turi: <b>$1</b> ($2 - $3)');
uis.lang_uz('ui-vhr315:period plan','Reja (davr)');
uis.lang_uz('ui-vhr315:period: from $1{begin_date} to $2{end_date}','Davr: $1 - $2');
uis.lang_uz('ui-vhr315:plan','Reja');
uis.lang_uz('ui-vhr315:plan amount','Maosh');
uis.lang_uz('ui-vhr315:plan days','Kunlar');
uis.lang_uz('ui-vhr315:plan time','Soatlar');
uis.lang_uz('ui-vhr315:rest day','Dam olish kuni');
uis.lang_uz('ui-vhr315:rownum','№');
uis.lang_uz('ui-vhr315:schedule','Ish jadvali');
uis.lang_uz('ui-vhr315:schedule: $1{schedule_name}','Ish jadvali: $1');
uis.lang_uz('ui-vhr315:sheet is not posted, sheet_id=$1','Maosh hisoblanishi o''tkazilmagan, ID = $1');
uis.lang_uz('ui-vhr315:sheet_number: $1','Raqam: $1');
uis.lang_uz('ui-vhr315:skip day','Qoldirilgan ish kuni');
uis.lang_uz('ui-vhr315:skip mark','Qoldirilgan belgilash');
uis.lang_uz('ui-vhr315:staff name','Xodim');
uis.lang_uz('ui-vhr315:staff number','Xodim raqami');
uis.lang_uz('ui-vhr315:staff: $1{staff_name}','Xodim: $1');
uis.lang_uz('ui-vhr315:time','Vaqt');
uis.lang_uz('ui-vhr315:total','Jami');
uis.lang_uz('ui-vhr315:total amount','Umumiy qiymat');
uis.lang_uz('ui-vhr315:total:','Jami:');
uis.lang_uz('ui-vhr315:type','Ish vaqti turi');
uis.lang_uz('ui-vhr315:wage','Maosh');
uis.lang_uz('ui-vhr315:wage amount','Maosh');
uis.lang_uz('ui-vhr315:wage days','Kunlar');
uis.lang_uz('ui-vhr315:wage time','Soatlar');
uis.lang_uz('ui-vhr315:you can not see rows that contain jobs that you do not have access to','⚠️ Siz uchun maoshi ko''rinishi cheklangan xodimlar haqidagi maʼlumotlarni koʻra olmaysiz');
commit;
end;
/
