prompt PATH TRANSLATE /vhr/rep/htt/timesheet
begin
uis.lang_ru('#a:/vhr/rep/htt/timesheet$select_division_group','Выбрать группу подразделений');
uis.lang_ru('#a:/vhr/rep/htt/timesheet$select_staff','Выбрать сотрудника');
uis.lang_ru('#f:/vhr/rep/htt/timesheet','Отчет по посещениям сотрудников');
uis.lang_ru('ui-vhr101:$1/$2','$1/$2');
uis.lang_ru('ui-vhr101:absence time','Без причины');
uis.lang_ru('ui-vhr101:date','Дата');
uis.lang_ru('ui-vhr101:day','День');
uis.lang_ru('ui-vhr101:dismissed','УВ');
uis.lang_ru('ui-vhr101:division','Подразделение');
uis.lang_ru('ui-vhr101:division: $1','Подразделение: $1');
uis.lang_ru('ui-vhr101:early time','Ранний уход');
uis.lang_ru('ui-vhr101:employee: $1','Сотрудник: $1');
uis.lang_ru('ui-vhr101:fact','Факт');
uis.lang_ru('ui-vhr101:fact coef','Отработанный коэффициент (вне графика) (%)');
uis.lang_ru('ui-vhr101:fact time','Отработано');
uis.lang_ru('ui-vhr101:fact time removed penalty time','Отработанное время с учетом штрафов');
uis.lang_ru('ui-vhr101:filial','Организация');
uis.lang_ru('ui-vhr101:filial: $1','Организация: $1');
uis.lang_ru('ui-vhr101:filials: $1','Организации: $1');
uis.lang_ru('ui-vhr101:free time','Вне графика');
uis.lang_ru('ui-vhr101:input','Приход');
uis.lang_ru('ui-vhr101:intime','Вовремя');
uis.lang_ru('ui-vhr101:job','Должность');
uis.lang_ru('ui-vhr101:job: $1','Должность: $1');
uis.lang_ru('ui-vhr101:late input','Опоздание');
uis.lang_ru('ui-vhr101:leave','Отсутствие по причине');
uis.lang_ru('ui-vhr101:leave and absence','Отсутствие');
uis.lang_ru('ui-vhr101:leave time','По причине');
uis.lang_ru('ui-vhr101:leave time by coef','По причине (с уч. коэф.)');
uis.lang_ru('ui-vhr101:location','Локации');
uis.lang_ru('ui-vhr101:location: $1','Локации: $1');
uis.lang_ru('ui-vhr101:manager','Руководитель');
uis.lang_ru('ui-vhr101:manager: $1','Руководитель: $1');
uis.lang_ru('ui-vhr101:name','ФИО');
uis.lang_ru('ui-vhr101:not come female','Не пришла');
uis.lang_ru('ui-vhr101:not come male','Не пришел');
uis.lang_ru('ui-vhr101:not come short','X');
uis.lang_ru('ui-vhr101:not hired','НП');
uis.lang_ru('ui-vhr101:not licensed day','Нет подписки');
uis.lang_ru('ui-vhr101:not licensed short','Нет подписки');
uis.lang_ru('ui-vhr101:order no','№');
uis.lang_ru('ui-vhr101:origin penalty early time','Исходное штрафное время за ранний уход');
uis.lang_ru('ui-vhr101:origin penalty lack time','Исходное штрафное время за отсутствие');
uis.lang_ru('ui-vhr101:origin penalty late time','Исходное штрафное время за опоздание');
uis.lang_ru('ui-vhr101:origin penalty total','Исходное штрафное время');
uis.lang_ru('ui-vhr101:original penalty early time','Исходное штрафное время за ранний уход');
uis.lang_ru('ui-vhr101:original penalty lack time','Исходное штрафное время за отсутствие');
uis.lang_ru('ui-vhr101:original penalty late time','Исходное штрафное время за опоздание');
uis.lang_ru('ui-vhr101:original penalty total time','Исходное штрафное время');
uis.lang_ru('ui-vhr101:output','Уход');
uis.lang_ru('ui-vhr101:overtime','Сверхурочно');
uis.lang_ru('ui-vhr101:penalty early time','Штрафное время за ранний уход');
uis.lang_ru('ui-vhr101:penalty lack time','Штрафное время за отсутствие');
uis.lang_ru('ui-vhr101:penalty late time','Штрафное время за опоздание');
uis.lang_ru('ui-vhr101:penalty total time','Штрафное время');
uis.lang_ru('ui-vhr101:period: $1 - $2','Период: $1 - $2');
uis.lang_ru('ui-vhr101:plan','План');
uis.lang_ru('ui-vhr101:plan time','По плану');
uis.lang_ru('ui-vhr101:plan_time','Норма');
uis.lang_ru('ui-vhr101:range date','Диапазон дат');
uis.lang_ru('ui-vhr101:rank','Разряд');
uis.lang_ru('ui-vhr101:rank: $1','Разряд: $1');
uis.lang_ru('ui-vhr101:report attendence','Отчет посещений');
uis.lang_ru('ui-vhr101:rest day','Выходной день');
uis.lang_ru('ui-vhr101:rest day short','В');
uis.lang_ru('ui-vhr101:rest free time','Работа в выходные дни');
uis.lang_ru('ui-vhr101:schedule','График работы');
uis.lang_ru('ui-vhr101:schedule: $1','График работы: $1');
uis.lang_ru('ui-vhr101:select range','Выберите диапазон дат');
uis.lang_ru('ui-vhr101:select staffs','Выберите сотрудников');
uis.lang_ru('ui-vhr101:staff number','Табельный номер');
uis.lang_ru('ui-vhr101:staff number: $1','Табельный номер: $1');
uis.lang_ru('ui-vhr101:staffs','Сотрудники');
uis.lang_ru('ui-vhr101:total','Итого');
uis.lang_ru('ui-vhr101:total time','Итого');
uis.lang_ru('ui-vhr101:track schedule','Отметки');
uis.lang_ru('ui-vhr101:when daily hour time less than plan time or when check track is on and not exists check track or when planned marks count more than done marks count','<b>Условия:</b><br>1) Явка меньше времени по плану. <br />2) При включенной настройки <u>Проверка отметок</u> кол-во отметок меньше запланированного значения или вообще нет отметок.');
uis.lang_ru('ui-vhr101:when day is rest day','Выходной день');
uis.lang_ru('ui-vhr101:when dismissed or not hired','Уволен или не принят на работу или не имеет графика');
uis.lang_ru('ui-vhr101:when done marks count more than planned marks count','Количество отметок больше, чем запланированных отметок');
uis.lang_ru('ui-vhr101:when in rest day have input time and output time','Выходной день имеет отметки прихода и ухода');
uis.lang_ru('ui-vhr101:when not license day','Нет лицензии');
uis.lang_ru('ui-vhr101:when there is no input and output times for the previous day or when done marks count equal zero','<b>Условия:</b><br>1) Нет отметок прихода и ухода.<br>2) При включённой настройки <u>Показать расписание отметок</u> нет отметок по расписанию.');
uis.lang_ru('ui-vhr101:worked coef','Отработанный коэффициент (%)');
uis.lang_ru('ui-vhr101:worked days','Отработано дней');
commit;
end;
/
