prompt PATH TRANSLATE /vhr/rep/htt/timesheet_with_transfer
begin
uis.lang_ru('#a:/vhr/rep/htt/timesheet_with_transfer$select_division_group','Выбрать группу подразделений');
uis.lang_ru('#a:/vhr/rep/htt/timesheet_with_transfer$select_staff','Выбрать сотрудника');
uis.lang_ru('#f:/vhr/rep/htt/timesheet_with_transfer','Отчет по посещениям сотрудников (T-13)');
uis.lang_ru('ui-vhr468:$1/$2','$1/$2');
uis.lang_ru('ui-vhr468:absence time','Без причины');
uis.lang_ru('ui-vhr468:date','Дата');
uis.lang_ru('ui-vhr468:day','День');
uis.lang_ru('ui-vhr468:dismissed','УВ');
uis.lang_ru('ui-vhr468:division','Подразделение');
uis.lang_ru('ui-vhr468:division: $1','Подразделение: $1');
uis.lang_ru('ui-vhr468:early time','Ранний уход');
uis.lang_ru('ui-vhr468:employee: $1','Сотрудник: $1');
uis.lang_ru('ui-vhr468:fact','Факт');
uis.lang_ru('ui-vhr468:fact time','Отработано');
uis.lang_ru('ui-vhr468:free time','Вне графика');
uis.lang_ru('ui-vhr468:input','Приход');
uis.lang_ru('ui-vhr468:intime','Вовремя');
uis.lang_ru('ui-vhr468:job','Должность');
uis.lang_ru('ui-vhr468:job: $1','Должность: $1');
uis.lang_ru('ui-vhr468:late input','Опоздание');
uis.lang_ru('ui-vhr468:leave','Отсутствие по причине');
uis.lang_ru('ui-vhr468:leave and absence','Отсутствие');
uis.lang_ru('ui-vhr468:leave time','По причине');
uis.lang_ru('ui-vhr468:location','Локация');
uis.lang_ru('ui-vhr468:location: $1','Локации: $1');
uis.lang_ru('ui-vhr468:manager','Руководитель');
uis.lang_ru('ui-vhr468:manager: $1','Руководитель: $1');
uis.lang_ru('ui-vhr468:name','ФИО');
uis.lang_ru('ui-vhr468:not come female','Не пришла');
uis.lang_ru('ui-vhr468:not come male','Не пришел');
uis.lang_ru('ui-vhr468:not come short','X');
uis.lang_ru('ui-vhr468:not hired','НП');
uis.lang_ru('ui-vhr468:not licensed day','Нет подписки');
uis.lang_ru('ui-vhr468:not licensed short','Нет подписки');
uis.lang_ru('ui-vhr468:order no','№');
uis.lang_ru('ui-vhr468:org unit','Организационная единица');
uis.lang_ru('ui-vhr468:output','Уход');
uis.lang_ru('ui-vhr468:overtime','Сверхурочно');
uis.lang_ru('ui-vhr468:period: $1 - $2','Период: $1 - $2');
uis.lang_ru('ui-vhr468:plan','План');
uis.lang_ru('ui-vhr468:plan time','По плану (часы)');
uis.lang_ru('ui-vhr468:plan_time','Норма');
uis.lang_ru('ui-vhr468:position: $1','Позиция: $1');
uis.lang_ru('ui-vhr468:rank','Разряд');
uis.lang_ru('ui-vhr468:rank: $1','Разряд: $1');
uis.lang_ru('ui-vhr468:rest day','Выходной день');
uis.lang_ru('ui-vhr468:rest day short','В');
uis.lang_ru('ui-vhr468:robot','Штат');
uis.lang_ru('ui-vhr468:schedule','График работы');
uis.lang_ru('ui-vhr468:schedule: $1','График работы: $1');
uis.lang_ru('ui-vhr468:staff number','Табельный номер');
uis.lang_ru('ui-vhr468:staff number: $1','Табельный номер: $1');
uis.lang_ru('ui-vhr468:total','Итого');
uis.lang_ru('ui-vhr468:total time','Итого');
uis.lang_ru('ui-vhr468:track schedule','Отметки');
uis.lang_ru('ui-vhr468:transfer','КП');
uis.lang_ru('ui-vhr468:transfer period','Период кадрового перевода');
uis.lang_ru('ui-vhr468:worked days','Отработано дней');
commit;
end;
/
