prompt PATH TRANSLATE /vhr/hpd/audit/journal_audit_details
begin
uis.lang_uz('#f:/vhr/hpd/audit/journal_audit_details','O''zgarishlar tarixi tafsilotlari');
uis.lang_uz('ui-vhr183:based on doc','Ishdan bo''shatish asosi');
uis.lang_uz('ui-vhr183:begin date','Boshlanish sanasi');
uis.lang_uz('ui-vhr183:change data','Ma''lumotlarni o''zgartirish');
uis.lang_uz('ui-vhr183:change date','O''zgarish sanasi');
uis.lang_uz('ui-vhr183:coefficient','Koeffitsient');
uis.lang_uz('ui-vhr183:concluding term','Yakunlovchi muddat');
uis.lang_uz('ui-vhr183:contract date','Shartnoma sanasi');
uis.lang_uz('ui-vhr183:contract number','Shartnoma raqami');
uis.lang_uz('ui-vhr183:days limit','Yillik mehnat ta''tili davomiyligi');
uis.lang_uz('ui-vhr183:dismissal date','Ishdan bo''shatish sanasi');
uis.lang_uz('ui-vhr183:dismissal reason name','Ishdan bo''shatish sababi');
uis.lang_uz('ui-vhr183:division name','Bo''lim');
uis.lang_uz('ui-vhr183:employment source name','Qayerdan kelgan');
uis.lang_uz('ui-vhr183:employment type name','Bandlik turi');
uis.lang_uz('ui-vhr183:end date','Tugash sanasi');
uis.lang_uz('ui-vhr183:file name','Fayl');
uis.lang_uz('ui-vhr183:fixed term','Muddatli mehnat shartnomasi');
uis.lang_uz('ui-vhr183:fixed term base name','Muddatli shartnoma asosi');
uis.lang_uz('ui-vhr183:fte','Ish vaqti turi');
uis.lang_uz('ui-vhr183:hiring conditions','Ishga qabul qilish shartlari');
uis.lang_uz('ui-vhr183:hiring date','Qabul sanasi');
uis.lang_uz('ui-vhr183:indicator name','Ko''rsatkich');
uis.lang_uz('ui-vhr183:indicator names','Ko''rsatkichlar');
uis.lang_uz('ui-vhr183:indicator value','Ko''rsatkich qiymati');
uis.lang_uz('ui-vhr183:job name','Lavozim');
uis.lang_uz('ui-vhr183:journal date','Hujjat sanasi');
uis.lang_uz('ui-vhr183:journal number','Hujjat raqami');
uis.lang_uz('ui-vhr183:journal type name','Hujjat turi');
uis.lang_uz('ui-vhr183:note','Izoh');
uis.lang_uz('ui-vhr183:oper type name','Amaliyot turi');
uis.lang_uz('ui-vhr183:order no','№');
uis.lang_uz('ui-vhr183:other conditions','Boshqa shartlar');
uis.lang_uz('ui-vhr183:person name','Jismoniy shaxs');
uis.lang_uz('ui-vhr183:posted','O''tganmi');
uis.lang_uz('ui-vhr183:rank name','Daraja');
uis.lang_uz('ui-vhr183:reason name','Sabab');
uis.lang_uz('ui-vhr183:region name','Mintaqa');
uis.lang_uz('ui-vhr183:representative basis','Vakillik asoslari');
uis.lang_uz('ui-vhr183:robot name','Ish o''rni');
uis.lang_uz('ui-vhr183:schedule name','Ish jadvali');
uis.lang_uz('ui-vhr183:sick leave number','Kasallik varaqasi raqami');
uis.lang_uz('ui-vhr183:staff name','Xodim');
uis.lang_uz('ui-vhr183:transfer base','Ish o''rnini o''zgartirish asosi');
uis.lang_uz('ui-vhr183:transfer begin','Boshlanish sanasi');
uis.lang_uz('ui-vhr183:transfer end','Tugash sanasi');
uis.lang_uz('ui-vhr183:transfer reason','O''zgartirish sababi');
uis.lang_uz('ui-vhr183:trial period','Sinov muddati (kun)');
uis.lang_uz('ui-vhr183:workplace equipment','Ish joyidagi jihozlar');
commit;
end;
/
