prompt PATH TRANSLATE /vhr/htm/recommended_rank_document_list
begin
uis.lang_en('#a:/vhr/htm/recommended_rank_document_list$add','Create');
uis.lang_en('#a:/vhr/htm/recommended_rank_document_list$delete','Delete');
uis.lang_en('#a:/vhr/htm/recommended_rank_document_list$edit','Edit');
uis.lang_en('#a:/vhr/htm/recommended_rank_document_list$edit_statuses','Edit statuses');
uis.lang_en('#a:/vhr/htm/recommended_rank_document_list$edit_trainings','Edit training');
uis.lang_en('#a:/vhr/htm/recommended_rank_document_list$list_status_approved','Approved');
uis.lang_en('#a:/vhr/htm/recommended_rank_document_list$list_status_new','New');
uis.lang_en('#a:/vhr/htm/recommended_rank_document_list$list_status_set_training','To set Training');
uis.lang_en('#a:/vhr/htm/recommended_rank_document_list$list_status_training','To Training');
uis.lang_en('#a:/vhr/htm/recommended_rank_document_list$list_status_waiting','Waiting');
uis.lang_en('#a:/vhr/htm/recommended_rank_document_list$return_to_set_training','Return To set Training');
uis.lang_en('#a:/vhr/htm/recommended_rank_document_list$return_to_training','Return To Training');
uis.lang_en('#a:/vhr/htm/recommended_rank_document_list$return_to_waiting','Return to waiting');
uis.lang_en('#a:/vhr/htm/recommended_rank_document_list$run','Generate');
uis.lang_en('#a:/vhr/htm/recommended_rank_document_list$to_approved','Approve');
uis.lang_en('#a:/vhr/htm/recommended_rank_document_list$to_new','New');
uis.lang_en('#a:/vhr/htm/recommended_rank_document_list$to_set_training','To set Training');
uis.lang_en('#a:/vhr/htm/recommended_rank_document_list$to_training','To Training');
uis.lang_en('#a:/vhr/htm/recommended_rank_document_list$to_waiting','Send');
uis.lang_en('#a:/vhr/htm/recommended_rank_document_list$view','View');
uis.lang_en('#a:/vhr/htm/recommended_rank_document_list$view_journal','View HR document');
uis.lang_en('#f:/vhr/htm/recommended_rank_document_list','Rank Promotion');
uis.lang_en('ui-vhr549:change date','Change Date');
uis.lang_en('ui-vhr549:division name','Department');
uis.lang_en('ui-vhr549:division name: $1{division_name}','Division: $1');
uis.lang_en('ui-vhr549:document date: $1{document_date}','Date: $1');
uis.lang_en('ui-vhr549:document number: $1{document_number}','Number: $1');
uis.lang_en('ui-vhr549:document status: $1{document_status}','Status: $1');
uis.lang_en('ui-vhr549:from rank','Previous Rank');
uis.lang_en('ui-vhr549:increment status','Increment status');
uis.lang_en('ui-vhr549:job name','Job');
uis.lang_en('ui-vhr549:new wage','New Salary');
uis.lang_en('ui-vhr549:note','Note');
uis.lang_en('ui-vhr549:note: $1{note}','Description: $1');
uis.lang_en('ui-vhr549:old wage','Previous Salary');
uis.lang_en('ui-vhr549:order_no','№');
uis.lang_en('ui-vhr549:staff name','Employee');
uis.lang_en('ui-vhr549:to rank','New Rank');
uis.lang_en('ui-vhr549:total:','Total:');
commit;
end;
/
