prompt PATH TRANSLATE /vhr/rep/hpr/payroll_book
begin
uis.lang_uz('#a:/vhr/rep/hpr/payroll_book$select_job','Lavozim tanlash');
uis.lang_uz('#a:/vhr/rep/hpr/payroll_book$select_staffs','Xodimlarni tanlash');
uis.lang_uz('#f:/vhr/rep/hpr/payroll_book','Ish haqi hisoblanishi hisoboti');
uis.lang_uz('ui-vhr217:accrued, $1{currency}','Hisoblandi, $1');
uis.lang_uz('ui-vhr217:advance payment','Avans');
uis.lang_uz('ui-vhr217:begin date','Hisobot davri boshi');
uis.lang_uz('ui-vhr217:credit','Qarz');
uis.lang_uz('ui-vhr217:date','Sana');
uis.lang_uz('ui-vhr217:days','kunlar');
uis.lang_uz('ui-vhr217:deducted, $1{currency}','Ushlab qolindi, $1');
uis.lang_uz('ui-vhr217:divisions','Bo''limlar');
uis.lang_uz('ui-vhr217:divisions: $1{division_names}','Bo''limlar: $1');
uis.lang_uz('ui-vhr217:end date','Hisobot davri oxiri');
uis.lang_uz('ui-vhr217:fact days','Ishlangan kunlar');
uis.lang_uz('ui-vhr217:fact hours','Ishlangan soatlar');
uis.lang_uz('ui-vhr217:filial name','Tashkilot');
uis.lang_uz('ui-vhr217:final balance','Davr oxiriga nisbatan saldo');
uis.lang_uz('ui-vhr217:given year income','Yil boshidan boshlab daromad');
uis.lang_uz('ui-vhr217:given year income tax','Yil boshidan boshlab daromad solig''i');
uis.lang_uz('ui-vhr217:given year social payment','Yil boshidan boshlab ijtimoiy to''lov');
uis.lang_uz('ui-vhr217:hours','soatlar');
uis.lang_uz('ui-vhr217:iapa','ShJBPH');
uis.lang_uz('ui-vhr217:income tax','Daromad solig''i');
uis.lang_uz('ui-vhr217:initial balance','Davr boshiga nisbatan saldo');
uis.lang_uz('ui-vhr217:job name','Lavozim');
uis.lang_uz('ui-vhr217:name','Nom');
uis.lang_uz('ui-vhr217:npin','JShShIR');
uis.lang_uz('ui-vhr217:order no','Tartib raqami');
uis.lang_uz('ui-vhr217:other accrual','Boshqa hisoblashlar');
uis.lang_uz('ui-vhr217:other deduction','Boshqa ushlab qolishlar');
uis.lang_uz('ui-vhr217:other payments','Boshqalar');
uis.lang_uz('ui-vhr217:payment','To''lovlar');
uis.lang_uz('ui-vhr217:payment, $1{currency}','To''landi, $1');
uis.lang_uz('ui-vhr217:payroll book','Ish haqi hisoblanishi hisoboti');
uis.lang_uz('ui-vhr217:payroll book for $1{month_year}','$1 bo''yicha ish haqi hisoblanishi hisoboti');
uis.lang_uz('ui-vhr217:penalty for absence','Yo''qlik uchun jarima');
uis.lang_uz('ui-vhr217:penalty for day skip','Ish kunini qoldirish uchun jarima');
uis.lang_uz('ui-vhr217:penalty for early output','Erta ketish uchun jarima');
uis.lang_uz('ui-vhr217:penalty for late','Kech kelish uchun jarima');
uis.lang_uz('ui-vhr217:pension payment','Jumladan JShShIR');
uis.lang_uz('ui-vhr217:planned wage, $1{currency}','Rejalashtirilgan ish haqi');
uis.lang_uz('ui-vhr217:rank name','Daraja');
uis.lang_uz('ui-vhr217:social payment','Yagona ijtimoiy to''lov');
uis.lang_uz('ui-vhr217:staff name','Xodim');
uis.lang_uz('ui-vhr217:staff number','Xodim raqami');
uis.lang_uz('ui-vhr217:staffs','Xodimlar');
uis.lang_uz('ui-vhr217:tin','STIR');
uis.lang_uz('ui-vhr217:total accrual','Jami');
uis.lang_uz('ui-vhr217:total deduction','Jami');
uis.lang_uz('ui-vhr217:total payment','Jami to''langan');
uis.lang_uz('ui-vhr217:total:','Jami:');
uis.lang_uz('ui-vhr217:turnout','Ishlangan vaqt');
uis.lang_uz('ui-vhr217:wage','Maosh');
uis.lang_uz('ui-vhr217:wage accrual','Maosh bo''yicha');
uis.lang_uz('ui-vhr217:wage, $1{currency}','Maosh, $1');
commit;
end;
/
