prompt PATH TRANSLATE /vhr/rep/htt/timesheet_with_transfer
begin
uis.lang_en('#a:/vhr/rep/htt/timesheet_with_transfer$select_division_group','Select department group');
uis.lang_en('#a:/vhr/rep/htt/timesheet_with_transfer$select_staff','Select employee');
uis.lang_en('#f:/vhr/rep/htt/timesheet_with_transfer','Attendance Report (T-13)');
uis.lang_en('ui-vhr468:$1/$2','$1/$2');
uis.lang_en('ui-vhr468:absence time','Without reason');
uis.lang_en('ui-vhr468:date','Date');
uis.lang_en('ui-vhr468:day','Day');
uis.lang_en('ui-vhr468:dismissed','DM');
uis.lang_en('ui-vhr468:division','Department');
uis.lang_en('ui-vhr468:division: $1','Department: $1');
uis.lang_en('ui-vhr468:early time','Early Check Out');
uis.lang_en('ui-vhr468:employee: $1','Employee: $1');
uis.lang_en('ui-vhr468:fact','Fact');
uis.lang_en('ui-vhr468:fact time','Worked');
uis.lang_en('ui-vhr468:free time','Off Schedule');
uis.lang_en('ui-vhr468:input','Check In');
uis.lang_en('ui-vhr468:intime','On Time');
uis.lang_en('ui-vhr468:job','Job');
uis.lang_en('ui-vhr468:job: $1','Job: $1');
uis.lang_en('ui-vhr468:late input','Lateness');
uis.lang_en('ui-vhr468:leave','Absence by Reason');
uis.lang_en('ui-vhr468:leave and absence','Absence');
uis.lang_en('ui-vhr468:leave time','By reason');
uis.lang_en('ui-vhr468:location','Location');
uis.lang_en('ui-vhr468:location: $1','Locations: $1');
uis.lang_en('ui-vhr468:manager','Manager');
uis.lang_en('ui-vhr468:manager: $1','Manager: $1');
uis.lang_en('ui-vhr468:name','Full Name');
uis.lang_en('ui-vhr468:not come female','Absent');
uis.lang_en('ui-vhr468:not come male','Absent');
uis.lang_en('ui-vhr468:not come short','X');
uis.lang_en('ui-vhr468:not hired','NH');
uis.lang_en('ui-vhr468:not licensed day','No subscription');
uis.lang_en('ui-vhr468:not licensed short','No subscription');
uis.lang_en('ui-vhr468:order no','№');
uis.lang_en('ui-vhr468:org unit','Org. Unit');
uis.lang_en('ui-vhr468:output','Check Out');
uis.lang_en('ui-vhr468:overtime','Overtime');
uis.lang_en('ui-vhr468:period: $1 - $2','Period: $1 - $2');
uis.lang_en('ui-vhr468:plan','Plan');
uis.lang_en('ui-vhr468:plan time','By plan (hours)');
uis.lang_en('ui-vhr468:plan_time','Standard');
uis.lang_en('ui-vhr468:position: $1','Position: $1');
uis.lang_en('ui-vhr468:rank','Rank');
uis.lang_en('ui-vhr468:rank: $1','Rank: $1');
uis.lang_en('ui-vhr468:rest day','Rest day');
uis.lang_en('ui-vhr468:rest day short','Nwd');
uis.lang_en('ui-vhr468:robot','Staff Unit');
uis.lang_en('ui-vhr468:schedule','Work Schedule');
uis.lang_en('ui-vhr468:schedule: $1','Work Schedule: $1');
uis.lang_en('ui-vhr468:staff number','PersNo');
uis.lang_en('ui-vhr468:staff number: $1','PersNo: $1');
uis.lang_en('ui-vhr468:total','Total');
uis.lang_en('ui-vhr468:total time','Total');
uis.lang_en('ui-vhr468:track schedule','Tracks');
uis.lang_en('ui-vhr468:transfer','TR');
uis.lang_en('ui-vhr468:transfer period','HR Transfer period');
uis.lang_en('ui-vhr468:worked days','Worked Days');
commit;
end;
/
