prompt PATH TRANSLATE /vhr/rep/htt/timesheet
begin
uis.lang_en('#a:/vhr/rep/htt/timesheet$select_division_group','Select department group');
uis.lang_en('#a:/vhr/rep/htt/timesheet$select_staff','Select employee');
uis.lang_en('#f:/vhr/rep/htt/timesheet','Attendance Report');
uis.lang_en('ui-vhr101:$1/$2','$1/$2');
uis.lang_en('ui-vhr101:absence time','Without reason');
uis.lang_en('ui-vhr101:date','Date');
uis.lang_en('ui-vhr101:day','Day');
uis.lang_en('ui-vhr101:dismissed','DM');
uis.lang_en('ui-vhr101:division','Department');
uis.lang_en('ui-vhr101:division: $1','Department: $1');
uis.lang_en('ui-vhr101:early time','Early Check Out');
uis.lang_en('ui-vhr101:employee: $1','Employee: $1');
uis.lang_en('ui-vhr101:fact','Fact');
uis.lang_en('ui-vhr101:fact coef','Worked Coefficient (off-schedule time) %');
uis.lang_en('ui-vhr101:fact time','Worked');
uis.lang_en('ui-vhr101:fact time removed penalty time','Worked hours including fines');
uis.lang_en('ui-vhr101:filial','Organization');
uis.lang_en('ui-vhr101:filial: $1','Organization: $1');
uis.lang_en('ui-vhr101:filials: $1','Organizations: $1');
uis.lang_en('ui-vhr101:free time','Off Schedule');
uis.lang_en('ui-vhr101:input','Check In');
uis.lang_en('ui-vhr101:intime','On Time');
uis.lang_en('ui-vhr101:job','Job');
uis.lang_en('ui-vhr101:job: $1','Job: $1');
uis.lang_en('ui-vhr101:late input','Lateness');
uis.lang_en('ui-vhr101:leave','Absence by Reason');
uis.lang_en('ui-vhr101:leave and absence','Absence');
uis.lang_en('ui-vhr101:leave time','By reason');
uis.lang_en('ui-vhr101:leave time by coef','Leave time by coefficient');
uis.lang_en('ui-vhr101:location','Locations');
uis.lang_en('ui-vhr101:location: $1','Locations: $1');
uis.lang_en('ui-vhr101:manager','Manager');
uis.lang_en('ui-vhr101:manager: $1','Manager: $1');
uis.lang_en('ui-vhr101:name','Full Name');
uis.lang_en('ui-vhr101:not come female','Absent');
uis.lang_en('ui-vhr101:not come male','Absent');
uis.lang_en('ui-vhr101:not come short','X');
uis.lang_en('ui-vhr101:not hired','NH');
uis.lang_en('ui-vhr101:not licensed day','No subscription');
uis.lang_en('ui-vhr101:not licensed short','No subscription');
uis.lang_en('ui-vhr101:order no','№');
uis.lang_en('ui-vhr101:origin penalty early time','Original Fine Early Time');
uis.lang_en('ui-vhr101:origin penalty lack time','Original Fine Lack Time');
uis.lang_en('ui-vhr101:origin penalty late time','Original Fine Late Time');
uis.lang_en('ui-vhr101:origin penalty total','Original Fine Time');
uis.lang_en('ui-vhr101:original penalty early time','Original Fine Early Time');
uis.lang_en('ui-vhr101:original penalty lack time','Original Fine Lack Time');
uis.lang_en('ui-vhr101:original penalty late time','Original Fine Late Time');
uis.lang_en('ui-vhr101:original penalty total time','Original Fine Time');
uis.lang_en('ui-vhr101:output','Check Out');
uis.lang_en('ui-vhr101:overtime','Overtime');
uis.lang_en('ui-vhr101:penalty early time','Fine Early Time');
uis.lang_en('ui-vhr101:penalty lack time','Fine Lack Time');
uis.lang_en('ui-vhr101:penalty late time','Fine Late Time');
uis.lang_en('ui-vhr101:penalty total time','Fine Total Time');
uis.lang_en('ui-vhr101:period: $1 - $2','Period: $1 - $2');
uis.lang_en('ui-vhr101:plan','Plan');
uis.lang_en('ui-vhr101:plan time','By plan');
uis.lang_en('ui-vhr101:plan_time','Standard');
uis.lang_en('ui-vhr101:range date','Dates Range');
uis.lang_en('ui-vhr101:rank','Rank');
uis.lang_en('ui-vhr101:rank: $1','Rank: $1');
uis.lang_en('ui-vhr101:report attendence','Attendance Report');
uis.lang_en('ui-vhr101:rest day','Non-working Day');
uis.lang_en('ui-vhr101:rest day short','Nwd');
uis.lang_en('ui-vhr101:rest free time','Rest Day Work');
uis.lang_en('ui-vhr101:schedule','Work Schedule');
uis.lang_en('ui-vhr101:schedule: $1','Work Schedule: $1');
uis.lang_en('ui-vhr101:select range','Select date range');
uis.lang_en('ui-vhr101:select staffs','Select employees');
uis.lang_en('ui-vhr101:staff number','PersNo');
uis.lang_en('ui-vhr101:staff number: $1','PersNo: $1');
uis.lang_en('ui-vhr101:staffs','Employees');
uis.lang_en('ui-vhr101:total','Total');
uis.lang_en('ui-vhr101:total time','Total');
uis.lang_en('ui-vhr101:track schedule','Tracks');
uis.lang_en('ui-vhr101:when daily hour time less than plan time or when check track is on and not exists check track or when planned marks count more than done marks count','Daily hour time less than plan time or check marks is on and not exists marks or when planned marks count more than done marks count');
uis.lang_en('ui-vhr101:when day is rest day','Rest day');
uis.lang_en('ui-vhr101:when dismissed or not hired','Dismissed or not hired or not scheduled');
uis.lang_en('ui-vhr101:when done marks count more than planned marks count','Done marks count more than planned marks');
uis.lang_en('ui-vhr101:when in rest day have input time and output time','Rest day has input and output time');
uis.lang_en('ui-vhr101:when not license day','Not license day');
uis.lang_en('ui-vhr101:when there is no input and output times for the previous day or when done marks count equal zero','There is no input and output marks or check marks are enabled and there are no completed marks');
uis.lang_en('ui-vhr101:worked coef','Worked Coefficient %');
uis.lang_en('ui-vhr101:worked days','Worked Days');
commit;
end;
/
