prompt PATH TRANSLATE /vhr/hpd/hiring
begin
uis.lang_ru('#a:/vhr/hpd/hiring+add$add_accrual','Создать начисление');
uis.lang_ru('#a:/vhr/hpd/hiring+add$add_deduction','Создать удержание');
uis.lang_ru('#a:/vhr/hpd/hiring+add$add_employee','Создать сотрудника');
uis.lang_ru('#a:/vhr/hpd/hiring+add$add_employment_source','Создать источник занятости');
uis.lang_ru('#a:/vhr/hpd/hiring+add$add_fixed_term_base','Создать основание срочного договора');
uis.lang_ru('#a:/vhr/hpd/hiring+add$add_fte','Создать тип занятости');
uis.lang_ru('#a:/vhr/hpd/hiring+add$add_job','Создать должность');
uis.lang_ru('#a:/vhr/hpd/hiring+add$add_rank','Создать квалификационный разряд');
uis.lang_ru('#a:/vhr/hpd/hiring+add$add_schedule','Создать график работы');
uis.lang_ru('#a:/vhr/hpd/hiring+add$add_wage_scale','Добавить тарифную группу');
uis.lang_ru('#a:/vhr/hpd/hiring+add$select_accrual','Выбрать начисление');
uis.lang_ru('#a:/vhr/hpd/hiring+add$select_deduction','Выбрать удержание');
uis.lang_ru('#a:/vhr/hpd/hiring+add$select_employee','Выбрать сотрудника');
uis.lang_ru('#a:/vhr/hpd/hiring+add$select_employment_source','Выбрать источник занятости');
uis.lang_ru('#a:/vhr/hpd/hiring+add$select_fixed_term_base','Выбрать основание срочного договора');
uis.lang_ru('#a:/vhr/hpd/hiring+add$select_fte','Выбрать тип занятости');
uis.lang_ru('#a:/vhr/hpd/hiring+add$select_job','Выбрать должность');
uis.lang_ru('#a:/vhr/hpd/hiring+add$select_rank','Выбрать квалификационный разряд');
uis.lang_ru('#a:/vhr/hpd/hiring+add$select_robot','Выбрать позицию');
uis.lang_ru('#a:/vhr/hpd/hiring+add$select_schedule','Выбрать график работы');
uis.lang_ru('#a:/vhr/hpd/hiring+add$select_wage_scale','Выбрать тарифную группу');
uis.lang_ru('#a:/vhr/hpd/hiring+edit$add_accrual','Создать начисление');
uis.lang_ru('#a:/vhr/hpd/hiring+edit$add_deduction','Создать удержание');
uis.lang_ru('#a:/vhr/hpd/hiring+edit$add_employee','Создать сотрудника');
uis.lang_ru('#a:/vhr/hpd/hiring+edit$add_employment_source','Создать источник занятости');
uis.lang_ru('#a:/vhr/hpd/hiring+edit$add_fixed_term_base','Создать основание срочного договора');
uis.lang_ru('#a:/vhr/hpd/hiring+edit$add_fte','Создать тип занятости');
uis.lang_ru('#a:/vhr/hpd/hiring+edit$add_job','Создать должность');
uis.lang_ru('#a:/vhr/hpd/hiring+edit$add_rank','Создать квалификационный разряд');
uis.lang_ru('#a:/vhr/hpd/hiring+edit$add_schedule','Создать график работы');
uis.lang_ru('#a:/vhr/hpd/hiring+edit$add_wage_scale','Добавить тарифную группу');
uis.lang_ru('#a:/vhr/hpd/hiring+edit$select_accrual','Выбрать начисление');
uis.lang_ru('#a:/vhr/hpd/hiring+edit$select_deduction','Выбрать удержание');
uis.lang_ru('#a:/vhr/hpd/hiring+edit$select_employee','Выбрать сотрудника');
uis.lang_ru('#a:/vhr/hpd/hiring+edit$select_employment_source','Выбрать источник занятости');
uis.lang_ru('#a:/vhr/hpd/hiring+edit$select_fixed_term_base','Выбрать основание срочного договора');
uis.lang_ru('#a:/vhr/hpd/hiring+edit$select_fte','Выбрать тип занятости');
uis.lang_ru('#a:/vhr/hpd/hiring+edit$select_job','Выбрать должность');
uis.lang_ru('#a:/vhr/hpd/hiring+edit$select_rank','Выбрать квалификационный разряд');
uis.lang_ru('#a:/vhr/hpd/hiring+edit$select_robot','Выбрать позицию');
uis.lang_ru('#a:/vhr/hpd/hiring+edit$select_schedule','Выбрать график работы');
uis.lang_ru('#a:/vhr/hpd/hiring+edit$select_wage_scale','Выбрать тарифную группу');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_add$add_accrual','Создать начисление');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_add$add_deduction','Создать удержание');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_add$add_employee','Создать сотрудника');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_add$add_employment_source','Создать источник занятости');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_add$add_fixed_term_base','Создать основание срочного договора');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_add$add_fte','Создать тип занятости');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_add$add_job','Создать должность');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_add$add_rank','Создать квалификационный разряд');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_add$add_schedule','Создать график работы');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_add$add_wage_scale','Добавить тарифную группу');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_add$hiring_import','Импорт');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_add$select_accrual','Выбрать начисление');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_add$select_deduction','Выбрать удержание');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_add$select_employee','Выбрать сотрудника');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_add$select_employment_source','Выбрать источник занятости');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_add$select_fixed_term_base','Выбрать основание срочного договора');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_add$select_fte','Выбрать тип занятости');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_add$select_job','Выбрать должность');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_add$select_rank','Выбрать квалификационный разряд');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_add$select_robot','Выбрать позицию');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_add$select_schedule','Выбрать график работы');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_add$select_wage_scale','Выбрать тарифную группу');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_edit$add_accrual','Создать начисление');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_edit$add_deduction','Создать удержание');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_edit$add_employee','Создать сотрудника');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_edit$add_employment_source','Создать источник занятости');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_edit$add_fixed_term_base','Создать основание срочного договора');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_edit$add_fte','Создать тип занятости');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_edit$add_job','Создать должность');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_edit$add_rank','Создать квалификационный разряд');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_edit$add_schedule','Создать график работы');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_edit$add_wage_scale','Добавить тарифную группу');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_edit$hiring_import','Импорт');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_edit$select_accrual','Выбрать начисление');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_edit$select_deduction','Выбрать удержание');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_edit$select_employee','Выбрать сотрудника');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_edit$select_employment_source','Выбрать источник занятости');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_edit$select_fixed_term_base','Выбрать основание срочного договора');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_edit$select_fte','Выбрать тип занятости');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_edit$select_job','Выбрать должность');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_edit$select_rank','Выбрать квалификационный разряд');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_edit$select_robot','Выбрать позицию');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_edit$select_schedule','Выбрать график работы');
uis.lang_ru('#a:/vhr/hpd/hiring+multiple_edit$select_wage_scale','Выбрать тарифную группу');
uis.lang_ru('#f:/vhr/hpd/hiring+add','Прием на работу (создание)');
uis.lang_ru('#f:/vhr/hpd/hiring+edit','Прием на работу (изменение)');
uis.lang_ru('#f:/vhr/hpd/hiring+multiple_add','Прием на работу списком (создание)');
uis.lang_ru('#f:/vhr/hpd/hiring+multiple_edit','Прием на работу списком (изменение)');
commit;
end;
/
