prompt PATH TRANSLATE /vhr/hpd/journal_list
begin
uis.lang_ru('#a:/vhr/hpd/journal_list$business_trip_add','Командировка (создание)');
uis.lang_ru('#a:/vhr/hpd/journal_list$business_trip_audit','История изменений');
uis.lang_ru('#a:/vhr/hpd/journal_list$business_trip_edit','Командировка (изменение)');
uis.lang_ru('#a:/vhr/hpd/journal_list$business_trip_multiple_add','Командировка списком (создание)');
uis.lang_ru('#a:/vhr/hpd/journal_list$business_trip_multiple_edit','Командировка списком (изменение)');
uis.lang_ru('#a:/vhr/hpd/journal_list$business_trip_multiple_view','Командировка списком (просмотр)');
uis.lang_ru('#a:/vhr/hpd/journal_list$business_trip_view','Командировка (просмотр)');
uis.lang_ru('#a:/vhr/hpd/journal_list$create_sign_document','Создать документооборот');
uis.lang_ru('#a:/vhr/hpd/journal_list$delete','Удалить');
uis.lang_ru('#a:/vhr/hpd/journal_list$dismissal_add','Увольнение (создание)');
uis.lang_ru('#a:/vhr/hpd/journal_list$dismissal_audit','История изменений');
uis.lang_ru('#a:/vhr/hpd/journal_list$dismissal_edit','Увольнение (изменение)');
uis.lang_ru('#a:/vhr/hpd/journal_list$dismissal_multiple_add','Увольнение списком (создание)');
uis.lang_ru('#a:/vhr/hpd/journal_list$dismissal_multiple_audit','История изменений');
uis.lang_ru('#a:/vhr/hpd/journal_list$dismissal_multiple_edit','Увольнение списком (изменение)');
uis.lang_ru('#a:/vhr/hpd/journal_list$dismissal_multiple_report','Приказ об увольнении (Т-8а)');
uis.lang_ru('#a:/vhr/hpd/journal_list$dismissal_multiple_view','Увольнение списком (просмотр)');
uis.lang_ru('#a:/vhr/hpd/journal_list$dismissal_report','Приказ об увольнении (Т-8)');
uis.lang_ru('#a:/vhr/hpd/journal_list$dismissal_view','Увольнение (просмотр)');
uis.lang_ru('#a:/vhr/hpd/journal_list$hiring_add','Прием на работу (создание)');
uis.lang_ru('#a:/vhr/hpd/journal_list$hiring_audit','История изменений');
uis.lang_ru('#a:/vhr/hpd/journal_list$hiring_contract_add','Прием на договор ГПХ (создание)');
uis.lang_ru('#a:/vhr/hpd/journal_list$hiring_contract_edit','Прием на договор ГПХ (изменить)');
uis.lang_ru('#a:/vhr/hpd/journal_list$hiring_contract_view','Прием на договор ГПХ (просмотр)');
uis.lang_ru('#a:/vhr/hpd/journal_list$hiring_edit','Прием на работу (изменение)');
uis.lang_ru('#a:/vhr/hpd/journal_list$hiring_multiple_add','Прием на работу списком (создание)');
uis.lang_ru('#a:/vhr/hpd/journal_list$hiring_multiple_audit','История изменений');
uis.lang_ru('#a:/vhr/hpd/journal_list$hiring_multiple_edit','Прием на работу списком (изменение)');
uis.lang_ru('#a:/vhr/hpd/journal_list$hiring_multiple_report','Приказ о приеме (Т-1а)');
uis.lang_ru('#a:/vhr/hpd/journal_list$hiring_multiple_view','Прием на работу списоком (просмотр)');
uis.lang_ru('#a:/vhr/hpd/journal_list$hiring_report','Приказ о приеме (Т-1)');
uis.lang_ru('#a:/vhr/hpd/journal_list$hiring_view','Прием на работу (прием)');
uis.lang_ru('#a:/vhr/hpd/journal_list$labor_contract','Трудовой договор');
uis.lang_ru('#a:/vhr/hpd/journal_list$overtime_add','Сверхурочная работа (создание)');
uis.lang_ru('#a:/vhr/hpd/journal_list$overtime_audit','История изменений');
uis.lang_ru('#a:/vhr/hpd/journal_list$overtime_edit','Сверхурочная работа (изменение)');
uis.lang_ru('#a:/vhr/hpd/journal_list$overtime_view','Сверхурочная работа (просмотр)');
uis.lang_ru('#a:/vhr/hpd/journal_list$post','Провести');
uis.lang_ru('#a:/vhr/hpd/journal_list$rank_change_add','Создать изменение разряда');
uis.lang_ru('#a:/vhr/hpd/journal_list$rank_change_audit','История изменения разряда');
uis.lang_ru('#a:/vhr/hpd/journal_list$rank_change_edit','Изменить изменение разряда');
uis.lang_ru('#a:/vhr/hpd/journal_list$rank_change_multiple_add','Изменение разряда списком (создание)');
uis.lang_ru('#a:/vhr/hpd/journal_list$rank_change_multiple_edit','Изменение разряда списком (изменение)');
uis.lang_ru('#a:/vhr/hpd/journal_list$rank_change_multiple_view','Изменение разряда списком (просмотр)');
uis.lang_ru('#a:/vhr/hpd/journal_list$rank_change_view','Изменение разряда (просмотр)');
uis.lang_ru('#a:/vhr/hpd/journal_list$schedule_change_add','Изменение графика работы списком (создание)');
uis.lang_ru('#a:/vhr/hpd/journal_list$schedule_change_audit','История изменений');
uis.lang_ru('#a:/vhr/hpd/journal_list$schedule_change_edit','Изменение графика работы списком (изменение)');
uis.lang_ru('#a:/vhr/hpd/journal_list$schedule_change_view','Изменение графика работы списком (просмотр)');
uis.lang_ru('#a:/vhr/hpd/journal_list$sick_leave_add','Больничный лист (создание)');
uis.lang_ru('#a:/vhr/hpd/journal_list$sick_leave_audit','История изменений');
uis.lang_ru('#a:/vhr/hpd/journal_list$sick_leave_edit','Больничный лист (изменение)');
uis.lang_ru('#a:/vhr/hpd/journal_list$sick_leave_multiple_add','Больничный лист списком (создание)');
uis.lang_ru('#a:/vhr/hpd/journal_list$sick_leave_multiple_audit','Больничный лист списком (история изменений)');
uis.lang_ru('#a:/vhr/hpd/journal_list$sick_leave_multiple_edit','Больничный лист списком (изменение)');
uis.lang_ru('#a:/vhr/hpd/journal_list$sick_leave_multiple_view','Больничный лист списком (просмотр)');
uis.lang_ru('#a:/vhr/hpd/journal_list$sick_leave_view','Больничный лист (просмотр)');
uis.lang_ru('#a:/vhr/hpd/journal_list$timebook_adjustment_add','Корректировка табеля (создание)');
uis.lang_ru('#a:/vhr/hpd/journal_list$timebook_adjustment_audit','История изменений');
uis.lang_ru('#a:/vhr/hpd/journal_list$timebook_adjustment_edit','Корректировка табеля (изменение)');
uis.lang_ru('#a:/vhr/hpd/journal_list$timebook_adjustment_view','Корректировка табеля (просмотр)');
uis.lang_ru('#a:/vhr/hpd/journal_list$to_draft','Документооборот на "Черновик"');
uis.lang_ru('#a:/vhr/hpd/journal_list$to_progress','К подписанию');
uis.lang_ru('#a:/vhr/hpd/journal_list$transfer_add','Кадровый перевод (создание)');
uis.lang_ru('#a:/vhr/hpd/journal_list$transfer_audit','История изменений');
uis.lang_ru('#a:/vhr/hpd/journal_list$transfer_edit','Кадровый перевод (изменение)');
uis.lang_ru('#a:/vhr/hpd/journal_list$transfer_multiple_add','Кадровый перевод списком (создание)');
uis.lang_ru('#a:/vhr/hpd/journal_list$transfer_multiple_audit','История изменений');
uis.lang_ru('#a:/vhr/hpd/journal_list$transfer_multiple_edit','Кадровый перевод списком (изменение)');
uis.lang_ru('#a:/vhr/hpd/journal_list$transfer_multiple_report','Приказ о переводе (Т-5а)');
uis.lang_ru('#a:/vhr/hpd/journal_list$transfer_multiple_view','Кадровый перевод списком (просмотр)');
uis.lang_ru('#a:/vhr/hpd/journal_list$transfer_report','Приказ о переводе (Т-5)');
uis.lang_ru('#a:/vhr/hpd/journal_list$transfer_view','Кадровый перевод (просмотр)');
uis.lang_ru('#a:/vhr/hpd/journal_list$unpost','Отменить');
uis.lang_ru('#a:/vhr/hpd/journal_list$update_sign_document','Обновить документооборот');
uis.lang_ru('#a:/vhr/hpd/journal_list$vacation_add','Отпуск (создание)');
uis.lang_ru('#a:/vhr/hpd/journal_list$vacation_edit','Отпуск (изменение)');
uis.lang_ru('#a:/vhr/hpd/journal_list$vacation_limit_change_add','Создать изменение отпускных дней');
uis.lang_ru('#a:/vhr/hpd/journal_list$vacation_limit_change_edit','Изменить изменение отпускных дней');
uis.lang_ru('#a:/vhr/hpd/journal_list$vacation_limit_change_view','Просмотреть изменение отпускных дней');
uis.lang_ru('#a:/vhr/hpd/journal_list$vacation_multiple_add','Отпуск списком (создание)');
uis.lang_ru('#a:/vhr/hpd/journal_list$vacation_multiple_edit','Отпуск списком (изменение)');
uis.lang_ru('#a:/vhr/hpd/journal_list$vacation_multiple_view','Отпуск списком (просмотр)');
uis.lang_ru('#a:/vhr/hpd/journal_list$vacation_view','Отпуск (просмотр)');
uis.lang_ru('#a:/vhr/hpd/journal_list$wage_change_add','Изменение оплаты труда (создание)');
uis.lang_ru('#a:/vhr/hpd/journal_list$wage_change_audit','История изменений');
uis.lang_ru('#a:/vhr/hpd/journal_list$wage_change_edit','Изменение оплаты труда (изменение)');
uis.lang_ru('#a:/vhr/hpd/journal_list$wage_change_multiple_add','Изменение оплаты труда списком (создание)');
uis.lang_ru('#a:/vhr/hpd/journal_list$wage_change_multiple_audit','История изменений');
uis.lang_ru('#a:/vhr/hpd/journal_list$wage_change_multiple_edit','Изменение оплаты труда списком (изменение)');
uis.lang_ru('#a:/vhr/hpd/journal_list$wage_change_multiple_view','Изменение оплаты труда списком (просмотр)');
uis.lang_ru('#a:/vhr/hpd/journal_list$wage_change_view','Изменение оплаты труда (просмотр)');
uis.lang_ru('#f:/vhr/hpd/journal_list','Все кадровые документы');
commit;
end;
/
