prompt PATH TRANSLATE /vhr/hpd/transfer
begin
uis.lang_ru('#a:/vhr/hpd/transfer+add$add_accrual','Создать начисление');
uis.lang_ru('#a:/vhr/hpd/transfer+add$add_deduction','Создать удержание');
uis.lang_ru('#a:/vhr/hpd/transfer+add$add_fixed_term_base','Создать основание срочного договора');
uis.lang_ru('#a:/vhr/hpd/transfer+add$add_fte','Создать тип занятости');
uis.lang_ru('#a:/vhr/hpd/transfer+add$add_rank','Создать квалификационный разряд');
uis.lang_ru('#a:/vhr/hpd/transfer+add$add_schedule','Создать график работы');
uis.lang_ru('#a:/vhr/hpd/transfer+add$add_wage_scale','Добавить тарифную группу');
uis.lang_ru('#a:/vhr/hpd/transfer+add$select_accrual','Выбрать начисление');
uis.lang_ru('#a:/vhr/hpd/transfer+add$select_deduction','Выбрать удержание');
uis.lang_ru('#a:/vhr/hpd/transfer+add$select_fixed_term_base','Выбрать основание срочного договора');
uis.lang_ru('#a:/vhr/hpd/transfer+add$select_fte','Выбрать тип занятости');
uis.lang_ru('#a:/vhr/hpd/transfer+add$select_rank','Выбрать квалификационный разряд');
uis.lang_ru('#a:/vhr/hpd/transfer+add$select_robot','Выбрать позицию');
uis.lang_ru('#a:/vhr/hpd/transfer+add$select_schedule','Выбрать график работы');
uis.lang_ru('#a:/vhr/hpd/transfer+add$select_staff','Выбрать сотрудника');
uis.lang_ru('#a:/vhr/hpd/transfer+add$select_wage_scale','Выбрать тарифную группу');
uis.lang_ru('#a:/vhr/hpd/transfer+edit$add_accrual','Создать начисление');
uis.lang_ru('#a:/vhr/hpd/transfer+edit$add_deduction','Создать удержание');
uis.lang_ru('#a:/vhr/hpd/transfer+edit$add_fixed_term_base','Создать основание срочного договора');
uis.lang_ru('#a:/vhr/hpd/transfer+edit$add_fte','Создать тип занятости');
uis.lang_ru('#a:/vhr/hpd/transfer+edit$add_rank','Создать квалификационный разряд');
uis.lang_ru('#a:/vhr/hpd/transfer+edit$add_schedule','Создать график работы');
uis.lang_ru('#a:/vhr/hpd/transfer+edit$add_wage_scale','Добавить тарифную группу');
uis.lang_ru('#a:/vhr/hpd/transfer+edit$select_accrual','Выбрать начисление');
uis.lang_ru('#a:/vhr/hpd/transfer+edit$select_deduction','Выбрать удержание');
uis.lang_ru('#a:/vhr/hpd/transfer+edit$select_fixed_term_base','Выбрать основание срочного договора');
uis.lang_ru('#a:/vhr/hpd/transfer+edit$select_fte','Выбрать тип занятости');
uis.lang_ru('#a:/vhr/hpd/transfer+edit$select_rank','Выбрать квалификационный разряд');
uis.lang_ru('#a:/vhr/hpd/transfer+edit$select_robot','Выбрать позицию');
uis.lang_ru('#a:/vhr/hpd/transfer+edit$select_schedule','Выбрать график работы');
uis.lang_ru('#a:/vhr/hpd/transfer+edit$select_staff','Выбрать сотрудника');
uis.lang_ru('#a:/vhr/hpd/transfer+edit$select_wage_scale','Выбрать тарифную группу');
uis.lang_ru('#a:/vhr/hpd/transfer+multiple_add$add_accrual','Создать начисление');
uis.lang_ru('#a:/vhr/hpd/transfer+multiple_add$add_deduction','Создать удержание');
uis.lang_ru('#a:/vhr/hpd/transfer+multiple_add$add_fixed_term_base','Создать основание срочного договора');
uis.lang_ru('#a:/vhr/hpd/transfer+multiple_add$add_fte','Создать тип занятости');
uis.lang_ru('#a:/vhr/hpd/transfer+multiple_add$add_rank','Создать квалификационный разряд');
uis.lang_ru('#a:/vhr/hpd/transfer+multiple_add$add_schedule','Создать график работы');
uis.lang_ru('#a:/vhr/hpd/transfer+multiple_add$add_wage_scale','Добавить тарифную группу');
uis.lang_ru('#a:/vhr/hpd/transfer+multiple_add$select_accrual','Выбрать начисление');
uis.lang_ru('#a:/vhr/hpd/transfer+multiple_add$select_deduction','Выбрать удержание');
uis.lang_ru('#a:/vhr/hpd/transfer+multiple_add$select_fixed_term_base','Выбрать основание срочного договора');
uis.lang_ru('#a:/vhr/hpd/transfer+multiple_add$select_fte','Выбрать тип занятости');
uis.lang_ru('#a:/vhr/hpd/transfer+multiple_add$select_rank','Выбрать квалификационный разряд');
uis.lang_ru('#a:/vhr/hpd/transfer+multiple_add$select_robot','Выбрать позицию');
uis.lang_ru('#a:/vhr/hpd/transfer+multiple_add$select_schedule','Выбрать график работы');
uis.lang_ru('#a:/vhr/hpd/transfer+multiple_add$select_staff','Выбрать сотрудника');
uis.lang_ru('#a:/vhr/hpd/transfer+multiple_add$select_wage_scale','Выбрать тарифную группу');
uis.lang_ru('#a:/vhr/hpd/transfer+multiple_edit$add_fixed_term_base','Создать основание срочного договора');
uis.lang_ru('#a:/vhr/hpd/transfer+multiple_edit$add_fte','Создать тип занятости');
uis.lang_ru('#a:/vhr/hpd/transfer+multiple_edit$add_oper_type','Создать начисление');
uis.lang_ru('#a:/vhr/hpd/transfer+multiple_edit$add_rank','Создать квалификационный разряд');
uis.lang_ru('#a:/vhr/hpd/transfer+multiple_edit$add_schedule','Создать график работы');
uis.lang_ru('#a:/vhr/hpd/transfer+multiple_edit$add_wage_scale','Добавить тарифную группу');
uis.lang_ru('#a:/vhr/hpd/transfer+multiple_edit$select_accrual','Выбрать начисление');
uis.lang_ru('#a:/vhr/hpd/transfer+multiple_edit$select_deduction','Выбрать удержание');
uis.lang_ru('#a:/vhr/hpd/transfer+multiple_edit$select_fixed_term_base','Выбрать основание срочного договора');
uis.lang_ru('#a:/vhr/hpd/transfer+multiple_edit$select_fte','Выбрать тип занятости');
uis.lang_ru('#a:/vhr/hpd/transfer+multiple_edit$select_rank','Выбрать квалификационный разряд');
uis.lang_ru('#a:/vhr/hpd/transfer+multiple_edit$select_robot','Выбрать позицию');
uis.lang_ru('#a:/vhr/hpd/transfer+multiple_edit$select_schedule','Выбрать график работы');
uis.lang_ru('#a:/vhr/hpd/transfer+multiple_edit$select_staff','Выбрать сотрудника');
uis.lang_ru('#a:/vhr/hpd/transfer+multiple_edit$select_wage_scale','Выбрать тарифную группу');
uis.lang_ru('#f:/vhr/hpd/transfer+add','Кадровый перевод (создание)');
uis.lang_ru('#f:/vhr/hpd/transfer+edit','Кадровый перевод (изменение)');
uis.lang_ru('#f:/vhr/hpd/transfer+multiple_add','Кадровый перевод списком (создание)');
uis.lang_ru('#f:/vhr/hpd/transfer+multiple_edit','Кадровый перевод списком (изменение)');
commit;
end;
/
