prompt PATH TRANSLATE /vhr/rep/hpr/payroll_book
begin
uis.lang_en('#a:/vhr/rep/hpr/payroll_book$select_job','Select job');
uis.lang_en('#a:/vhr/rep/hpr/payroll_book$select_staffs','Select employee');
uis.lang_en('#f:/vhr/rep/hpr/payroll_book','Payroll Book');
uis.lang_en('ui-vhr217:accrued, $1{currency}','Paid: $1');
uis.lang_en('ui-vhr217:advance payment','Advance Amount');
uis.lang_en('ui-vhr217:begin date','Report Start Period');
uis.lang_en('ui-vhr217:credit','Loan');
uis.lang_en('ui-vhr217:date','Date');
uis.lang_en('ui-vhr217:days','days');
uis.lang_en('ui-vhr217:deducted, $1{currency}','Deducted: $1');
uis.lang_en('ui-vhr217:divisions','Departments');
uis.lang_en('ui-vhr217:divisions: $1{division_names}','Department: $1');
uis.lang_en('ui-vhr217:end date','Report End Period');
uis.lang_en('ui-vhr217:fact days','Worked Days');
uis.lang_en('ui-vhr217:fact hours','Worked Hours');
uis.lang_en('ui-vhr217:filial name','Organization');
uis.lang_en('ui-vhr217:final balance','Balance at the end');
uis.lang_en('ui-vhr217:given year income','Income from beginning of year');
uis.lang_en('ui-vhr217:given year income tax','PIT from beginning of year');
uis.lang_en('ui-vhr217:given year social payment','USP from beginning of year');
uis.lang_en('ui-vhr217:hours','hours');
uis.lang_en('ui-vhr217:iapa','IPSA');
uis.lang_en('ui-vhr217:income tax','PIT');
uis.lang_en('ui-vhr217:initial balance','Balance at the beginning');
uis.lang_en('ui-vhr217:job name','Job');
uis.lang_en('ui-vhr217:name','Full Name');
uis.lang_en('ui-vhr217:npin','IPIN');
uis.lang_en('ui-vhr217:order no','No.');
uis.lang_en('ui-vhr217:other accrual','Other Wage Payments');
uis.lang_en('ui-vhr217:other deduction','Other Wage Deduction');
uis.lang_en('ui-vhr217:other payments','Other payments');
uis.lang_en('ui-vhr217:payment','Payment');
uis.lang_en('ui-vhr217:payment, $1{currency}','Payments: $1');
uis.lang_en('ui-vhr217:payroll book','Payroll Book');
uis.lang_en('ui-vhr217:payroll book for $1{month_year}','Payroll Book for $1');
uis.lang_en('ui-vhr217:penalty for absence','Fine for Absence');
uis.lang_en('ui-vhr217:penalty for day skip','Fine for Day skip');
uis.lang_en('ui-vhr217:penalty for early output','Fine for Early Check-Out');
uis.lang_en('ui-vhr217:penalty for late','Fine for Lateness');
uis.lang_en('ui-vhr217:pension payment','Including IPSA');
uis.lang_en('ui-vhr217:planned wage, $1{currency}','Planned Salary');
uis.lang_en('ui-vhr217:rank name','Rank');
uis.lang_en('ui-vhr217:social payment','USP');
uis.lang_en('ui-vhr217:staff name','Employee');
uis.lang_en('ui-vhr217:staff number','PersNo');
uis.lang_en('ui-vhr217:staffs','Employees');
uis.lang_en('ui-vhr217:tin','TIN');
uis.lang_en('ui-vhr217:total accrual','Total');
uis.lang_en('ui-vhr217:total deduction','Total');
uis.lang_en('ui-vhr217:total payment','Total payment');
uis.lang_en('ui-vhr217:total:','Total');
uis.lang_en('ui-vhr217:turnout','Worked');
uis.lang_en('ui-vhr217:wage','Salary');
uis.lang_en('ui-vhr217:wage accrual','By Salary');
uis.lang_en('ui-vhr217:wage, $1{currency}','Salary: $1');
commit;
end;
/
