prompt PATH TRANSLATE /vhr/rep/href/employee_by_gender
begin
uis.lang_en('#a:/vhr/rep/href/employee_by_gender$select_edu_stage','Select education type');
uis.lang_en('#a:/vhr/rep/href/employee_by_gender$select_rank','Select qualification rank');
uis.lang_en('#f:/vhr/rep/href/employee_by_gender','Report by employee gender division');
uis.lang_en('ui-vhr291:... others','and others');
uis.lang_en('ui-vhr291:age','Age');
uis.lang_en('ui-vhr291:age range title','Report by employee gender division (age)');
uis.lang_en('ui-vhr291:age ranges','Age');
uis.lang_en('ui-vhr291:birthday','Birth Date');
uis.lang_en('ui-vhr291:count','Qty');
uis.lang_en('ui-vhr291:count %','Qty %');
uis.lang_en('ui-vhr291:count female','Women');
uis.lang_en('ui-vhr291:count male','Men');
uis.lang_en('ui-vhr291:date $1','Date: $1');
uis.lang_en('ui-vhr291:division','Department');
uis.lang_en('ui-vhr291:divisions: $1','Department: $1');
uis.lang_en('ui-vhr291:edu stages','Education Type');
uis.lang_en('ui-vhr291:educ title','Report by employee gender division (education type)');
uis.lang_en('ui-vhr291:eduction stage : $1','Education Type: $1');
uis.lang_en('ui-vhr291:experience range title','Report by employee gender division (experience)');
uis.lang_en('ui-vhr291:female','Female');
uis.lang_en('ui-vhr291:from $1 ages','from $1 year old');
uis.lang_en('ui-vhr291:from $1 experiences','from $1 year old');
uis.lang_en('ui-vhr291:from $1 to $2 ages','from $1 to $2 year old');
uis.lang_en('ui-vhr291:from $1 to $2 experiences','from $1 to $2 year old');
uis.lang_en('ui-vhr291:gender','Gender');
uis.lang_en('ui-vhr291:hiring_date','Hiring Date');
uis.lang_en('ui-vhr291:job','Job');
uis.lang_en('ui-vhr291:male','Male');
uis.lang_en('ui-vhr291:month','Month');
uis.lang_en('ui-vhr291:name','Employee');
uis.lang_en('ui-vhr291:rank : $1','Qualification ranks: $1');
uis.lang_en('ui-vhr291:rank title','Report by employee gender division (qualification rank)');
uis.lang_en('ui-vhr291:ranks','Rank');
uis.lang_en('ui-vhr291:run_header: range not found, type=$1','There must be at least one period!');
uis.lang_en('ui-vhr291:some days ago','several days ago');
uis.lang_en('ui-vhr291:to $1 ages','to $1 year old');
uis.lang_en('ui-vhr291:to $1 experiences','to $1 year old');
uis.lang_en('ui-vhr291:total','Total');
uis.lang_en('ui-vhr291:wage','Salary');
uis.lang_en('ui-vhr291:wage %','Salary %');
uis.lang_en('ui-vhr291:wage female','Salary');
uis.lang_en('ui-vhr291:wage male','Salary');
uis.lang_en('ui-vhr291:work ranges','Experience');
uis.lang_en('ui-vhr291:work_month','Experience');
uis.lang_en('ui-vhr291:year','year');
commit;
end;
/
