prompt PATH TRANSLATE /vhr/rep/htt/timesheet_with_transfer
begin
uis.lang_uz('#a:/vhr/rep/htt/timesheet_with_transfer$select_division_group','Bo''lim guruhi tanlash');
uis.lang_uz('#a:/vhr/rep/htt/timesheet_with_transfer$select_staff','Xodim tanlash');
uis.lang_uz('#f:/vhr/rep/htt/timesheet_with_transfer','Xodimlar davomati hisoboti (T-13)');
uis.lang_uz('ui-vhr468:$1/$2','$1/$2');
uis.lang_uz('ui-vhr468:absence time','Sababsiz');
uis.lang_uz('ui-vhr468:date','Sana');
uis.lang_uz('ui-vhr468:day','Kun');
uis.lang_uz('ui-vhr468:dismissed','B');
uis.lang_uz('ui-vhr468:division','Bo''lim');
uis.lang_uz('ui-vhr468:division: $1','Bo''lim: $1');
uis.lang_uz('ui-vhr468:early time','Erta ketish');
uis.lang_uz('ui-vhr468:employee: $1','Xodim: $1');
uis.lang_uz('ui-vhr468:fact','Ishlangan vaqt');
uis.lang_uz('ui-vhr468:fact time','Ishlangan vaqt');
uis.lang_uz('ui-vhr468:free time','Ishdan tashqari');
uis.lang_uz('ui-vhr468:input','Kirish');
uis.lang_uz('ui-vhr468:intime','O''z vaqtida');
uis.lang_uz('ui-vhr468:job','Lavozim');
uis.lang_uz('ui-vhr468:job: $1','Lavozim: $1');
uis.lang_uz('ui-vhr468:late input','Kech kelish');
uis.lang_uz('ui-vhr468:leave','Sababli yo''qlik');
uis.lang_uz('ui-vhr468:leave and absence','Yo''qlik');
uis.lang_uz('ui-vhr468:leave time','Sabab bo''yicha');
uis.lang_uz('ui-vhr468:location','Joylashuv');
uis.lang_uz('ui-vhr468:location: $1','Joylashuvlar: $1');
uis.lang_uz('ui-vhr468:manager','Rahbar');
uis.lang_uz('ui-vhr468:manager: $1','Rahbar: $1');
uis.lang_uz('ui-vhr468:name','Xodim');
uis.lang_uz('ui-vhr468:not come female','Kelmadi');
uis.lang_uz('ui-vhr468:not come male','Kelmadi');
uis.lang_uz('ui-vhr468:not come short','X');
uis.lang_uz('ui-vhr468:not hired','N');
uis.lang_uz('ui-vhr468:not licensed day','Obuna yo‘q');
uis.lang_uz('ui-vhr468:not licensed short','Obuna yo‘q');
uis.lang_uz('ui-vhr468:order no','Tartib raqami');
uis.lang_uz('ui-vhr468:output','Chiqish');
uis.lang_uz('ui-vhr468:overtime','Qo''shimcha ish');
uis.lang_uz('ui-vhr468:period: $1 - $2','Davr: $1 - $2');
uis.lang_uz('ui-vhr468:plan','Reja');
uis.lang_uz('ui-vhr468:plan time','Reja bo''yicha soatlar');
uis.lang_uz('ui-vhr468:plan_time','Reja bo''yicha soatlar');
uis.lang_uz('ui-vhr468:position: $1','Ish o''rni: $1');
uis.lang_uz('ui-vhr468:rank','Daraja');
uis.lang_uz('ui-vhr468:rank: $1','Daraja: $1');
uis.lang_uz('ui-vhr468:rest day','Dam olish kuni');
uis.lang_uz('ui-vhr468:rest day short','D');
uis.lang_uz('ui-vhr468:robot','Ish o''rni');
uis.lang_uz('ui-vhr468:schedule','Ish jadvali');
uis.lang_uz('ui-vhr468:schedule: $1','Ish jadvali: $1');
uis.lang_uz('ui-vhr468:staff number','Xodim raqami');
uis.lang_uz('ui-vhr468:staff number: $1','Xodim raqami: $1');
uis.lang_uz('ui-vhr468:total','Jami');
uis.lang_uz('ui-vhr468:total time','Jami');
uis.lang_uz('ui-vhr468:track schedule','Belgilashlar');
uis.lang_uz('ui-vhr468:transfer','Ish o''rnini o''zgartirish');
uis.lang_uz('ui-vhr468:transfer period','Ish o''rni o''zgargan davr');
uis.lang_uz('ui-vhr468:worked days','Ishlangan kunlar');
commit;
end;
/
