prompt PATH TRANSLATE /vhr/rep/htt/timesheet
begin
uis.lang_uz('#a:/vhr/rep/htt/timesheet$select_division_group','Bo''lim guruhi tanlash');
uis.lang_uz('#a:/vhr/rep/htt/timesheet$select_staff','Xodim tanlash');
uis.lang_uz('#f:/vhr/rep/htt/timesheet','Xodimlar davomati hisoboti');
uis.lang_uz('ui-vhr101:$1/$2','$1/$2');
uis.lang_uz('ui-vhr101:absence time','Sababsiz');
uis.lang_uz('ui-vhr101:date','Sana');
uis.lang_uz('ui-vhr101:day','Kun');
uis.lang_uz('ui-vhr101:dismissed','B');
uis.lang_uz('ui-vhr101:division','Bo''lim');
uis.lang_uz('ui-vhr101:division: $1','Bo''lim: $1');
uis.lang_uz('ui-vhr101:early time','Erta ketish');
uis.lang_uz('ui-vhr101:employee: $1','Xodim: $1');
uis.lang_uz('ui-vhr101:fact','Ishlangan vaqt');
uis.lang_uz('ui-vhr101:fact coef','Ishlangan vaqt koeffitsienti (ish vaqtidan tashqari) %');
uis.lang_uz('ui-vhr101:fact time','Ishlangan vaqt');
uis.lang_uz('ui-vhr101:fact time removed penalty time','Jarimalar hisobga olingandagi ishlangan vaqt');
uis.lang_uz('ui-vhr101:filial','Tashkilot');
uis.lang_uz('ui-vhr101:filial: $1','Tashkilot: $1');
uis.lang_uz('ui-vhr101:filials: $1','Tashkilotlar: $1');
uis.lang_uz('ui-vhr101:free time','Ishdan tashqari');
uis.lang_uz('ui-vhr101:input','Kirish');
uis.lang_uz('ui-vhr101:intime','O''z vaqtida');
uis.lang_uz('ui-vhr101:job','Lavozim');
uis.lang_uz('ui-vhr101:job: $1','Lavozim: $1');
uis.lang_uz('ui-vhr101:late input','Kech kelish');
uis.lang_uz('ui-vhr101:leave','Sababli yo''qlik');
uis.lang_uz('ui-vhr101:leave and absence','Yo''qlik');
uis.lang_uz('ui-vhr101:leave time','Sabab bo''yicha');
uis.lang_uz('ui-vhr101:leave time by coef','Yo''qlik vaqtini koeffitsienti bilan ko''rsatish');
uis.lang_uz('ui-vhr101:location','Joylashuv');
uis.lang_uz('ui-vhr101:location: $1','Joylashuvlar: $1');
uis.lang_uz('ui-vhr101:manager','Rahbar');
uis.lang_uz('ui-vhr101:manager: $1','Rahbar: $1');
uis.lang_uz('ui-vhr101:name','Nom');
uis.lang_uz('ui-vhr101:not come female','Kelmadi');
uis.lang_uz('ui-vhr101:not come male','Kelmadi');
uis.lang_uz('ui-vhr101:not come short','X');
uis.lang_uz('ui-vhr101:not hired','N');
uis.lang_uz('ui-vhr101:not licensed day','Obuna yo‘q');
uis.lang_uz('ui-vhr101:not licensed short','Obuna yo‘q');
uis.lang_uz('ui-vhr101:order no','Tartib raqami');
uis.lang_uz('ui-vhr101:origin penalty early time','Erta ketish uchun asl jarima vaqti');
uis.lang_uz('ui-vhr101:origin penalty lack time','Yo''qlik uchun asl jarima vaqti');
uis.lang_uz('ui-vhr101:origin penalty late time','Kech kelish uchun asl jarima vaqti');
uis.lang_uz('ui-vhr101:origin penalty total','Asl jarima vaqti');
uis.lang_uz('ui-vhr101:original penalty early time','Erta ketish uchun asl jarima vaqti');
uis.lang_uz('ui-vhr101:original penalty lack time','Yo''qlik uchun asl jarima vaqti');
uis.lang_uz('ui-vhr101:original penalty late time','Kech kelish uchun asl jarima vaqti');
uis.lang_uz('ui-vhr101:original penalty total time','Asl jarima vaqti');
uis.lang_uz('ui-vhr101:output','Chiqish');
uis.lang_uz('ui-vhr101:overtime','Qo''shimcha ish');
uis.lang_uz('ui-vhr101:penalty early time','Erta ketish uchun jarima vaqti');
uis.lang_uz('ui-vhr101:penalty lack time','Yo''qlik uchun jarima vaqti');
uis.lang_uz('ui-vhr101:penalty late time','Kech kelish uchun jarima vaqti');
uis.lang_uz('ui-vhr101:penalty total time','Jarima vaqti');
uis.lang_uz('ui-vhr101:period: $1 - $2','Davr: $1 - $2');
uis.lang_uz('ui-vhr101:plan','Reja');
uis.lang_uz('ui-vhr101:plan time','Reja bo''yicha soatlar');
uis.lang_uz('ui-vhr101:plan_time','Reja bo''yicha soatlar');
uis.lang_uz('ui-vhr101:range date','Sanalar diapazoni');
uis.lang_uz('ui-vhr101:rank','Daraja');
uis.lang_uz('ui-vhr101:rank: $1','Daraja: $1');
uis.lang_uz('ui-vhr101:report attendence','Davomat hisoboti');
uis.lang_uz('ui-vhr101:rest day','Dam olish kuni');
uis.lang_uz('ui-vhr101:rest day short','D');
uis.lang_uz('ui-vhr101:rest free time','Dam olish kunlaridagi ish vaqti');
uis.lang_uz('ui-vhr101:schedule','Ish jadvali');
uis.lang_uz('ui-vhr101:schedule: $1','Ish jadvali: $1');
uis.lang_uz('ui-vhr101:select range','Sanalar diapazonini tanlang');
uis.lang_uz('ui-vhr101:select staffs','Xodimlarni tanlang');
uis.lang_uz('ui-vhr101:staff number','Xodim raqami');
uis.lang_uz('ui-vhr101:staff number: $1','Xodim raqami: $1');
uis.lang_uz('ui-vhr101:staffs','Xodimlar');
uis.lang_uz('ui-vhr101:total','Jami');
uis.lang_uz('ui-vhr101:total time','Jami');
uis.lang_uz('ui-vhr101:track schedule','Belgilashlar');
uis.lang_uz('ui-vhr101:worked coef','Ishlangan vaqt koeffitsienti (%)');
uis.lang_uz('ui-vhr101:worked days','Ishlangan kunlar');
commit;
end;
/
