prompt PATH TRANSLATE /vhr/hpd/hiring
begin
uis.lang_uz('#a:/vhr/hpd/hiring+add$add_accrual','Hisoblash yaratish');
uis.lang_uz('#a:/vhr/hpd/hiring+add$add_deduction','Ushlab qolish yaratish');
uis.lang_uz('#a:/vhr/hpd/hiring+add$add_employee','Xodim yaratish');
uis.lang_uz('#a:/vhr/hpd/hiring+add$add_employment_source','Bandlik manbasi yaratish');
uis.lang_uz('#a:/vhr/hpd/hiring+add$add_fixed_term_base','Muddatli sharnoma asosini yaratish');
uis.lang_uz('#a:/vhr/hpd/hiring+add$add_fte','Ish vaqti turi qo''shish');
uis.lang_uz('#a:/vhr/hpd/hiring+add$add_job','Lavozim qo''shish');
uis.lang_uz('#a:/vhr/hpd/hiring+add$add_rank','Daraja qo''shish');
uis.lang_uz('#a:/vhr/hpd/hiring+add$add_schedule','Ish jadvali qo''shish');
uis.lang_uz('#a:/vhr/hpd/hiring+add$add_wage_scale','Tarif setkasi qo''shish');
uis.lang_uz('#a:/vhr/hpd/hiring+add$select_accrual','Hisoblashni tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+add$select_deduction','Ushlab qolishni tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+add$select_employee','Xodimni tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+add$select_employment_source','Bandlik manbasi tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+add$select_fixed_term_base','Muddatli sharnoma asosini tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+add$select_fte','Ish vaqti turi tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+add$select_job','Lavozim tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+add$select_rank','Daraja tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+add$select_robot','Ish o''rni tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+add$select_schedule','Ish jadvali tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+add$select_wage_scale','Tarif setkasini tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+edit$add_accrual','Hisoblash yaratish');
uis.lang_uz('#a:/vhr/hpd/hiring+edit$add_deduction','Ushlab qolish yaratish');
uis.lang_uz('#a:/vhr/hpd/hiring+edit$add_employee','Xodim yaratish');
uis.lang_uz('#a:/vhr/hpd/hiring+edit$add_employment_source','Bandlik manbasi yaratish');
uis.lang_uz('#a:/vhr/hpd/hiring+edit$add_fixed_term_base','Muddatli sharnoma asosini yaratish');
uis.lang_uz('#a:/vhr/hpd/hiring+edit$add_fte','Ish vaqti turi qo''shish');
uis.lang_uz('#a:/vhr/hpd/hiring+edit$add_job','Lavozim qo''shish');
uis.lang_uz('#a:/vhr/hpd/hiring+edit$add_rank','Daraja qo''shish');
uis.lang_uz('#a:/vhr/hpd/hiring+edit$add_schedule','Ish jadvali qo''shish');
uis.lang_uz('#a:/vhr/hpd/hiring+edit$add_wage_scale','Tarif setkasi qo''shish');
uis.lang_uz('#a:/vhr/hpd/hiring+edit$select_accrual','Hisoblashni tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+edit$select_deduction','Ushlab qolishni tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+edit$select_employee','Xodimni tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+edit$select_employment_source','Bandlik manbasi tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+edit$select_fixed_term_base','Muddatli sharnoma asosini tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+edit$select_fte','Ish vaqti turi tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+edit$select_job','Lavozim tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+edit$select_rank','Daraja tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+edit$select_robot','Ish o''rni tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+edit$select_schedule','Ish jadvali tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+edit$select_wage_scale','Tarif setkasini tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_add$add_accrual','Hisoblash yaratish');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_add$add_deduction','Ushlab qolish yaratish');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_add$add_employee','Xodim yaratish');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_add$add_employment_source','Bandlik manbasi yaratish');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_add$add_fixed_term_base','Muddatli sharnoma asosini yaratish');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_add$add_fte','Ish vaqti turi qo''shish');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_add$add_job','Lavozim qo''shish');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_add$add_rank','Daraja qo''shish');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_add$add_schedule','Ish jadvali qo''shish');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_add$add_wage_scale','Tarif setkasi qo''shish');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_add$hiring_import','Import');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_add$select_accrual','Hisoblashni tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_add$select_deduction','Ushlab qolishni tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_add$select_employee','Xodimni tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_add$select_employment_source','Bandlik manbasi tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_add$select_fixed_term_base','Muddatli sharnoma asosini tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_add$select_fte','Ish vaqti turi tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_add$select_job','Lavozim tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_add$select_rank','Daraja tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_add$select_robot','Ish o''rni tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_add$select_schedule','Ish jadvali tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_add$select_wage_scale','Tarif setkasini tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_edit$add_accrual','Hisoblash yaratish');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_edit$add_deduction','Ushlab qolish yaratish');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_edit$add_employee','Xodim yaratish');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_edit$add_employment_source','Bandlik manbasi yaratish');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_edit$add_fixed_term_base','Muddatli sharnoma asosini yaratish');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_edit$add_fte','Ish vaqti turi qo''shish');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_edit$add_job','Lavozim qo''shish');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_edit$add_rank','Daraja qo''shish');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_edit$add_schedule','Ish jadvali qo''shish');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_edit$add_wage_scale','Tarif setkasi qo''shish');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_edit$hiring_import','Import');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_edit$select_accrual','Hisoblashni tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_edit$select_deduction','Ushlab qolishni tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_edit$select_employee','Xodimni tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_edit$select_employment_source','Bandlik manbasi tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_edit$select_fixed_term_base','Muddatli sharnoma asosini tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_edit$select_fte','Ish vaqti turi tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_edit$select_job','Lavozim tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_edit$select_rank','Daraja tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_edit$select_robot','Ish o''rni tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_edit$select_schedule','Ish jadvali tanlash');
uis.lang_uz('#a:/vhr/hpd/hiring+multiple_edit$select_wage_scale','Tarif setkasini tanlash');
uis.lang_uz('#f:/vhr/hpd/hiring+add','Ishga qabul qilish (yaratish)');
uis.lang_uz('#f:/vhr/hpd/hiring+edit','Ishga qabul qilish (tahrirlash)');
uis.lang_uz('#f:/vhr/hpd/hiring+multiple_add','Ro''yxat bilan ishga qabul qilish (yaratish)');
uis.lang_uz('#f:/vhr/hpd/hiring+multiple_edit','Ro''yxat bilan ishga qabul qilish (tahrirlash)');
commit;
end;
/
