prompt PATH TRANSLATE /vhr/hpd/journal_list
begin
uis.lang_uz('#a:/vhr/hpd/journal_list$business_trip_add','Ish safari (yaratish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$business_trip_audit','Ish safari / O''zgarishlar tarixi');
uis.lang_uz('#a:/vhr/hpd/journal_list$business_trip_edit','Ish safari (tahrirlash)');
uis.lang_uz('#a:/vhr/hpd/journal_list$business_trip_multiple_add','Ro''yxat bilan ish safari (yaratish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$business_trip_multiple_edit','Ro''yxat bilan ish safari (tahrirlash)');
uis.lang_uz('#a:/vhr/hpd/journal_list$business_trip_multiple_view','Ro''yhat bilan ish safari (ko''rish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$business_trip_view','Ish safari (ko''rish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$create_sign_document','Ish jarayoni yaratish');
uis.lang_uz('#a:/vhr/hpd/journal_list$delete','O''chirish');
uis.lang_uz('#a:/vhr/hpd/journal_list$dismissal_add','Ishdan bo''shatish (yaratish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$dismissal_audit','Ishdan bo''shatish / O''zgarishlar tarixi');
uis.lang_uz('#a:/vhr/hpd/journal_list$dismissal_edit','Ishdan bo''shatish (tahrirlash)');
uis.lang_uz('#a:/vhr/hpd/journal_list$dismissal_multiple_add','Ro''yxat bilan ishdan bo''shatish (yaratish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$dismissal_multiple_audit','Ro''yxat bilan ishdan bo''shatish / O''zgarishlar tarixi');
uis.lang_uz('#a:/vhr/hpd/journal_list$dismissal_multiple_edit','Ro''yxat bilan ishdan bo''shatish (tahrirlash)');
uis.lang_uz('#a:/vhr/hpd/journal_list$dismissal_multiple_report','Mehnat shartnomasini bekor qilish (T-8a)');
uis.lang_uz('#a:/vhr/hpd/journal_list$dismissal_multiple_view','Ro''yxat bilan ishdan bo''shatish (ko''rish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$dismissal_report','Mehnat shartnomasini bekor qilish (T-8)');
uis.lang_uz('#a:/vhr/hpd/journal_list$dismissal_view','Ishdan bo''shatish (ko''rish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$hiring_add','Ishga qabul qilish (yaratish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$hiring_audit','Ishga qabul qilish / O''zgarishlar tarixi');
uis.lang_uz('#a:/vhr/hpd/journal_list$hiring_contract_add','Fuqarolik-huquqiy tusdagi shartnoma asosida qabul qilish (yaratish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$hiring_contract_edit','Fuqarolik-huquqiy tusdagi shartnoma asosida qabul qilish (tahrirlash)');
uis.lang_uz('#a:/vhr/hpd/journal_list$hiring_contract_view','Fuqarolik-huquqiy tusdagi shartnoma asosida qabul qilish (ko''rish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$hiring_edit','Ishga qabul qilish (tahrirlash)');
uis.lang_uz('#a:/vhr/hpd/journal_list$hiring_multiple_add','Ro''yxat bilan ishga qabul qilish (yaratish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$hiring_multiple_audit','Ro''yxat bilan ishga qabul qilish / O''zgarishlar tarixi');
uis.lang_uz('#a:/vhr/hpd/journal_list$hiring_multiple_edit','Ro''yxat bilan ishga qabul qilish (tahrirlash)');
uis.lang_uz('#a:/vhr/hpd/journal_list$hiring_multiple_report','Ishga qabul qilish buyrug''i (T-1a)');
uis.lang_uz('#a:/vhr/hpd/journal_list$hiring_multiple_view','Ro''yxat bilan ishga qabul qilish (ko''rish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$hiring_report','Ishga qabul qilish buyrug''i (T-1)');
uis.lang_uz('#a:/vhr/hpd/journal_list$hiring_view','Ishga qabul qilish (ko''rish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$labor_contract','Mehnat shartnomasi');
uis.lang_uz('#a:/vhr/hpd/journal_list$overtime_add','Qo''shimcha ish (yaratish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$overtime_audit','Qo''shimcha ish (o''zgarishlar tarixi)');
uis.lang_uz('#a:/vhr/hpd/journal_list$overtime_edit','Qo''shimcha ish (tahrirlash)');
uis.lang_uz('#a:/vhr/hpd/journal_list$overtime_view','Qo''shimcha ish (ko''rish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$post','O''tkazish');
uis.lang_uz('#a:/vhr/hpd/journal_list$rank_change_add','Darajani o''zgartirish (yaratish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$rank_change_audit','Darajani o''zgartirish / O''zgarishlar tarixi');
uis.lang_uz('#a:/vhr/hpd/journal_list$rank_change_edit','Darajani o''zgartirish (tahrirlash)');
uis.lang_uz('#a:/vhr/hpd/journal_list$rank_change_multiple_add','Ro''yxat bilan darajani o''zgartirish (yaratish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$rank_change_multiple_edit','Ro''yxat bilan darajani o''zgartirish (tahrirlash)');
uis.lang_uz('#a:/vhr/hpd/journal_list$rank_change_multiple_view','Ro''yxat bilan darajani o''zgartirish (ko''rish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$rank_change_view','Darajani o''zgartirish (ko''rish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$schedule_change_add','Ro''yxat bilan ish jadvalini o''zgartirish (yaratish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$schedule_change_audit','Ro''yxat bilan ish jadvalini o''zgartirish / O''zgarishlar tarixi');
uis.lang_uz('#a:/vhr/hpd/journal_list$schedule_change_edit','Ro''yxat bilan ish jadvalini o''zgartirish (tahrirlash)');
uis.lang_uz('#a:/vhr/hpd/journal_list$schedule_change_view','Ish jadvalini o''zgartirish (ko''rish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$sick_leave_add','Kasallik varaqasi (yaratish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$sick_leave_audit','Kasallik varaqasi / O''zgarishlar tarixi');
uis.lang_uz('#a:/vhr/hpd/journal_list$sick_leave_edit','Kasallik varaqasi (tahrirlash)');
uis.lang_uz('#a:/vhr/hpd/journal_list$sick_leave_multiple_add','Ro''yhat bilan kasallik varaqasi (yaratish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$sick_leave_multiple_audit','Ro''yhat bilan kasallik varaqasi (o''zgarishlar tarixi)');
uis.lang_uz('#a:/vhr/hpd/journal_list$sick_leave_multiple_edit','Ro''yhat bilan kasallik varaqasi (tahrirlash)');
uis.lang_uz('#a:/vhr/hpd/journal_list$sick_leave_multiple_view','Ro''yhat bilan kasallik varaqasi (ko''rish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$sick_leave_view','Kasallik varaqasi (ko''rish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$timebook_adjustment_add','Tabelni tuzatish (yaratish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$timebook_adjustment_audit','Tabel tuzatishlari (o''zgarishlar tarixi)');
uis.lang_uz('#a:/vhr/hpd/journal_list$timebook_adjustment_edit','Tabelni tuzatish (tahrirlash)');
uis.lang_uz('#a:/vhr/hpd/journal_list$timebook_adjustment_view','Tabelni tuzatish (ko''rish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$to_draft','Qaytarish');
uis.lang_uz('#a:/vhr/hpd/journal_list$to_progress','Imzolash uchun');
uis.lang_uz('#a:/vhr/hpd/journal_list$transfer_add','Ish o''rnini o''zgartirish (yaratish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$transfer_audit','Ish o''rnini o''zgartirish / O''zgarishlar tarixi');
uis.lang_uz('#a:/vhr/hpd/journal_list$transfer_edit','Ish o''rnini o''zgartirish (tahrirlash)');
uis.lang_uz('#a:/vhr/hpd/journal_list$transfer_multiple_add','Ro''yxat bilan ish o''rnini o''zgartirish /  Yaratish');
uis.lang_uz('#a:/vhr/hpd/journal_list$transfer_multiple_audit','Ro''yxat bilan ish o''rnini o''zgartirish /  O''zgarishlar tarixi');
uis.lang_uz('#a:/vhr/hpd/journal_list$transfer_multiple_edit','Ro''yxat bilan ish o''rnini o''zgartirish /  Tahrirlash');
uis.lang_uz('#a:/vhr/hpd/journal_list$transfer_multiple_report','Ro''yxat bilan ish o''rnini o''zgartirish /  Yaratish');
uis.lang_uz('#a:/vhr/hpd/journal_list$transfer_multiple_view','Ro''yxat bilan ish o''rnini o''zgartirish (ko''rish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$transfer_report','Ish o''rnini o''zgartirish buyrug''i (T-5)');
uis.lang_uz('#a:/vhr/hpd/journal_list$transfer_view','Ish o''rnini o''zgartirish (ko''rish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$unpost','Qaytarish');
uis.lang_uz('#a:/vhr/hpd/journal_list$update_sign_document','Ish jarayoni yangilash');
uis.lang_uz('#a:/vhr/hpd/journal_list$vacation_add','Mehnat ta''tili (yaratish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$vacation_edit','Mehnat ta''tili (tahrirlash)');
uis.lang_uz('#a:/vhr/hpd/journal_list$vacation_limit_change_add','Yillik mehnat ta''tili davomiyligi (yaratish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$vacation_limit_change_edit','Yillik mehnat ta''tili davomiyligi (tahrirlash)');
uis.lang_uz('#a:/vhr/hpd/journal_list$vacation_limit_change_view','Yillik mehnat ta''tili davomiyligi (ko''rish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$vacation_multiple_add','Ro''yxat bilan mehnat ta''tili (yaratish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$vacation_multiple_edit','Ro''yxat bilan mehnat ta''tili (tahrirlash)');
uis.lang_uz('#a:/vhr/hpd/journal_list$vacation_multiple_view','Ro''yxat bilan mehnat ta''tili (ko''rish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$vacation_view','Mehnat ta''tili (ko''rish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$wage_change_add','Ish haqini o''zgartirish (yaratish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$wage_change_audit','Ish haqini o''zgartirish / O''zgarishlar tarixi');
uis.lang_uz('#a:/vhr/hpd/journal_list$wage_change_edit','Ish haqini o''zgartirish (tahrirlash)');
uis.lang_uz('#a:/vhr/hpd/journal_list$wage_change_multiple_add','Ro''yxat bilan ish haqini o''zgartirish (yaratish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$wage_change_multiple_audit','Ro''yxat bilan ish haqini o''zgartirish (o''zgarishlar tarixi)');
uis.lang_uz('#a:/vhr/hpd/journal_list$wage_change_multiple_edit','Ro''yxat bilan ish haqini o''zgartirish (tahrirlash)');
uis.lang_uz('#a:/vhr/hpd/journal_list$wage_change_multiple_view','Ro''yxat bilan ish haqini o''zgartirish (ko''rish)');
uis.lang_uz('#a:/vhr/hpd/journal_list$wage_change_view','Ish haqini o''zgartirish (ko''rish)');
uis.lang_uz('#f:/vhr/hpd/journal_list','Kadrlarga oid hujjatlar');
commit;
end;
/
