prompt PATH TRANSLATE /vhr/hpd/transfer
begin
uis.lang_uz('#a:/vhr/hpd/transfer+add$add_accrual','Hisoblash yaratish');
uis.lang_uz('#a:/vhr/hpd/transfer+add$add_deduction','Ushlab qolish yaratish');
uis.lang_uz('#a:/vhr/hpd/transfer+add$add_fixed_term_base','Muddatli sharnoma asosini yaratish');
uis.lang_uz('#a:/vhr/hpd/transfer+add$add_fte','Ish vaqti turi qo''shish');
uis.lang_uz('#a:/vhr/hpd/transfer+add$add_rank','Daraja qo''shish');
uis.lang_uz('#a:/vhr/hpd/transfer+add$add_schedule','Ish jadvali qo''shish');
uis.lang_uz('#a:/vhr/hpd/transfer+add$add_wage_scale','Tarif setkasi qo''shish');
uis.lang_uz('#a:/vhr/hpd/transfer+add$select_accrual','Hisoblashni tanlash');
uis.lang_uz('#a:/vhr/hpd/transfer+add$select_deduction','Ushlab qolishni tanlash');
uis.lang_uz('#a:/vhr/hpd/transfer+add$select_fixed_term_base','Muddatli sharnoma asosini tanlash');
uis.lang_uz('#a:/vhr/hpd/transfer+add$select_fte','Ish vaqti turi tanlash');
uis.lang_uz('#a:/vhr/hpd/transfer+add$select_rank','Daraja tanlash');
uis.lang_uz('#a:/vhr/hpd/transfer+add$select_robot','Ish o''rni tanlash');
uis.lang_uz('#a:/vhr/hpd/transfer+add$select_schedule','Ish jadvali tanlash');
uis.lang_uz('#a:/vhr/hpd/transfer+add$select_staff','Xodim tanlash');
uis.lang_uz('#a:/vhr/hpd/transfer+add$select_wage_scale','Tarif setkasini tanlash');
uis.lang_uz('#a:/vhr/hpd/transfer+edit$add_accrual','Hisoblash yaratish');
uis.lang_uz('#a:/vhr/hpd/transfer+edit$add_deduction','Ushlab qolish yaratish');
uis.lang_uz('#a:/vhr/hpd/transfer+edit$add_fixed_term_base','Muddatli sharnoma asosini yaratish');
uis.lang_uz('#a:/vhr/hpd/transfer+edit$add_fte','Ish vaqti turi qo''shish');
uis.lang_uz('#a:/vhr/hpd/transfer+edit$add_rank','Daraja qo''shish');
uis.lang_uz('#a:/vhr/hpd/transfer+edit$add_schedule','Ish jadvali qo''shish');
uis.lang_uz('#a:/vhr/hpd/transfer+edit$add_wage_scale','Tarif setkasi qo''shish');
uis.lang_uz('#a:/vhr/hpd/transfer+edit$select_accrual','Hisoblashni tanlash');
uis.lang_uz('#a:/vhr/hpd/transfer+edit$select_deduction','Ushlab qolishni tanlash');
uis.lang_uz('#a:/vhr/hpd/transfer+edit$select_fixed_term_base','Muddatli sharnoma asosini tanlash');
uis.lang_uz('#a:/vhr/hpd/transfer+edit$select_fte','Ish vaqti turi tanlash');
uis.lang_uz('#a:/vhr/hpd/transfer+edit$select_rank','Daraja tanlash');
uis.lang_uz('#a:/vhr/hpd/transfer+edit$select_robot','Ish o''rni tanlash');
uis.lang_uz('#a:/vhr/hpd/transfer+edit$select_schedule','Ish jadvali tanlash');
uis.lang_uz('#a:/vhr/hpd/transfer+edit$select_staff','Xodim tanlash');
uis.lang_uz('#a:/vhr/hpd/transfer+edit$select_wage_scale','Tarif setkasini tanlash');
uis.lang_uz('#a:/vhr/hpd/transfer+multiple_add$add_accrual','Hisoblash yaratish');
uis.lang_uz('#a:/vhr/hpd/transfer+multiple_add$add_deduction','Ushlab qolish yaratish');
uis.lang_uz('#a:/vhr/hpd/transfer+multiple_add$add_fixed_term_base','Muddatli sharnoma asosini yaratish');
uis.lang_uz('#a:/vhr/hpd/transfer+multiple_add$add_fte','Ish vaqti turi qo''shish');
uis.lang_uz('#a:/vhr/hpd/transfer+multiple_add$add_rank','Daraja qo''shish');
uis.lang_uz('#a:/vhr/hpd/transfer+multiple_add$add_schedule','Ish jadvali qo''shish');
uis.lang_uz('#a:/vhr/hpd/transfer+multiple_add$add_wage_scale','Tarif setkasi qo''shish');
uis.lang_uz('#a:/vhr/hpd/transfer+multiple_add$select_accrual','Hisoblashni tanlash');
uis.lang_uz('#a:/vhr/hpd/transfer+multiple_add$select_deduction','Ushlab qolishni tanlash');
uis.lang_uz('#a:/vhr/hpd/transfer+multiple_add$select_fixed_term_base','Muddatli sharnoma asosini tanlash');
uis.lang_uz('#a:/vhr/hpd/transfer+multiple_add$select_fte','Ish vaqti turi tanlash');
uis.lang_uz('#a:/vhr/hpd/transfer+multiple_add$select_rank','Daraja tanlash');
uis.lang_uz('#a:/vhr/hpd/transfer+multiple_add$select_robot','Ish o''rni tanlash');
uis.lang_uz('#a:/vhr/hpd/transfer+multiple_add$select_schedule','Ish jadvali tanlash');
uis.lang_uz('#a:/vhr/hpd/transfer+multiple_add$select_staff','Xodim tanlash');
uis.lang_uz('#a:/vhr/hpd/transfer+multiple_add$select_wage_scale','Tarif setkasini tanlash');
uis.lang_uz('#a:/vhr/hpd/transfer+multiple_edit$add_fixed_term_base','Muddatli sharnoma asosini yaratish');
uis.lang_uz('#a:/vhr/hpd/transfer+multiple_edit$add_fte','Ish vaqti turi qo''shish');
uis.lang_uz('#a:/vhr/hpd/transfer+multiple_edit$add_oper_type','Amaliyot turini qo''shish');
uis.lang_uz('#a:/vhr/hpd/transfer+multiple_edit$add_rank','Daraja qo''shish');
uis.lang_uz('#a:/vhr/hpd/transfer+multiple_edit$add_schedule','Ish jadvali qo''shish');
uis.lang_uz('#a:/vhr/hpd/transfer+multiple_edit$add_wage_scale','Tarif setkasi qo''shish');
uis.lang_uz('#a:/vhr/hpd/transfer+multiple_edit$select_fixed_term_base','Muddatli sharnoma asosini tanlash');
uis.lang_uz('#a:/vhr/hpd/transfer+multiple_edit$select_fte','Ish vaqti turi tanlash');
uis.lang_uz('#a:/vhr/hpd/transfer+multiple_edit$select_oper_type','Amaliyot turini tanlash');
uis.lang_uz('#a:/vhr/hpd/transfer+multiple_edit$select_rank','Daraja tanlash');
uis.lang_uz('#a:/vhr/hpd/transfer+multiple_edit$select_robot','Ish o''rni tanlash');
uis.lang_uz('#a:/vhr/hpd/transfer+multiple_edit$select_schedule','Ish jadvali tanlash');
uis.lang_uz('#a:/vhr/hpd/transfer+multiple_edit$select_staff','Xodim tanlash');
uis.lang_uz('#a:/vhr/hpd/transfer+multiple_edit$select_wage_scale','Tarif setkasini tanlash');
uis.lang_uz('#f:/vhr/hpd/transfer+add','Ish o''rnini o''zgartirish (yaratish)');
uis.lang_uz('#f:/vhr/hpd/transfer+edit','Ish o''rnini o''zgartirish (tahrirlash)');
uis.lang_uz('#f:/vhr/hpd/transfer+multiple_add','Ro''yxat bilan ish o''rnini o''zgartirish (yaratish)');
uis.lang_uz('#f:/vhr/hpd/transfer+multiple_edit','Ro''yxat bilan ish o''rnini o''zgartirish (tahrirlash)');
commit;
end;
/
