prompt PATH TRANSLATE /vhr/rep/href/employee_by_gender
begin
uis.lang_uz('#a:/vhr/rep/href/employee_by_gender$select_edu_stage','Ta''lim turi tanlash');
uis.lang_uz('#a:/vhr/rep/href/employee_by_gender$select_rank','Daraja tanlash');
uis.lang_uz('#f:/vhr/rep/href/employee_by_gender','Shaxsiy kategoriyalar bo''yicha hisobot');
uis.lang_uz('ui-vhr291:... others','va boshqalar');
uis.lang_uz('ui-vhr291:age','Yosh');
uis.lang_uz('ui-vhr291:age range title','Shaxsiy kategoriyalar bo''yicha hisobot (yosh bo''yicha)');
uis.lang_uz('ui-vhr291:age ranges','Yosh');
uis.lang_uz('ui-vhr291:birthday','Tug''ilgan kun');
uis.lang_uz('ui-vhr291:count','Soni');
uis.lang_uz('ui-vhr291:count %','Soni (%)');
uis.lang_uz('ui-vhr291:count female','Ayollar');
uis.lang_uz('ui-vhr291:count male','Erkaklar');
uis.lang_uz('ui-vhr291:date $1','Sana: $1');
uis.lang_uz('ui-vhr291:division','Bo''lim');
uis.lang_uz('ui-vhr291:divisions: $1','Bo''lim: $1');
uis.lang_uz('ui-vhr291:edu stages','Ta''lim turlari');
uis.lang_uz('ui-vhr291:educ title','Shaxsiy kategoriyalar bo''yicha hisobot (ta''lim turlari bo''yicha)');
uis.lang_uz('ui-vhr291:eduction stage : $1','Ta''lim turlari: $1');
uis.lang_uz('ui-vhr291:experience range title','Shaxsiy kategoriyalar bo''yicha hisobot (tajriba bo''yicha)');
uis.lang_uz('ui-vhr291:female','Ayol');
uis.lang_uz('ui-vhr291:from $1 ages','$1 yoshdan');
uis.lang_uz('ui-vhr291:from $1 experiences','$1 yildan');
uis.lang_uz('ui-vhr291:from $1 to $2 ages','$1 yoshdan $2 yoshgacha');
uis.lang_uz('ui-vhr291:from $1 to $2 experiences','$1 yildan $2 yilgacha');
uis.lang_uz('ui-vhr291:gender','Jins');
uis.lang_uz('ui-vhr291:hiring_date','Ishga qabul qilingan sana');
uis.lang_uz('ui-vhr291:job','Lavozim');
uis.lang_uz('ui-vhr291:male','Erkak');
uis.lang_uz('ui-vhr291:month','Oy');
uis.lang_uz('ui-vhr291:name','Xodim');
uis.lang_uz('ui-vhr291:rank : $1','Daraja: $1');
uis.lang_uz('ui-vhr291:rank title','Shaxsiy kategoriyalar bo''yicha hisobot (daraja bo''yicha)');
uis.lang_uz('ui-vhr291:ranks','Darajalar');
uis.lang_uz('ui-vhr291:run_header: range not found, type=$1','Kamida bitta davr mavjud bo''lishi kerak!');
uis.lang_uz('ui-vhr291:some days ago','bir necha kun oldin');
uis.lang_uz('ui-vhr291:to $1 ages','$1 yoshgacha');
uis.lang_uz('ui-vhr291:to $1 experiences','$1 yilgacha');
uis.lang_uz('ui-vhr291:total','Jami');
uis.lang_uz('ui-vhr291:wage','Maosh');
uis.lang_uz('ui-vhr291:wage %','Maosh (%)');
uis.lang_uz('ui-vhr291:wage female','Maosh');
uis.lang_uz('ui-vhr291:wage male','Maosh');
uis.lang_uz('ui-vhr291:work ranges','Tajriba');
uis.lang_uz('ui-vhr291:work_month','Tajriba');
uis.lang_uz('ui-vhr291:year','yil');
commit;
end;
/
