select t.Table_Name, t.Constraint_Name
  from User_Constraints t
 where t.Constraint_Type = 'R' -- filter foreign keys
   and t.Generated <> 'GENERATED NAME'
   and not exists --
 (select 1
          from User_Indexes q
         where q.Table_Name = t.Table_Name
           and q.Generated = 'N' -- filter indexes not generated by system
           and -- not exist any column of the constraint not matching position in the index
               not exists (select 1
                  from User_Cons_Columns w
                  join User_Ind_Columns k
                    on w.Table_Name = k.Table_Name
                   and w.Column_Name = k.Column_Name
                 where w.Table_Name = q.Table_Name
                   and w.Constraint_Name = t.Constraint_Name
                   and k.Index_Name = q.Index_Name
                   and k.Column_Position <> w.Position)
           and -- number of columns in the constraint is equal to number of columns that match between the index and the constraint
               (select count(*)
                  from User_Cons_Columns w
                 where w.Table_Name = q.Table_Name
                   and w.Constraint_Name = t.Constraint_Name) --
               = (select count(*)
                    from User_Cons_Columns w
                    join User_Ind_Columns k
                      on w.Table_Name = k.Table_Name
                     and w.Column_Name = k.Column_Name
                   where w.Table_Name = q.Table_Name
                     and w.Constraint_Name = t.Constraint_Name
                     and k.Index_Name = q.Index_Name));
