prompt PATH TRANSLATE /vhr/href/start/employee_import
begin
uis.lang_ru('#a:/vhr/href/start/employee_import$save_setting','Сохранить настройки');
uis.lang_ru('#f:/vhr/href/start/employee_import','Сотрудники (импорт)');
uis.lang_ru('ui-vhr309:$1{error message} with address $2{address}','$1 связанная с адресом места проживания: $2');
uis.lang_ru('ui-vhr309:$1{error message} with birthday $2{birthday}','$1 связанная с днем рождения: $2');
uis.lang_ru('ui-vhr309:$1{error message} with division $2{division}','$1 связанная с подразделением: $2');
uis.lang_ru('ui-vhr309:$1{error message} with email $2{email}','$1 связанная с E-mail: $2');
uis.lang_ru('ui-vhr309:$1{error message} with fte $2{fte}','$1 связанная  со типом занятости: $2');
uis.lang_ru('ui-vhr309:$1{error message} with gender $2{gender}','$1 связанная с полом: $2');
uis.lang_ru('ui-vhr309:$1{error message} with hiring_date $2{hiring_date}','$1 связанная с датой приема на работу: $2');
uis.lang_ru('ui-vhr309:$1{error message} with iapa $2{iapa}','$1 связанная с ИНПС: $2');
uis.lang_ru('ui-vhr309:$1{error message} with job $2{job}','$1 связанная с должностью: $2');
uis.lang_ru('ui-vhr309:$1{error message} with legal address $2{legal_address}','$1 связанная с адресом по прописке: $2');
uis.lang_ru('ui-vhr309:$1{error message} with location $2{location}','$1 связанная с локацией: $2');
uis.lang_ru('ui-vhr309:$1{error message} with login $2{login}','$1 связанная с логином: $2');
uis.lang_ru('ui-vhr309:$1{error message} with main phone $2{main phone}','$1 связанная с телефоном: $2');
uis.lang_ru('ui-vhr309:$1{error message} with nationality $2{nationality}','$1 связанная с национальностью: $2');
uis.lang_ru('ui-vhr309:$1{error message} with natural person first name $2{natural person}','$1 связанная с именем: $2');
uis.lang_ru('ui-vhr309:$1{error message} with natural person last name $2{natural person}','$1 связанная с фамилией: $2');
uis.lang_ru('ui-vhr309:$1{error message} with natural person middle name $2{natural person}','$1 связанная с отчеством: $2');
uis.lang_ru('ui-vhr309:$1{error message} with npin $2{npin}','$1 связанная с ПИНФЛ: $2');
uis.lang_ru('ui-vhr309:$1{error message} with region $2{region}','$1 связанная с регионом: $2');
uis.lang_ru('ui-vhr309:$1{error message} with salary_amount $2{salary_amount}','$1 связанная с заплатой: $2');
uis.lang_ru('ui-vhr309:$1{error message} with salary_type $2{salary_type}','$1 связанная с типом зарплаты: $2');
uis.lang_ru('ui-vhr309:$1{error message} with schedule $2{schedule}','$1 связанная с графиком работы: $2');
uis.lang_ru('ui-vhr309:$1{error message} with staff_number $2{employee number}','$1 связанная с табельным номером: $2');
uis.lang_ru('ui-vhr309:address','Адрес');
uis.lang_ru('ui-vhr309:birthday','Дата рождения');
uis.lang_ru('ui-vhr309:chosen job is not belongs to chosen division, job_id=$1, division_id=$2','Выбранная должность не принадлежит выбранному подразделению, ИД должности=$1, ИД подразделения=$2');
uis.lang_ru('ui-vhr309:division','Подразделение');
uis.lang_ru('ui-vhr309:email','E-mail');
uis.lang_ru('ui-vhr309:employees','Сотрудники');
uis.lang_ru('ui-vhr309:first_name','Имя');
uis.lang_ru('ui-vhr309:fte_name','Тип занятости');
uis.lang_ru('ui-vhr309:gender','Пол');
uis.lang_ru('ui-vhr309:hiring_date','Дата приема на работу');
uis.lang_ru('ui-vhr309:iapa','ИНПС');
uis.lang_ru('ui-vhr309:identifier:code','Код');
uis.lang_ru('ui-vhr309:identifier:name','Название');
uis.lang_ru('ui-vhr309:job','Должность');
uis.lang_ru('ui-vhr309:last_name','Фамилия');
uis.lang_ru('ui-vhr309:legal_address','Адрес по прописке');
uis.lang_ru('ui-vhr309:location','Локация');
uis.lang_ru('ui-vhr309:login','Логин');
uis.lang_ru('ui-vhr309:login is used, $1=login','Логин уже занять, логин=$1');
uis.lang_ru('ui-vhr309:main_phone','Номер телефона');
uis.lang_ru('ui-vhr309:middle_name','Отчество');
uis.lang_ru('ui-vhr309:nationality_name','Национальность');
uis.lang_ru('ui-vhr309:npin','ПИНФЛ');
uis.lang_ru('ui-vhr309:region','Регион');
uis.lang_ru('ui-vhr309:salary_amount','Запрплата');
uis.lang_ru('ui-vhr309:salary_type','Тип зарплаты');
uis.lang_ru('ui-vhr309:schedule','График работы');
uis.lang_ru('ui-vhr309:staff_number','Табельный номер');
commit;
end;
/
