prompt MOBILE TRANSLATE
begin
uis.lang_uz('#mob:vhr:attendance_chart:back','Orqaga');
uis.lang_uz('#mob:vhr:attendance_chart:free_day','Dam olish kuni');
uis.lang_uz('#mob:vhr:attendance_chart:holiday','Bayram kuni');
uis.lang_uz('#mob:vhr:attendance_chart:intime','O''z vaqtida kelgan');
uis.lang_uz('#mob:vhr:attendance_chart:late','Kechikkan');
uis.lang_uz('#mob:vhr:attendance_chart:list_is_empty','Ro''yxat bo''sh');
uis.lang_uz('#mob:vhr:attendance_chart:no_license','Litsenziya yo''q');
uis.lang_uz('#mob:vhr:attendance_chart:no_schedule','Ish jadvali o''rnatilmagan');
uis.lang_uz('#mob:vhr:attendance_chart:non_working','Belgilangan dam olish kuni');
uis.lang_uz('#mob:vhr:attendance_chart:nonworking_day','Belgilangan dam olish kuni');
uis.lang_uz('#mob:vhr:attendance_chart:not_begin','Ish vaqti boshlanmagan');
uis.lang_uz('#mob:vhr:attendance_chart:not_come','Kelmagan');
uis.lang_uz('#mob:vhr:attendance_chart:not_licensed','Litsenziya yo''q');
uis.lang_uz('#mob:vhr:attendance_chart:show_all','Barchasini ko''rsatish');
uis.lang_uz('#mob:vhr:attendance_chart:take_leave','So''rov yuborilgan');
uis.lang_uz('#mob:vhr:attendance_chart:unknown','Aniqlanmagan');
uis.lang_uz('#mob:vhr:attendance_subordinate:back','Orqaga');
uis.lang_uz('#mob:vhr:birthday_list:back','Orqaga');
uis.lang_uz('#mob:vhr:birthday_list:birthday_show_all','Barchasi');
uis.lang_uz('#mob:vhr:birthday_list:birthdays','Tug''ilgan kunlar');
uis.lang_uz('#mob:vhr:birthday_list:list_is_empty','Ro''yxat bo''sh');
uis.lang_uz('#mob:vhr:birthday_list:toolbar_title','Tug''ilgan kunlar');
uis.lang_uz('#mob:vhr:camera:back','Orqaga');
uis.lang_uz('#mob:vhr:camera:camera_request_denied_description','Ilovaning ayrim imkoniyatlaridan foydalanish uchun, ilova sozlamalari orqali kameraga kirishga ruxsat bering');
uis.lang_uz('#mob:vhr:camera:camera_request_denied_title','Kameradan foydalanish talabi rad etildi');
uis.lang_uz('#mob:vhr:camera:face_recognition','Aniqlash');
uis.lang_uz('#mob:vhr:camera:go_to_setting','Sozlamalarga o''tish');
uis.lang_uz('#mob:vhr:camera:location_request_denied_description','Ilovaning ayrim imkoniyatlaridan foydalanish uchun ilova sozlamalarini oching va joylashuvni kuzatishga ruxsat bering');
uis.lang_uz('#mob:vhr:camera:location_request_denied_title','Joylashuvni kuzatish so''rovi rad etildi');
uis.lang_uz('#mob:vhr:camera:ok','OK');
uis.lang_uz('#mob:vhr:camera:please_wait','Iltimos, kuting');
uis.lang_uz('#mob:vhr:camera:repeat','Qayta urinib ko''ring');
uis.lang_uz('#mob:vhr:camera:send_note','Qaydni yuborish');
uis.lang_uz('#mob:vhr:camera:skip','O?tkazib yuborish');
uis.lang_uz('#mob:vhr:camera:warning','Ogohlantirish!');
uis.lang_uz('#mob:vhr:change:add','Qo''shish');
uis.lang_uz('#mob:vhr:change:cancel','Bekor qilish');
uis.lang_uz('#mob:vhr:change:comment','Izoh');
uis.lang_uz('#mob:vhr:change:comment_text','Izoh matni');
uis.lang_uz('#mob:vhr:change:send','Yuborish');
uis.lang_uz('#mob:vhr:change:toolbar_title','Ish jadvalini o''zgartirish');
uis.lang_uz('#mob:vhr:change_item:date','sana');
uis.lang_uz('#mob:vhr:change_item:free_schedule','Erkin ish jadvali');
uis.lang_uz('#mob:vhr:change_item:lunch','Tanaffus vaqti');
uis.lang_uz('#mob:vhr:change_item:lunch_end','Tanaffus tugashi');
uis.lang_uz('#mob:vhr:change_item:lunch_start','Tanaffus boshlanishi');
uis.lang_uz('#mob:vhr:change_item:not_specified','Ko''rsatilmagan');
uis.lang_uz('#mob:vhr:change_item:remove','O?chirish');
uis.lang_uz('#mob:vhr:change_item:schedule','Ish jadvali');
uis.lang_uz('#mob:vhr:change_item:specify','Belgilash');
uis.lang_uz('#mob:vhr:change_item:time_end','Tugash vaqti');
uis.lang_uz('#mob:vhr:change_item:time_start','Boshlanish vaqti');
uis.lang_uz('#mob:vhr:change_item:weekend','Dam olish kuni');
uis.lang_uz('#mob:vhr:change_item:working_hours_number','Ish vaqti');
uis.lang_uz('#mob:vhr:dashboard_mark:card_title','Qayd etish');
uis.lang_uz('#mob:vhr:dashboard_mark:check-in','Qayd');
uis.lang_uz('#mob:vhr:dashboard_mark:input','Kirish');
uis.lang_uz('#mob:vhr:dashboard_mark:output','Chiqish');
uis.lang_uz('#mob:vhr:face_registered_screen:camera','Ilovaning ayrim funksiyalaridan foydalanish uchun ilovangiz sozlamalarini oching va kameraga kirishga ruxsat bering');
uis.lang_uz('#mob:vhr:face_registered_screen:capture_face_from_camera','Kameradan foydalanish talabi rad etildi');
uis.lang_uz('#mob:vhr:face_registered_screen:choice_face_into_gallery','Galereyadan rasm tanlash');
uis.lang_uz('#mob:vhr:face_registered_screen:face_id_description','Yuzingiz aks etgan fotosuratni tanlang, unda yuzingiz faqat kameraga to�g�ridan-to�g�ri qaragan holda ko�rsatilishi kerak, to''liq oq fon bo''lishi tavsiya etiladi (pasport fotosuratidagi kabi)');
uis.lang_uz('#mob:vhr:face_registered_screen:face_id_title','Face ID uchun fotosurat qo''shing');
uis.lang_uz('#mob:vhr:face_registered_screen:face_registered','Yuz qayd etilgan');
uis.lang_uz('#mob:vhr:face_registered_screen:finish','Yakunlash');
uis.lang_uz('#mob:vhr:face_registered_screen:gallery','Galereya orqali');
uis.lang_uz('#mob:vhr:gps_tracking:back','Orqaga');
uis.lang_uz('#mob:vhr:gps_tracking:calendar','Taqvim');
uis.lang_uz('#mob:vhr:gps_tracking:toolbar_title','GPS kuzatuv');
uis.lang_uz('#mob:vhr:head:happy_birthday','Tug''ilgan kuningiz muborak bo''lsin!');
uis.lang_uz('#mob:vhr:head:my_day','Mening kunim');
uis.lang_uz('#mob:vhr:head:settings','Ko''proq');
uis.lang_uz('#mob:vhr:head:subordinate','Xodimlar');
uis.lang_uz('#mob:vhr:head:toolbar_title','Asosiy');
uis.lang_uz('#mob:vhr:init_setup:accept','Tasdiqlash');
uis.lang_uz('#mob:vhr:init_setup:alert_face_id_message','Keyinchalik qaydlarni amalga oshirish uchun Face ID qo''shishingiz kerak, agar bu bosqichni o''tkazib yuborsangiz qaydlarni amalga oshira olmaysiz');
uis.lang_uz('#mob:vhr:init_setup:alert_face_id_skip','O''tkazib yuborish');
uis.lang_uz('#mob:vhr:init_setup:alert_face_id_title','Diqqat!');
uis.lang_uz('#mob:vhr:init_setup:alert_gps_track_message','Ish vaqtida fonda joylashuvingizni kuzatish uchun, joylshuv sozlamalaridan "Doimiy ruxsat"ni yoqib berishingiz kerak, agar bu bosqichni o''tkazib yuborsangiz, administratoringiz joylashuvingizni kuzata olmaydi.');
uis.lang_uz('#mob:vhr:init_setup:alert_gps_track_skip','O''tkazib yuborish');
uis.lang_uz('#mob:vhr:init_setup:alert_gps_track_title','Diqqat!');
uis.lang_uz('#mob:vhr:init_setup:back','Orqaga');
uis.lang_uz('#mob:vhr:init_setup:finish','Yakunlash');
uis.lang_uz('#mob:vhr:init_setup:finish_description','Agar siz ba''zi qadamlarni o''tkazib yuborgan bo''lsangiz yoki keyinchalik o''zgartirishlar kiritmoqchi bo''lsangiz, ularni "Ko''proq" bo''limida alohida sozlashingiz mumkin');
uis.lang_uz('#mob:vhr:init_setup:finish_title','Dastalbki sozlash yakunlandi');
uis.lang_uz('#mob:vhr:init_setup:next','Keyingi');
uis.lang_uz('#mob:vhr:init_setup:skip','O''tkazib yuborish');
uis.lang_uz('#mob:vhr:init_setup:start','Sozlashni boshlash');
uis.lang_uz('#mob:vhr:kpi_category:calculation_type','Hisoblash turi');
uis.lang_uz('#mob:vhr:kpi_category:plan_type_e','Qo''shimcha ko''rsatkichlar');
uis.lang_uz('#mob:vhr:kpi_category:plan_type_m','Asosiy ko''rsatkichlar');
uis.lang_uz('#mob:vhr:kpi_category:status','Holat');
uis.lang_uz('#mob:vhr:kpi_category:weight','Vazni');
uis.lang_uz('#mob:vhr:kpi_part_add_edit:accept','Qabul qilish');
uis.lang_uz('#mob:vhr:kpi_part_add_edit:add','Baholarni qo''shish');
uis.lang_uz('#mob:vhr:kpi_part_add_edit:comment','Izoh');
uis.lang_uz('#mob:vhr:kpi_part_add_edit:error_empty_field','To''ldirilishi shart maydon');
uis.lang_uz('#mob:vhr:kpi_part_add_edit:fact','Bajarildi');
uis.lang_uz('#mob:vhr:kpi_plan_detailed:add','Qo''shish');
uis.lang_uz('#mob:vhr:kpi_plan_detailed:added','Qo''shdi');
uis.lang_uz('#mob:vhr:kpi_plan_detailed:are_you_sure_delete','Haqiqatan ham bahoni o?chirmoqchimisiz?');
uis.lang_uz('#mob:vhr:kpi_plan_detailed:at_time','da');
uis.lang_uz('#mob:vhr:kpi_plan_detailed:calculation_type','Hisoblash turi:');
uis.lang_uz('#mob:vhr:kpi_plan_detailed:close','Yopish');
uis.lang_uz('#mob:vhr:kpi_plan_detailed:delete','O?chirish');
uis.lang_uz('#mob:vhr:kpi_plan_detailed:edit','Tahrirlash');
uis.lang_uz('#mob:vhr:kpi_plan_detailed:no','Yo''q');
uis.lang_uz('#mob:vhr:kpi_plan_detailed:weight','Vazni:');
uis.lang_uz('#mob:vhr:kpi_plan_detailed:yes','Ha');
uis.lang_uz('#mob:vhr:kpi_plan_detailed:you','Siz');
uis.lang_uz('#mob:vhr:mark_barcode:close','Yopish');
uis.lang_uz('#mob:vhr:mark_barcode:qr_message','Qayd etish uchun QR-kodni planshetdagi Verifix Timepad ilovasiga ko''rsating.');
uis.lang_uz('#mob:vhr:mark_barcode:title','QR-kod orqali qayd etish');
uis.lang_uz('#mob:vhr:mark_face_bean:check_emotion_close_left_eye','Chap ko''zingizni yuming');
uis.lang_uz('#mob:vhr:mark_face_bean:check_emotion_close_right_eye','O''ng ko''zingizni yuming');
uis.lang_uz('#mob:vhr:mark_face_bean:check_emotion_smile','Tabassum qiling');
uis.lang_uz('#mob:vhr:mark_face_bean:face_not_recognized','Face ID aniqlanmadi');
uis.lang_uz('#mob:vhr:mark_face_bean:face_recognized','Face ID aniqlandi');
uis.lang_uz('#mob:vhr:mark_face_bean:unable_generate_emotion','Emotsiyani yaratish mumkin emas');
uis.lang_uz('#mob:vhr:mark_location:location_found','Koordinatalar topildi, aniqlik %1s m');
uis.lang_uz('#mob:vhr:mark_location:location_not_match','Joylashuv mos kelmadi');
uis.lang_uz('#mob:vhr:mark_location:please_wait','Iltimos, kuting');
uis.lang_uz('#mob:vhr:mark_location:skip','O?tkazib yuborish');
uis.lang_uz('#mob:vhr:mark_location:touch_id_description','Joriy foydalanuvchini aniqlash uchun Touch-ID-dan foydalaning. Barmog''ingizni sensorga qo''ying');
uis.lang_uz('#mob:vhr:mark_note:cancel','Bekor qilish');
uis.lang_uz('#mob:vhr:mark_note:face','Fotosurat');
uis.lang_uz('#mob:vhr:mark_note:face_found','Yuz aniqlandi');
uis.lang_uz('#mob:vhr:mark_note:field_required','Qayd yuborish uchun izoh talab etiladi');
uis.lang_uz('#mob:vhr:mark_note:location','Joylashuv');
uis.lang_uz('#mob:vhr:mark_note:location_accuracy','Aniqlik: %1s m');
uis.lang_uz('#mob:vhr:mark_note:location_not_found','Joylashuv mos kelmadi');
uis.lang_uz('#mob:vhr:mark_note:not_valid','Yuz aniqlanmadi');
uis.lang_uz('#mob:vhr:mark_note:note_hint_message','Qayd uchun izoh...');
uis.lang_uz('#mob:vhr:mark_note:send','Yuborish');
uis.lang_uz('#mob:vhr:mark_note:toolbar_title','Qayd haqida');
uis.lang_uz('#mob:vhr:mark_note:track_note','Izoh');
uis.lang_uz('#mob:vhr:my_day:hourly_schedule','Soatlik ish jadvali');
uis.lang_uz('#mob:vhr:my_day:merged_time','Kunni tasdiqlash oralig''i: %1s');
uis.lang_uz('#mob:vhr:my_day:no_schedule','Ish jadvali o''rnatilmagan');
uis.lang_uz('#mob:vhr:my_day:relax','Dam oling va kuningizdan zavqlaning');
uis.lang_uz('#mob:vhr:my_day:timesheet','Taqvim');
uis.lang_uz('#mob:vhr:my_day:toolbar_title','Asosiy');
uis.lang_uz('#mob:vhr:my_day:weekend','Dam olish kuni');
uis.lang_uz('#mob:vhr:my_day:work_day','Ish kuni %1s: %2s');
uis.lang_uz('#mob:vhr:my_day:working_day','Ish kuni');
uis.lang_uz('#mob:vhr:my_kpi:calculation_type','Hisoblash turi');
uis.lang_uz('#mob:vhr:my_kpi:calendar','Taqvim');
uis.lang_uz('#mob:vhr:my_kpi:toolbar_title','Mening samaradorligim');
uis.lang_uz('#mob:vhr:my_kpi:weight','Vazni');
uis.lang_uz('#mob:vhr:my_requests:back','Orqaga');
uis.lang_uz('#mob:vhr:my_requests:my_requests','Ish joyida bo''lmaganlik so''rovi');
uis.lang_uz('#mob:vhr:notification:back','Orqaga');
uis.lang_uz('#mob:vhr:notification:calendar','Taqvim');
uis.lang_uz('#mob:vhr:notification:coming_and_going','Davomat');
uis.lang_uz('#mob:vhr:notification:header_description','Push-bildirishnomalarni boshqarish');
uis.lang_uz('#mob:vhr:notification:header_title','Push-bildirishnomalar');
uis.lang_uz('#mob:vhr:notification:hes:nt:calendar_day_change','Ishchi taqvimdagi o''zgarishlar');
uis.lang_uz('#mob:vhr:notification:hes:nt:early_time','Xodimning erta ishdan ketishi');
uis.lang_uz('#mob:vhr:notification:hes:nt:late_time','Xodimning kech qolishi');
uis.lang_uz('#mob:vhr:notification:hes:nt:plan_change','Ish jadvalini o''zgartirish so''rovlari');
uis.lang_uz('#mob:vhr:notification:hes:nt:plan_change_manager_approval','Rahbar tasdig''i');
uis.lang_uz('#mob:vhr:notification:hes:nt:plan_change_status_change','Holat o''zgarishi');
uis.lang_uz('#mob:vhr:notification:hes:nt:request','Ish joyida yo''qlik so''rovlari');
uis.lang_uz('#mob:vhr:notification:hes:nt:request_change_status','Holat o''zgarishi');
uis.lang_uz('#mob:vhr:notification:hes:nt:request_manager_approval','Rahbar tasdig''i');
uis.lang_uz('#mob:vhr:notification:plan_change','Ish jadvalini o''zgartirish so''rovlari');
uis.lang_uz('#mob:vhr:notification:request','Ish joyida yo''qlik so''rovlari');
uis.lang_uz('#mob:vhr:notification:toolbar_title','Bildirishnomalar');
uis.lang_uz('#mob:vhr:notify_mark_setting:after','Keyin');
uis.lang_uz('#mob:vhr:notify_mark_setting:before','Avval');
uis.lang_uz('#mob:vhr:notify_mark_setting:begin_time_notification','Ish kunining boshlanish vaqti');
uis.lang_uz('#mob:vhr:notify_mark_setting:btn_close','Yopish');
uis.lang_uz('#mob:vhr:notify_mark_setting:btn_reset','Qayta o''rnatish');
uis.lang_uz('#mob:vhr:notify_mark_setting:enable_text','Ish kunining boshlanish vaqti, ish kunining tugashini kuzatish haqida bildirishnomalar');
uis.lang_uz('#mob:vhr:notify_mark_setting:end_time_notification','Ish kunining tugash vaqti');
uis.lang_uz('#mob:vhr:notify_mark_setting:header_description','Ish kunining boshi va oxirida qaydlarning zarurligi haqida bildirishnomalar');
uis.lang_uz('#mob:vhr:notify_mark_setting:header_title','Qaydlar zaruriyati to''g''risida bildirishnomalar');
uis.lang_uz('#mob:vhr:notify_mark_setting:minute','%1s min');
uis.lang_uz('#mob:vhr:notify_mark_setting:reset','Qayta o''rnatish');
uis.lang_uz('#mob:vhr:notify_mark_setting:reset_warning_message','Joriy sozlamalarni qayta o''rnatmoqchimisiz');
uis.lang_uz('#mob:vhr:notify_mark_setting:reset_warning_title','Diqqat!');
uis.lang_uz('#mob:vhr:notify_mark_setting:save','Saqlash');
uis.lang_uz('#mob:vhr:notify_mark_setting:toolbar_title','Qaydlar bo''yicha bildirishnomalar');
uis.lang_uz('#mob:vhr:permission:enable','Yoqish');
uis.lang_uz('#mob:vhr:permission:go_to_setting','Sozlamalarga o''tish');
uis.lang_uz('#mob:vhr:permission:gps_track_functional_limited_message','Joylashuvga ruxsat berilmagani uchun ilova fonda joylashuvingizni aniqlay olmaydi va administrator ish vaqtida kuzatuvni amalga oshira olmaydi. Sozlamalar -> Ilovalar -> Ruxsatlar va ushbu ilovaga joylashuvga ruxsat bering.');
uis.lang_uz('#mob:vhr:permission:gps_track_functional_limited_title','Imkoniyatlar cheklangan');
uis.lang_uz('#mob:vhr:permission:location','Joylashuv ma''lumotlariga fonda kirish sizni ish soatlarida kuzatish imkonini beradi va administratoringiz kuzatuvni amalga oshirish imkoniyatiga ega bo''ladi. (Agar administratoringiz kuzatishni yoqqan bo''lsa, aks holda bu imkoniyat har doim o''chirilgan holatda bo''ladi)');
uis.lang_uz('#mob:vhr:permission:location_description','Verifix HR xodimlarda ilova yopilgan yoki ishlatilmayotgan paytda ham joylashuv ma''lumotlarini to''playdi');
uis.lang_uz('#mob:vhr:permission:location_title','Joylashuv ma''lumotlari');
uis.lang_uz('#mob:vhr:permission:no_thanks','Yo''q, rahmat!');
uis.lang_uz('#mob:vhr:permission:skip','O''tkazib yuborish');
uis.lang_uz('#mob:vhr:profile:account_password','Parolni o''zgartirish');
uis.lang_uz('#mob:vhr:profile:account_title','Profil');
uis.lang_uz('#mob:vhr:profile:change_account','Profilni o''zgartirish');
uis.lang_uz('#mob:vhr:profile:change_filial','Tashkilotni o''zgartirish');
uis.lang_uz('#mob:vhr:profile:change_password','PIN-kodni o''zgartirish');
uis.lang_uz('#mob:vhr:profile:current_filial','Hozirgi tashkilot');
uis.lang_uz('#mob:vhr:profile:enter_with_touch_id','Touch-ID bilan tizimga kirish');
uis.lang_uz('#mob:vhr:profile:gps_tracks','GPS kuzatuvlarim');
uis.lang_uz('#mob:vhr:profile:language','Til');
uis.lang_uz('#mob:vhr:profile:my_kpi','Mening samaradorligim');
uis.lang_uz('#mob:vhr:profile:notify_mark','Ish kunining boshlanishi va tugash vaqti haqida bildirishnomalar');
uis.lang_uz('#mob:vhr:profile:profile','Profil');
uis.lang_uz('#mob:vhr:profile:profile_change','O''zgartirish');
uis.lang_uz('#mob:vhr:profile:remove_password','PIN-kodni o''chirish');
uis.lang_uz('#mob:vhr:profile:security_title','Xavfsizlik');
uis.lang_uz('#mob:vhr:profile:serial_number','Seriya raqami');
uis.lang_uz('#mob:vhr:profile:set_password','PIN-kodni o''rnatish');
uis.lang_uz('#mob:vhr:profile:settings','Sozlamalar');
uis.lang_uz('#mob:vhr:profile:show_direct_subordinates','Faqat bevosita qo''l ostidagi xodimlarni ko''rsatish');
uis.lang_uz('#mob:vhr:profile:subordinates_kpi','Xodimlar samaradorligi');
uis.lang_uz('#mob:vhr:profile:system_title','Ilova haqida');
uis.lang_uz('#mob:vhr:profile:toolbar_title','Ko''proq');
uis.lang_uz('#mob:vhr:profile:version_number','Talqin');
uis.lang_uz('#mob:vhr:profile_screen:accounts','Profillar');
uis.lang_uz('#mob:vhr:profile_screen:accounts_and_ids','Hisob raqamlari');
uis.lang_uz('#mob:vhr:profile_screen:back','Orqaga');
uis.lang_uz('#mob:vhr:profile_screen:camera','Kamera');
uis.lang_uz('#mob:vhr:profile_screen:city','Shahar');
uis.lang_uz('#mob:vhr:profile_screen:contacts','Kontaktlar');
uis.lang_uz('#mob:vhr:profile_screen:copied','Buferga nusxalandi');
uis.lang_uz('#mob:vhr:profile_screen:date_of_birth','Tug''ilgan kun');
uis.lang_uz('#mob:vhr:profile_screen:email','E-mail');
uis.lang_uz('#mob:vhr:profile_screen:exit_account_message','Haqiqatan ham profildan chiqmoqchimisiz?');
uis.lang_uz('#mob:vhr:profile_screen:exit_account_no','Yo''q');
uis.lang_uz('#mob:vhr:profile_screen:exit_account_yes','Ha');
uis.lang_uz('#mob:vhr:profile_screen:face','Face ID');
uis.lang_uz('#mob:vhr:profile_screen:face_not_registered','Ro?yxatdan o?tmagan');
uis.lang_uz('#mob:vhr:profile_screen:face_registered','Ro''yxatga olingan');
uis.lang_uz('#mob:vhr:profile_screen:female','Ayol');
uis.lang_uz('#mob:vhr:profile_screen:gallery','Galereya');
uis.lang_uz('#mob:vhr:profile_screen:gender','Jins');
uis.lang_uz('#mob:vhr:profile_screen:image_source_question','Fotosurat qayerdan olinsin?');
uis.lang_uz('#mob:vhr:profile_screen:inn','STIR');
uis.lang_uz('#mob:vhr:profile_screen:inps','ShJBPH');
uis.lang_uz('#mob:vhr:profile_screen:leave','Chiqish');
uis.lang_uz('#mob:vhr:profile_screen:male','Erkak');
uis.lang_uz('#mob:vhr:profile_screen:manager','Rahbar');
uis.lang_uz('#mob:vhr:profile_screen:no_image_selected','Fotosurat tanlanmagan');
uis.lang_uz('#mob:vhr:profile_screen:no_info','Ko''rsatilmagan');
uis.lang_uz('#mob:vhr:profile_screen:personnel_number','Xodim raqami');
uis.lang_uz('#mob:vhr:profile_screen:phone_number','Telefon');
uis.lang_uz('#mob:vhr:profile_screen:pinfl','JShShIR');
uis.lang_uz('#mob:vhr:profile_screen:profile','Profil');
uis.lang_uz('#mob:vhr:profile_screen:region','Mintaqa');
uis.lang_uz('#mob:vhr:profile_screen:registration_address','Doimiy ro''yxatdan o''tgan manzili');
uis.lang_uz('#mob:vhr:profile_screen:residence_address','Yashash manzili');
uis.lang_uz('#mob:vhr:profile_screen:warning','Ogohlantirish');
uis.lang_uz('#mob:vhr:request_component:change_schedule','Jadval o''zg.');
uis.lang_uz('#mob:vhr:request_component:for_today','Bugungi');
uis.lang_uz('#mob:vhr:request_component:leave','Ish joy. yo''q.');
uis.lang_uz('#mob:vhr:request_component:requests','So''rovlar');
uis.lang_uz('#mob:vhr:request_component:show_all','Barchasi');
uis.lang_uz('#mob:vhr:request_component:swap','Kun almash.');
uis.lang_uz('#mob:vhr:request_component:this_month','Shu oy');
uis.lang_uz('#mob:vhr:request_details:accrual_kind','Hisoblash turi');
uis.lang_uz('#mob:vhr:request_details:approve','Qabul qilish');
uis.lang_uz('#mob:vhr:request_details:approved','Tasdiqlangan');
uis.lang_uz('#mob:vhr:request_details:back','Orqaga');
uis.lang_uz('#mob:vhr:request_details:change','Jadvalni o''zgartirish');
uis.lang_uz('#mob:vhr:request_details:comment','Izoh');
uis.lang_uz('#mob:vhr:request_details:comment_text','Izoh matni');
uis.lang_uz('#mob:vhr:request_details:complete','Tasdiqlash');
uis.lang_uz('#mob:vhr:request_details:date','Sana');
uis.lang_uz('#mob:vhr:request_details:dates','Sanalar');
uis.lang_uz('#mob:vhr:request_details:delete','O?chirish');
uis.lang_uz('#mob:vhr:request_details:denied','Rad etilgan');
uis.lang_uz('#mob:vhr:request_details:deny','Rad etish');
uis.lang_uz('#mob:vhr:request_details:edit','Tahrirlash');
uis.lang_uz('#mob:vhr:request_details:free_schedule','Erkin ish jadvali');
uis.lang_uz('#mob:vhr:request_details:leave','Ish joyida yo''qlik so''rovi');
uis.lang_uz('#mob:vhr:request_details:leave_reason','Sabab');
uis.lang_uz('#mob:vhr:request_details:leave_type','Ish joyida yo''qlik turi');
uis.lang_uz('#mob:vhr:request_details:lunch','Tanaffus vaqti');
uis.lang_uz('#mob:vhr:request_details:lunch_end','Tanaffus tugashi');
uis.lang_uz('#mob:vhr:request_details:lunch_start','Tanaffus boshlanishi');
uis.lang_uz('#mob:vhr:request_details:manager_approval','Rahbar tasdig''i');
uis.lang_uz('#mob:vhr:request_details:manager_note','Rahbar izohi');
uis.lang_uz('#mob:vhr:request_details:not_specified','Aniqlanmagan');
uis.lang_uz('#mob:vhr:request_details:note','Izoh');
uis.lang_uz('#mob:vhr:request_details:replaced_day','Almashish kuni');
uis.lang_uz('#mob:vhr:request_details:replacing_day','Ish kunlarini almashtirish');
uis.lang_uz('#mob:vhr:request_details:request_state','So''rov holati');
uis.lang_uz('#mob:vhr:request_details:reset','Qaytarish');
uis.lang_uz('#mob:vhr:request_details:schedule','Ish jadvali');
uis.lang_uz('#mob:vhr:request_details:schedule_change','Ish jadvalni o''zgartirish');
uis.lang_uz('#mob:vhr:request_details:send','Yuborish');
uis.lang_uz('#mob:vhr:request_details:subordinate_name','Xodim');
uis.lang_uz('#mob:vhr:request_details:swap','kun almashinuvi');
uis.lang_uz('#mob:vhr:request_details:time','vaqt');
uis.lang_uz('#mob:vhr:request_details:time_end','Tugash vaqti');
uis.lang_uz('#mob:vhr:request_details:time_start','Boshlanish vaqti');
uis.lang_uz('#mob:vhr:request_details:toolbar_title','So''rov tafsilotlari');
uis.lang_uz('#mob:vhr:request_details:waiting','Kutilmoqda');
uis.lang_uz('#mob:vhr:request_details:weekend','Dam olish kuni');
uis.lang_uz('#mob:vhr:request_details:work_day','Ish kuni');
uis.lang_uz('#mob:vhr:request_details:work_hours_number','Ish soatlari hajmi');
uis.lang_uz('#mob:vhr:request_details:working_hours_number','Ish soatlari hajmi');
uis.lang_uz('#mob:vhr:request_list:april','Aprel');
uis.lang_uz('#mob:vhr:request_list:august','Avgust');
uis.lang_uz('#mob:vhr:request_list:back','Orqaga');
uis.lang_uz('#mob:vhr:request_list:december','Dekabr');
uis.lang_uz('#mob:vhr:request_list:february','Fevral');
uis.lang_uz('#mob:vhr:request_list:january','Yanvar');
uis.lang_uz('#mob:vhr:request_list:july','Iyul');
uis.lang_uz('#mob:vhr:request_list:june','Iyun');
uis.lang_uz('#mob:vhr:request_list:march','Mart');
uis.lang_uz('#mob:vhr:request_list:may','May');
uis.lang_uz('#mob:vhr:request_list:no_requests','So?rovlar yo?q');
uis.lang_uz('#mob:vhr:request_list:november','Noyabr');
uis.lang_uz('#mob:vhr:request_list:october','Oktabr');
uis.lang_uz('#mob:vhr:request_list:september','Sentabr');
uis.lang_uz('#mob:vhr:request_list:toolbar_title','So''rovlar ro''yxati');
uis.lang_uz('#mob:vhr:requests:accrual','Hisoblandi');
uis.lang_uz('#mob:vhr:requests:approved','Tasdiqlangan');
uis.lang_uz('#mob:vhr:requests:back','Orqaga');
uis.lang_uz('#mob:vhr:requests:cancel','Bekor qilish');
uis.lang_uz('#mob:vhr:requests:change','Ish jadvalni o''zgartirish');
uis.lang_uz('#mob:vhr:requests:comment','Izoh');
uis.lang_uz('#mob:vhr:requests:comment_text','Izoh matni');
uis.lang_uz('#mob:vhr:requests:date','sana');
uis.lang_uz('#mob:vhr:requests:dates','sanalar');
uis.lang_uz('#mob:vhr:requests:day_end','tugash kuni');
uis.lang_uz('#mob:vhr:requests:day_start','boshlanish kuni');
uis.lang_uz('#mob:vhr:requests:delete','O?chirish');
uis.lang_uz('#mob:vhr:requests:denied','Qaytarilgan');
uis.lang_uz('#mob:vhr:requests:edit','Tahrirlash');
uis.lang_uz('#mob:vhr:requests:free_schedule','Erkin ish jadvali');
uis.lang_uz('#mob:vhr:requests:leave','Ish joyida yo''qlik so''rovi');
uis.lang_uz('#mob:vhr:requests:leave_reason','Sabab');
uis.lang_uz('#mob:vhr:requests:leave_type','Ish joyida yo''qlik turi');
uis.lang_uz('#mob:vhr:requests:leave_type_day','Kunlik');
uis.lang_uz('#mob:vhr:requests:leave_type_days','Bir necha kunlik');
uis.lang_uz('#mob:vhr:requests:leave_type_hourly','Soatlik');
uis.lang_uz('#mob:vhr:requests:left','Qoldi');
uis.lang_uz('#mob:vhr:requests:lunch','Tanaffus vaqti');
uis.lang_uz('#mob:vhr:requests:lunch_end','Tanaffus tugashi');
uis.lang_uz('#mob:vhr:requests:lunch_start','Tanaffus boshlanishi');
uis.lang_uz('#mob:vhr:requests:manager_approval','Rahbar tasdig''i');
uis.lang_uz('#mob:vhr:requests:no_choice','Tanlanmagan');
uis.lang_uz('#mob:vhr:requests:not_specified','Ko''rsatilmagan');
uis.lang_uz('#mob:vhr:requests:replaced_day','O''zgaruvchi kun');
uis.lang_uz('#mob:vhr:requests:replacing_day','Almashuvchi kun');
uis.lang_uz('#mob:vhr:requests:request_state','so''rov holati');
uis.lang_uz('#mob:vhr:requests:schedule_change','Ish jadvalini o''zgartirish');
uis.lang_uz('#mob:vhr:requests:send','Yuborish');
uis.lang_uz('#mob:vhr:requests:specify','Belgilash');
uis.lang_uz('#mob:vhr:requests:swap','Kun almashinuvi');
uis.lang_uz('#mob:vhr:requests:time','vaqt');
uis.lang_uz('#mob:vhr:requests:time_end','Tugash vaqti');
uis.lang_uz('#mob:vhr:requests:time_start','Boshlanish vaqti');
uis.lang_uz('#mob:vhr:requests:used','Ishlatildi');
uis.lang_uz('#mob:vhr:requests:waiting','Kutilmoqda');
uis.lang_uz('#mob:vhr:requests:working_hours_number','Ish soatlari hajmi');
uis.lang_uz('#mob:vhr:select_task_status:close','Yopish');
uis.lang_uz('#mob:vhr:select_task_status:title','Holatni tanlash');
uis.lang_uz('#mob:vhr:setting:account_btn','Profillar');
uis.lang_uz('#mob:vhr:setting:back','Orqaga');
uis.lang_uz('#mob:vhr:setting:background','Ilova foni');
uis.lang_uz('#mob:vhr:setting:components','Komponentlar');
uis.lang_uz('#mob:vhr:setting:dark','Qorong''i');
uis.lang_uz('#mob:vhr:setting:default_system','Tizimdagi kabi');
uis.lang_uz('#mob:vhr:setting:for_developer','Ishlab chiquvchilar uchun');
uis.lang_uz('#mob:vhr:setting:interface','Interfeys');
uis.lang_uz('#mob:vhr:setting:lang','til');
uis.lang_uz('#mob:vhr:setting:light','Yorqin');
uis.lang_uz('#mob:vhr:setting:load_vector','Yuz aniqlash tizimi vektorlari yuklanmoqda %1s/%2s');
uis.lang_uz('#mob:vhr:setting:load_vector_error','Yuz aniqlash tizimi vektorlari yuklanmoqda %1s/%2s, %3s');
uis.lang_uz('#mob:vhr:setting:main_page','Dastlabki ekran');
uis.lang_uz('#mob:vhr:setting:notification','Bildirishnomalar');
uis.lang_uz('#mob:vhr:setting:others','Boshqalar');
uis.lang_uz('#mob:vhr:setting:please_wait','Iltimos, kuting');
uis.lang_uz('#mob:vhr:setting:reload_btn','Qayta urinib ko''rish');
uis.lang_uz('#mob:vhr:setting:setting_downloads','Sozlamalar yuklanmoqda');
uis.lang_uz('#mob:vhr:setting:start_offline','Oflayn rejimda boshlash');
uis.lang_uz('#mob:vhr:setting:theme','mavzu');
uis.lang_uz('#mob:vhr:setting:toolbar_title','Sozlamalar');
uis.lang_uz('#mob:vhr:setting_options:back','Orqaga');
uis.lang_uz('#mob:vhr:setting_options:dark','Qorong''i');
uis.lang_uz('#mob:vhr:setting_options:default_system','Tizimdagi kabi');
uis.lang_uz('#mob:vhr:setting_options:light','Yorug''');
uis.lang_uz('#mob:vhr:setting_options:theme','Mavzu');
uis.lang_uz('#mob:vhr:setting_options:toolbar_title','Imkoniyatlar');
uis.lang_uz('#mob:vhr:subordinate:birthday_show_all','Barchasi');
uis.lang_uz('#mob:vhr:subordinate:birthdays','Tug''ilgan kunlar');
uis.lang_uz('#mob:vhr:subordinate:show_all','Barchasi');
uis.lang_uz('#mob:vhr:subordinate:sub_show_all','Barchasi');
uis.lang_uz('#mob:vhr:subordinate:subordinate_requests','So''rovlar');
uis.lang_uz('#mob:vhr:subordinate:subordinates','Xodimlar');
uis.lang_uz('#mob:vhr:subordinate:toolbar_title','Xodimlar');
uis.lang_uz('#mob:vhr:subordinate_card:calendar','Taqvim');
uis.lang_uz('#mob:vhr:subordinate_card:profile','Profil');
uis.lang_uz('#mob:vhr:subordinate_dialog:btn_close','Yopish');
uis.lang_uz('#mob:vhr:subordinate_dialog:list_is_empty','Xodimlar ro?yxati bo?sh');
uis.lang_uz('#mob:vhr:subordinate_dialog:search_hint','Qidiruv');
uis.lang_uz('#mob:vhr:subordinate_dialog:toolbar_title','Xodimlar');
uis.lang_uz('#mob:vhr:subordinate_kpi:calendar','Taqvim');
uis.lang_uz('#mob:vhr:subordinate_kpi:search','Qidiruv');
uis.lang_uz('#mob:vhr:subordinate_kpi:toolbar_title','Xodimlar samaradorligi');
uis.lang_uz('#mob:vhr:subordinate_kpi_detailed:calculation_type','Hisoblash turi');
uis.lang_uz('#mob:vhr:subordinate_kpi_detailed:calendar','Taqvim');
uis.lang_uz('#mob:vhr:subordinate_kpi_detailed:toolbar_title','Samaradorlik');
uis.lang_uz('#mob:vhr:subordinate_kpi_detailed:weight','Vazni');
uis.lang_uz('#mob:vhr:subordinate_list:back','Orqaga');
uis.lang_uz('#mob:vhr:subordinate_list:btn_close','Yopish');
uis.lang_uz('#mob:vhr:subordinate_list:list_is_empty','Ro''yxat bo''sh');
uis.lang_uz('#mob:vhr:subordinate_list:search','Qidiruv');
uis.lang_uz('#mob:vhr:subordinate_list:search_hint','Qidiruv');
uis.lang_uz('#mob:vhr:subordinate_list:toolbar_title','Xodimlar');
uis.lang_uz('#mob:vhr:swap:add','Qo''shish');
uis.lang_uz('#mob:vhr:swap:cancel','Bekor qilish');
uis.lang_uz('#mob:vhr:swap:comment','Izoh');
uis.lang_uz('#mob:vhr:swap:comment_text','Izoh matn');
uis.lang_uz('#mob:vhr:swap:send','Yuborish');
uis.lang_uz('#mob:vhr:swap:toolbar_title','Kun almashinuvi');
uis.lang_uz('#mob:vhr:swap_item:not_specified','Ko''rsatilmagan');
uis.lang_uz('#mob:vhr:swap_item:remove','O?chirish');
uis.lang_uz('#mob:vhr:swap_item:replaced_day','O''zgartiruvchi kun');
uis.lang_uz('#mob:vhr:swap_item:replacing_day','Almashuvchi kun');
uis.lang_uz('#mob:vhr:swap_item:specify','Belgilash');
uis.lang_uz('#mob:vhr:task_edit:back','Orqaga');
uis.lang_uz('#mob:vhr:task_edit:check_list','Ro''yxat');
uis.lang_uz('#mob:vhr:task_edit:create','Yaratish');
uis.lang_uz('#mob:vhr:task_edit:dialog_message_warning','Sizda hech qanday vazifa statuslari yo''q. Iltimos, bu haqda operatorga xabar bering');
uis.lang_uz('#mob:vhr:task_edit:dialog_title_warning','Ogohlantirish');
uis.lang_uz('#mob:vhr:task_edit:end_time','Tugash vaqti');
uis.lang_uz('#mob:vhr:task_edit:ok','OK');
uis.lang_uz('#mob:vhr:task_edit:pick_date','Muddat');
uis.lang_uz('#mob:vhr:task_edit:save','Saqlash');
uis.lang_uz('#mob:vhr:task_edit:start_time','Boshlanish vaqti');
uis.lang_uz('#mob:vhr:task_edit:task_add_checklist','Ro''yxat qo''shish');
uis.lang_uz('#mob:vhr:task_edit:task_add_description','Izoh qoldirish');
uis.lang_uz('#mob:vhr:task_edit:task_title','Vazifa nomi');
uis.lang_uz('#mob:vhr:task_edit:title_bt_apply','Qo''llash');
uis.lang_uz('#mob:vhr:task_edit:title_director','Obyekt');
uis.lang_uz('#mob:vhr:task_edit:title_executor','Ijrochi');
uis.lang_uz('#mob:vhr:task_edit:title_grade','Baho');
uis.lang_uz('#mob:vhr:task_edit:title_observer','Kuzatuvchi');
uis.lang_uz('#mob:vhr:task_edit:title_participant','Ishtirokchi');
uis.lang_uz('#mob:vhr:task_edit:title_responsible','Mas''ul');
uis.lang_uz('#mob:vhr:task_edit:title_select_status','Holatni tanlang');
uis.lang_uz('#mob:vhr:task_edit:title_spent_time','Sarflangan vaqt');
uis.lang_uz('#mob:vhr:task_edit:title_status','Holat');
uis.lang_uz('#mob:vhr:task_edit:toolbar_create_title','Vazifa yaratish');
uis.lang_uz('#mob:vhr:task_edit:toolbar_edit_title','Tahrirlash');
uis.lang_uz('#mob:vhr:task_info:add_comment','Izoh qo''shish ....');
uis.lang_uz('#mob:vhr:task_info:back','Orqaga');
uis.lang_uz('#mob:vhr:task_info:btn_save','Saqlash');
uis.lang_uz('#mob:vhr:task_info:check_list','Ro''yxat');
uis.lang_uz('#mob:vhr:task_info:comment','Izohlar');
uis.lang_uz('#mob:vhr:task_info:delete_comment','O''chirish');
uis.lang_uz('#mob:vhr:task_info:delete_comment_message','Siz haqiqatan ham izohni ochirib tashlamoqchimisiz?');
uis.lang_uz('#mob:vhr:task_info:directory','Obyekt');
uis.lang_uz('#mob:vhr:task_info:done_in','%2s dan %1s bajarildi');
uis.lang_uz('#mob:vhr:task_info:edit','Tahrirlash');
uis.lang_uz('#mob:vhr:task_info:edit_comment','Tahrirlash');
uis.lang_uz('#mob:vhr:task_info:end_time','Tugash vaqti');
uis.lang_uz('#mob:vhr:task_info:executor','Ijrochi');
uis.lang_uz('#mob:vhr:task_info:grade','Baho');
uis.lang_uz('#mob:vhr:task_info:no','Yo''q');
uis.lang_uz('#mob:vhr:task_info:observer','Kuzatuvchi');
uis.lang_uz('#mob:vhr:task_info:participant','Ishtirokchi');
uis.lang_uz('#mob:vhr:task_info:quite_message','Chiqishni xohlaysizmi?');
uis.lang_uz('#mob:vhr:task_info:responsible','Mas''ul');
uis.lang_uz('#mob:vhr:task_info:spent_time','Sarflangan vaqt');
uis.lang_uz('#mob:vhr:task_info:start_time','Boshlash vaqti');
uis.lang_uz('#mob:vhr:task_info:task_persons','Ishtirokchilar');
uis.lang_uz('#mob:vhr:task_info:task_title_2','Vazifa nomi');
uis.lang_uz('#mob:vhr:task_info:toolbar_title','Vazifa %1s - %2s');
uis.lang_uz('#mob:vhr:task_info:un_auth_error','Foydalanuvchi autentifikatsiya qilmagan');
uis.lang_uz('#mob:vhr:task_info:warning','Ogohlantirish');
uis.lang_uz('#mob:vhr:task_info:yes','Ha');
uis.lang_uz('#mob:vhr:task_list:add_task','+ Vazifa qo''shish');
uis.lang_uz('#mob:vhr:task_list:back','Orqaga');
uis.lang_uz('#mob:vhr:task_list:day','kun');
uis.lang_uz('#mob:vhr:task_list:expired','Muddati tugagan');
uis.lang_uz('#mob:vhr:task_list:hour','soat');
uis.lang_uz('#mob:vhr:task_list:list_is_empty','Ro''yxat bo''sh');
uis.lang_uz('#mob:vhr:task_list:no_data_found','Ma''lumot topilmadi');
uis.lang_uz('#mob:vhr:task_list:search','Qidiruv');
uis.lang_uz('#mob:vhr:task_list:task_expired_days','%1s kun');
uis.lang_uz('#mob:vhr:task_list:today','Bugun');
uis.lang_uz('#mob:vhr:task_list:toolbar_title','Vazifalar');
uis.lang_uz('#mob:vhr:task_list_filter:apply','Qo''llash');
uis.lang_uz('#mob:vhr:task_list_filter:close','Bekor qilish');
uis.lang_uz('#mob:vhr:task_list_filter:filter','Filtr');
uis.lang_uz('#mob:vhr:task_list_filter:select_status','Holatlar');
uis.lang_uz('#mob:vhr:task_list_filter:toolbar_title','Filtr');
uis.lang_uz('#mob:vhr:task_person_list:apply','Qo''llash');
uis.lang_uz('#mob:vhr:task_person_list:back','Orqaga');
uis.lang_uz('#mob:vhr:task_person_list:list_is_empty','Ro''yxat bo''sh');
uis.lang_uz('#mob:vhr:task_person_list:no','Yo''q');
uis.lang_uz('#mob:vhr:task_person_list:quite_message','Chiqishni xohlaysizmi?');
uis.lang_uz('#mob:vhr:task_person_list:search','Qidiruv');
uis.lang_uz('#mob:vhr:task_person_list:toolbar_title','Foydalanuvchilar');
uis.lang_uz('#mob:vhr:task_person_list:warning','Ogohlantirish');
uis.lang_uz('#mob:vhr:task_person_list:yes','Ha');
uis.lang_uz('#mob:vhr:timesheet:april','Aprel');
uis.lang_uz('#mob:vhr:timesheet:at_work','Ish joyida');
uis.lang_uz('#mob:vhr:timesheet:august','Avgust');
uis.lang_uz('#mob:vhr:timesheet:back_pressed','Orqaga');
uis.lang_uz('#mob:vhr:timesheet:december','Dekabr');
uis.lang_uz('#mob:vhr:timesheet:employee_change','Ish kunini o''zgartirish');
uis.lang_uz('#mob:vhr:timesheet:february','Fevral');
uis.lang_uz('#mob:vhr:timesheet:has_leave_full_day','Kun davomida ish joyida yoq''lik');
uis.lang_uz('#mob:vhr:timesheet:january','Yanvar');
uis.lang_uz('#mob:vhr:timesheet:july','Iyul');
uis.lang_uz('#mob:vhr:timesheet:june','Iyun');
uis.lang_uz('#mob:vhr:timesheet:march','Mart');
uis.lang_uz('#mob:vhr:timesheet:may','may');
uis.lang_uz('#mob:vhr:timesheet:november','Noyabr');
uis.lang_uz('#mob:vhr:timesheet:october','Oktabr');
uis.lang_uz('#mob:vhr:timesheet:schedule','Ish jadvali');
uis.lang_uz('#mob:vhr:timesheet:september','Sentabr');
uis.lang_uz('#mob:vhr:timesheet:toolbar_title','Taqvim');
uis.lang_uz('#mob:vhr:timesheet:track_title','Qaydnoma');
uis.lang_uz('#mob:vhr:timesheet:weekend','Dam olish kuni');
uis.lang_uz('#mob:vhr:timesheet:work_pass','Ishga kelmaganlik');
uis.lang_uz('#mob:vhr:timesheet_employee_info:back','Orqaga');
uis.lang_uz('#mob:vhr:timesheet_employee_info:calendar','Taqvim');
uis.lang_uz('#mob:vhr:timesheet_employee_info:employee_statistic','Xodimning profili');
uis.lang_uz('#mob:vhr:timesheet_employee_info:schedule_requests','So''rovlar');
uis.lang_uz('#mob:vhr:timesheet_employee_info:show_all','Barchasi');
uis.lang_uz('#mob:vhr:timesheet_employee_info:track_title','Qaydnoma');
uis.lang_uz('#mob:vhr:timesheet_inout:input','Kirish');
uis.lang_uz('#mob:vhr:timesheet_inout:output','Chiqish');
uis.lang_uz('#mob:vhr:timesheet_schedule:change_change','Ish jadvalni o''zgartirish');
uis.lang_uz('#mob:vhr:timesheet_schedule:change_swap','Kunlar almashuvi');
uis.lang_uz('#mob:vhr:timesheet_schedule:dinner','Tanaffus');
uis.lang_uz('#mob:vhr:timesheet_schedule:leave','Ish joyida yo''qlik');
uis.lang_uz('#mob:vhr:timesheet_schedule:leave_full_day','Kun davomida ishda bo''lmaslik');
uis.lang_uz('#mob:vhr:timesheet_schedule:schedule','Ish jadvali');
uis.lang_uz('#mob:vhr:timesheet_schedule:schedule_hourly','Soatlik ish jadvali');
uis.lang_uz('#mob:vhr:timesheet_schedule:work_day','Ish kuni');
uis.lang_uz('#mob:vhr:timesheet_statistic:day_result_title','Kun tafsilotlari');
uis.lang_uz('#mob:vhr:timesheet_statistic:freetime','Erkin ish vaqti');
uis.lang_uz('#mob:vhr:timesheet_statistic:intime','O''z vaqtida kelgan');
uis.lang_uz('#mob:vhr:timesheet_statistic:not_worked','Ishlanmagan');
uis.lang_uz('#mob:vhr:timesheet_statistic:overtime','Qo''shimcha ishlagan');
uis.lang_uz('#mob:vhr:timesheet_statistic:plan_time','Ish jadvali bo''yicha');
uis.lang_uz('#mob:vhr:timesheet_statistic:toolbar_title','Kun tafsilotlari');
uis.lang_uz('#mob:vhr:timesheet_tracking:list_is_empty','Ro''yxat bo''sh');
uis.lang_uz('#mob:vhr:timesheet_tracking:more_tracks','Barchasi');
uis.lang_uz('#mob:vhr:today_attendance:back','Orqaga');
uis.lang_uz('#mob:vhr:today_attendance:calendar','Taqvim');
uis.lang_uz('#mob:vhr:today_attendance:close','Yopish');
uis.lang_uz('#mob:vhr:today_attendance:filter','Filtr');
uis.lang_uz('#mob:vhr:today_attendance:more_info','Tafsilotlar');
uis.lang_uz('#mob:vhr:today_attendance:sort','Saralash');
uis.lang_uz('#mob:vhr:today_attendance:sort_full','Saralash');
uis.lang_uz('#mob:vhr:today_attendance:visits','Davomat');
uis.lang_uz('#mob:vhr:today_attendance_filter_dialog:all','Barchasi');
uis.lang_uz('#mob:vhr:today_attendance_filter_dialog:close','Yopish');
uis.lang_uz('#mob:vhr:today_attendance_filter_dialog:filter','Filtr');
uis.lang_uz('#mob:vhr:today_attendance_filter_dialog:free_day','Dam olish kuni');
uis.lang_uz('#mob:vhr:today_attendance_filter_dialog:holiday','Bayram kuni');
uis.lang_uz('#mob:vhr:today_attendance_filter_dialog:intime','O''z vaqtida kelgan');
uis.lang_uz('#mob:vhr:today_attendance_filter_dialog:late','Kechikkan');
uis.lang_uz('#mob:vhr:today_attendance_filter_dialog:no_license','Litsenziya yo''q');
uis.lang_uz('#mob:vhr:today_attendance_filter_dialog:no_schedule','Ish jadvali o''rnatilmagan');
uis.lang_uz('#mob:vhr:today_attendance_filter_dialog:non_working','Belgilangan dam olish kuni');
uis.lang_uz('#mob:vhr:today_attendance_filter_dialog:nonworking_day','Belgilangan dam olish kuni');
uis.lang_uz('#mob:vhr:today_attendance_filter_dialog:not_begin','Ish vaqtidan tashqari');
uis.lang_uz('#mob:vhr:today_attendance_filter_dialog:not_come','Kelmagan');
uis.lang_uz('#mob:vhr:today_attendance_filter_dialog:not_licensed','Litsenziya yo''q');
uis.lang_uz('#mob:vhr:today_attendance_filter_dialog:select','Qabul qilish');
uis.lang_uz('#mob:vhr:today_attendance_filter_dialog:show_all','Barchasini ko''rish');
uis.lang_uz('#mob:vhr:today_attendance_filter_dialog:take_leave','So''rov yuborilgan');
uis.lang_uz('#mob:vhr:today_attendance_filter_dialog:unknown','Aniqlanmagan');
uis.lang_uz('#mob:vhr:today_timesheet:breaks','Tanaffus');
uis.lang_uz('#mob:vhr:today_timesheet:input','Kirish');
uis.lang_uz('#mob:vhr:today_timesheet:output','Chiqish');
uis.lang_uz('#mob:vhr:today_timesheet:weekend','Dam olish kuni');
uis.lang_uz('#mob:vhr:today_timesheet:work_day','Ish kuni');
uis.lang_uz('#mob:vhr:track_filter:cancel','Bekor qilish');
uis.lang_uz('#mob:vhr:track_filter:current_month','Shu oy');
uis.lang_uz('#mob:vhr:track_filter:filter','Filtr');
uis.lang_uz('#mob:vhr:track_filter:filter_tracks_title','Qaydlarni filtrlash');
uis.lang_uz('#mob:vhr:track_filter:last30day','So''nggi 30 kun');
uis.lang_uz('#mob:vhr:track_filter:last7day','So''nggi 7 kun');
uis.lang_uz('#mob:vhr:track_filter:last_month','O''tgan oy');
uis.lang_uz('#mob:vhr:track_filter:today','Bugun');
uis.lang_uz('#mob:vhr:track_filter:yesterday','Kecha');
uis.lang_uz('#mob:vhr:track_info:back','Orqaga');
uis.lang_uz('#mob:vhr:track_info:location','Koordinatalar');
uis.lang_uz('#mob:vhr:track_info:location_accuracy','Aniqlik: %1s m');
uis.lang_uz('#mob:vhr:track_info:not_valid','Yaroqsiz');
uis.lang_uz('#mob:vhr:track_info:toolbar_title','Qayd (%1s)');
uis.lang_uz('#mob:vhr:track_info:track_location','Joylashuv');
uis.lang_uz('#mob:vhr:track_info:track_note','Izoh');
uis.lang_uz('#mob:vhr:track_info:track_photo','Fotosurat');
uis.lang_uz('#mob:vhr:track_info:track_time','Vaqt');
uis.lang_uz('#mob:vhr:track_info:tracking_type','Qayd turi');
uis.lang_uz('#mob:vhr:track_widget:no_location','Joylashuv yo''q');
uis.lang_uz('#mob:vhr:track_widget:not_valid','Yaroqsiz');
uis.lang_uz('#mob:vhr:tracking:all_tracks_title','Barcha qaydlar');
uis.lang_uz('#mob:vhr:tracking:check-in','Belgilash');
uis.lang_uz('#mob:vhr:tracking:employee_close_btn','Yopish');
uis.lang_uz('#mob:vhr:tracking:employee_list_is_empty','Xodimlar ro?yxati bo?sh');
uis.lang_uz('#mob:vhr:tracking:employee_list_title','Xodimlar ro?yxati');
uis.lang_uz('#mob:vhr:tracking:employee_select_btn','Tanlash');
uis.lang_uz('#mob:vhr:tracking:employee_title','Xodimlar');
uis.lang_uz('#mob:vhr:tracking:employee_tracks_title','Xodimning qaydlari');
uis.lang_uz('#mob:vhr:tracking:filter_title','Filtr');
uis.lang_uz('#mob:vhr:tracking:fix_day','Kunni tasdiqlash');
uis.lang_uz('#mob:vhr:tracking:input','Kirish');
uis.lang_uz('#mob:vhr:tracking:more_tracks','Barchasi');
uis.lang_uz('#mob:vhr:tracking:output','Chiqish');
uis.lang_uz('#mob:vhr:tracking:search_hint','Qidiruv');
uis.lang_uz('#mob:vhr:tracking:track_at_date','%2s da %1s');
uis.lang_uz('#mob:vhr:tracking:track_input','Kirish');
uis.lang_uz('#mob:vhr:tracking:track_is_empty','Ro''yxat bo''sh');
uis.lang_uz('#mob:vhr:tracking:track_list_is_empty','Ro''yxat bo''sh');
uis.lang_uz('#mob:vhr:tracking:track_location','Joylashuv');
uis.lang_uz('#mob:vhr:tracking:track_mark','Belgilash');
uis.lang_uz('#mob:vhr:tracking:track_merger','Kun tasdiqlash');
uis.lang_uz('#mob:vhr:tracking:track_not_valid','Yaroqsiz');
uis.lang_uz('#mob:vhr:tracking:track_note','Izoh');
uis.lang_uz('#mob:vhr:tracking:track_output','Chiqish');
uis.lang_uz('#mob:vhr:tracking:track_potential_output','Ehtimoliy chiqish');
uis.lang_uz('#mob:vhr:tracking:track_time','Vaqt');
uis.lang_uz('#mob:vhr:tracking:track_title','Qaydnoma');
uis.lang_uz('#mob:vhr:tracking:track_today','Bugun %1s');
uis.lang_uz('#mob:vhr:tracking:tracking_type','Qayd turi');
uis.lang_uz('#mob:vhr:tracking_list:all_tracks_title','Barcha qaydlar');
uis.lang_uz('#mob:vhr:tracking_list:back','Orqaga');
uis.lang_uz('#mob:vhr:tracking_list:employee','Xodimlar');
uis.lang_uz('#mob:vhr:tracking_list:employee_tracks_title','Xodimning qaydlari');
uis.lang_uz('#mob:vhr:tracking_list:filter','Filtr');
uis.lang_uz('#mob:vhr:tracking_list:track_list_is_empty','Qaydlar topilmadi');
uis.lang_uz('#mob:vhr:tracking_offline:back','Orqaga');
uis.lang_uz('#mob:vhr:tracking_offline:list_is_empty','Ro''yxat bo''sh');
uis.lang_uz('#mob:vhr:tracking_offline:more_tracks','Barchasi');
uis.lang_uz('#mob:vhr:tracking_offline:sync','Sinxronlash');
uis.lang_uz('#mob:vhr:tracking_offline:sync_start','Yuborish');
uis.lang_uz('#mob:vhr:tracking_offline:toolbar_title','Oflayn qaydnoma');
uis.lang_uz('#mob:vhr:tracking_offline:track_title','Yuborilmagan qaydlar');
uis.lang_uz('#mob:vhr:tracking_offline_list:back','Orqaga');
uis.lang_uz('#mob:vhr:tracking_offline_list:list_is_empty','Ro''yxat bo''sh');
uis.lang_uz('#mob:vhr:tracking_offline_list:sync','Sinxronlash');
uis.lang_uz('#mob:vhr:tracking_offline_list:toolbar_title','Yuborilmagan qaydlar');
commit;
end;
/
