name: Tag on Merge to Master

on:
  workflow_run:
    workflows: ["Build and Push SQL Changes"]
    types:
      - completed

jobs:
  create-tag-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Check if VERSION.md exists
      run: |
        if [ ! -f "VERSION.md" ]; then
          echo "Error: VERSION.md file not found"
          exit 1
        fi

    - name: Read version from VERSION.md
      id: read-version
      run: |
        export TAG_NAME=$(cat VERSION.md)
        echo "Version read from VERSION.md: $TAG_NAME"
        echo "::set-output name=tag_name::$TAG_NAME"

    - name: Create tag
      run: |
        git tag "${{ steps.read-version.outputs.tag_name }}" -m "Tag created on merge to master"
        git push origin "${{ steps.read-version.outputs.tag_name }}"

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: ''  # Add file paths to include in the release (leave empty for just the tag)
        tag_name: "${{ steps.read-version.outputs.tag_name }}"
        title: "Release ${{ steps.read-version.outputs.tag_name }}"
        body: "Release notes or description for version ${{ steps.read-version.outputs.tag_name }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
