name: Tag on Merge to Master

on:
  push:
    branches:
      - master

jobs:
  create-tag-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Check if VERSION.md exists
      run: |
        if [ ! -f "VERSION.md" ]; then
          echo "Error: VERSION.md file not found"
          exit 1
        fi

    - name: Read version from VERSION.md
      id: read-version
      run: |
        export TAG_NAME=$(cat VERSION.md)
        echo "Version read from VERSION.md: $TAG_NAME"
        echo "::set-output name=tag_name::$TAG_NAME"

    - name: Create tag
      run: |
        git tag "${{ steps.read-version.outputs.tag_name }}" -m "Tag created on merge to master"
        git push origin "${{ steps.read-version.outputs.tag_name }}"

    - name: Generate release notes
      id: release-notes
      run: |
        # Your release notes generation script here
        # Save the result to an output variable
        echo "::set-output name=release_notes::$(your-script.sh)"

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: ''
        tag_name: "${{ steps.read-version.outputs.tag_name }}"
        title: "Release ${{ steps.read-version.outputs.tag_name }}"
        body: "${{ steps.release-notes.outputs.release_notes }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
