prompt PATH TRANSLATE /vhr/hpd/audit/journal_audit_details
begin
uis.lang_en('#f:/vhr/hpd/audit/journal_audit_details','Audit Log Details');
uis.lang_en('ui-vhr183:based on doc','Dismissal Proof');
uis.lang_en('ui-vhr183:begin date','Start');
uis.lang_en('ui-vhr183:change data','Change data');
uis.lang_en('ui-vhr183:change date','Change Date');
uis.lang_en('ui-vhr183:coefficient','Coefficient');
uis.lang_en('ui-vhr183:concluding term','Concluding Term');
uis.lang_en('ui-vhr183:contract date','Contract Date');
uis.lang_en('ui-vhr183:contract number','Contract Number');
uis.lang_en('ui-vhr183:currency name','Currency');
uis.lang_en('ui-vhr183:days limit','Vacation Days');
uis.lang_en('ui-vhr183:dismissal date','Dismissal Date');
uis.lang_en('ui-vhr183:dismissal reason name','Dismissal Reason');
uis.lang_en('ui-vhr183:division name','Department');
uis.lang_en('ui-vhr183:employment source name','Employment Source');
uis.lang_en('ui-vhr183:employment type name','Employment Type');
uis.lang_en('ui-vhr183:end date','End');
uis.lang_en('ui-vhr183:file name','File');
uis.lang_en('ui-vhr183:fixed term','Fixed-term Labour Contract');
uis.lang_en('ui-vhr183:fixed term base name','Fixed-term Contract Reason');
uis.lang_en('ui-vhr183:free time','Off Schedule');
uis.lang_en('ui-vhr183:fte','Full-time equivalent');
uis.lang_en('ui-vhr183:hiring conditions','Hiring Requirements');
uis.lang_en('ui-vhr183:hiring date','Hiring Date');
uis.lang_en('ui-vhr183:indicator name','Variable');
uis.lang_en('ui-vhr183:indicator names','Variables');
uis.lang_en('ui-vhr183:indicator value','Variable Value');
uis.lang_en('ui-vhr183:job name','Job');
uis.lang_en('ui-vhr183:journal date','Document Date');
uis.lang_en('ui-vhr183:journal number','Document Number');
uis.lang_en('ui-vhr183:journal type name','Document Type');
uis.lang_en('ui-vhr183:note','Note');
uis.lang_en('ui-vhr183:oper type name','Wage Payment');
uis.lang_en('ui-vhr183:order no','No.');
uis.lang_en('ui-vhr183:other conditions','Other Requirements');
uis.lang_en('ui-vhr183:overtime','Overtime');
uis.lang_en('ui-vhr183:overtime date','Date');
uis.lang_en('ui-vhr183:overtime total','Overtime');
uis.lang_en('ui-vhr183:person name','Natural Person');
uis.lang_en('ui-vhr183:posted','Posted');
uis.lang_en('ui-vhr183:rank name','Rank');
uis.lang_en('ui-vhr183:reason name','Reason');
uis.lang_en('ui-vhr183:region name','Region');
uis.lang_en('ui-vhr183:representative basis','Representative Reason');
uis.lang_en('ui-vhr183:robot name','Position');
uis.lang_en('ui-vhr183:schedule name','Work Schedule');
uis.lang_en('ui-vhr183:sick leave number','Sick Note Number');
uis.lang_en('ui-vhr183:staff name','Employee');
uis.lang_en('ui-vhr183:transfer base','Transfer Proof');
uis.lang_en('ui-vhr183:transfer begin','Transfer Start Date');
uis.lang_en('ui-vhr183:transfer end','Transfer End Date');
uis.lang_en('ui-vhr183:transfer reason','Transfer Reason');
uis.lang_en('ui-vhr183:trial period','Initial Assessment Period (days)');
uis.lang_en('ui-vhr183:turnout time','Turnout');
uis.lang_en('ui-vhr183:workplace equipment','Workspace Equipment');
commit;
end;
/
